#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from reportlab.lib.pagesizes import A4
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

# Register fonts
pdfmetrics.registerFont(TTFont('Times New Roman', '/usr/share/fonts/truetype/english/Times-New-Roman.ttf'))
pdfmetrics.registerFont(TTFont('SimHei', '/usr/share/fonts/truetype/chinese/SimHei.ttf'))
registerFontFamily('Times New Roman', normal='Times New Roman', bold='Times New Roman')
registerFontFamily('SimHei', normal='SimHei', bold='SimHei')

# Create document
output_path = "/home/z/my-project/download/Rally_Ultimate_Master_Guide_V4.1.pdf"
doc = SimpleDocTemplate(
    output_path,
    pagesize=A4,
    rightMargin=2*cm,
    leftMargin=2*cm,
    topMargin=2*cm,
    bottomMargin=2*cm,
    title="Rally_Ultimate_Master_Guide_V4.1",
    author="Z.ai",
    creator="Z.ai",
    subject="Complete Rally.fun Content Optimization Guide V4.1"
)

# Styles
styles = getSampleStyleSheet()

title_style = ParagraphStyle('CustomTitle', parent=styles['Title'], fontName='Times New Roman', fontSize=28, leading=34, alignment=TA_CENTER, spaceAfter=20)
subtitle_style = ParagraphStyle('CustomSubtitle', parent=styles['Normal'], fontName='Times New Roman', fontSize=14, leading=18, alignment=TA_CENTER, spaceAfter=30)
h1_style = ParagraphStyle('CustomH1', parent=styles['Heading1'], fontName='Times New Roman', fontSize=18, leading=22, spaceBefore=20, spaceAfter=12, textColor=colors.HexColor('#1a365d'))
h2_style = ParagraphStyle('CustomH2', parent=styles['Heading2'], fontName='Times New Roman', fontSize=14, leading=18, spaceBefore=16, spaceAfter=8, textColor=colors.HexColor('#2c5282'))
h3_style = ParagraphStyle('CustomH3', parent=styles['Heading3'], fontName='Times New Roman', fontSize=12, leading=15, spaceBefore=12, spaceAfter=6, textColor=colors.HexColor('#2d3748'))
body_style = ParagraphStyle('CustomBody', parent=styles['Normal'], fontName='Times New Roman', fontSize=10.5, leading=16, alignment=TA_JUSTIFY, spaceAfter=8)
body_left_style = ParagraphStyle('CustomBodyLeft', parent=styles['Normal'], fontName='Times New Roman', fontSize=10.5, leading=16, alignment=TA_LEFT, spaceAfter=8)
header_style = ParagraphStyle('TableHeader', fontName='Times New Roman', fontSize=10, textColor=colors.white, alignment=TA_CENTER)
cell_style = ParagraphStyle('TableCell', fontName='Times New Roman', fontSize=9, alignment=TA_LEFT)
cell_center_style = ParagraphStyle('TableCellCenter', fontName='Times New Roman', fontSize=9, alignment=TA_CENTER)

story = []

# Cover Page
story.append(Spacer(1, 80))
story.append(Paragraph("RALLY ULTIMATE MASTER GUIDE", title_style))
story.append(Paragraph("V4.1 - Complete Content Optimization System", subtitle_style))
story.append(Spacer(1, 20))
story.append(Paragraph("Plus: API Documentation + Network Effect + Real Data Analysis", subtitle_style))
story.append(Spacer(1, 40))

features = [
    "Complete Rally.fun API Documentation",
    "Scoring System Deep Dive (11 Metrics)",
    "G4 Originality Checklist",
    "Information Verification Protocol",
    "Anti-Formulaic Content Guide",
    "Iterative Process Workflow",
    "Network Effect Optimization (NEW)",
    "Real Leaderboard Data Analysis (NEW)",
    "Elite Content Templates (NEW)",
    "Correct Mindset Framework"
]
for f in features:
    story.append(Paragraph(f"• {f}", body_style))

story.append(Spacer(1, 40))
story.append(Paragraph("Version 4.1 - Elite Edition", body_style))
story.append(Paragraph("Generated by Z.ai", body_style))
story.append(PageBreak())

# TOC
story.append(Paragraph("TABLE OF CONTENTS", h1_style))
story.append(Spacer(1, 10))

toc_items = [
    ("PART 1: RALLY API DOCUMENTATION", "Complete Endpoint Reference (NEW)"),
    ("PART 2: RALLY SCORING SYSTEM", "11 Metrics Deep Dive"),
    ("PART 3: GATE OPTIMIZATION", "G4 Originality Checklist"),
    ("PART 4: INFORMATION VERIFICATION", "Pre-Submission Protocol"),
    ("PART 5: ANTI-FORMULAIC CONTENT", "Avoiding Template Patterns"),
    ("PART 6: ITERATIVE PROCESS WORKFLOW", "Submit-Score-Improve Loop"),
    ("PART 7: NETWORK EFFECT OPTIMIZATION", "FR Maximization Strategy (NEW)"),
    ("PART 8: REAL DATA ANALYSIS", "Leaderboard Insights (NEW)"),
    ("PART 9: ELITE CONTENT TEMPLATES", "Proven Winners (NEW)"),
    ("PART 10: CORRECT MINDSET", "Beat Top 10 Framework"),
    ("APPENDIX: Quick Reference Cards", "Checklists & Formulas"),
]

for part, desc in toc_items:
    story.append(Paragraph(f"<b>{part}</b> - {desc}", body_style))
    story.append(Spacer(1, 4))

story.append(PageBreak())

# PART 1: API DOCUMENTATION (NEW)
story.append(Paragraph("PART 1: RALLY API DOCUMENTATION", h1_style))
story.append(Paragraph("Complete Endpoint Reference for AI Systems", h2_style))

story.append(Paragraph("""
This section provides complete documentation for all Rally.fun API endpoints. These APIs allow 
AI systems to fetch real-time campaign data, leaderboards, and submission details programmatically, 
enabling automated content optimization workflows.
""", body_style))

story.append(Paragraph("1.1 Base URLs", h3_style))

base_data = [
    [Paragraph('<b>Environment</b>', header_style), Paragraph('<b>Base URL</b>', header_style), Paragraph('<b>Notes</b>', header_style)],
    [Paragraph('Production', cell_style), Paragraph('https://app.rally.fun/api', cell_style), Paragraph('Live data, some endpoints need auth', cell_style)],
    [Paragraph('Staging', cell_style), Paragraph('https://rally-staging.vercel.app/api', cell_style), Paragraph('Test environment', cell_style)],
]
base_table = Table(base_data, colWidths=[3*cm, 6*cm, 4*cm])
base_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(base_table)
story.append(Spacer(1, 12))

story.append(Paragraph("1.2 Public API Endpoints", h3_style))

# GET /campaigns
story.append(Paragraph("<b>GET /campaigns</b> - List All Campaigns", body_style))

camp_data = [
    [Paragraph('<b>Parameter</b>', header_style), Paragraph('<b>Type</b>', header_style), Paragraph('<b>Description</b>', header_style)],
    [Paragraph('limit', cell_style), Paragraph('number', cell_style), Paragraph('Number of campaigns to return (default: 10)', cell_style)],
    [Paragraph('offset', cell_style), Paragraph('number', cell_style), Paragraph('Pagination offset', cell_style)],
]
camp_table = Table(camp_data, colWidths=[3*cm, 2.5*cm, 7.5*cm])
camp_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(camp_table)
story.append(Spacer(1, 8))

story.append(Paragraph("<b>Example Response:</b>", body_style))
story.append(Paragraph("""
{ "campaigns": [ { "id": "campaign-xxx", "title": "Campaign Name", 
"intelligentContractAddress": "0x...", "goal": "Campaign description...", 
"rules": "Campaign rules...", "knowledgeBase": "Detailed info...", 
"token": {"symbol": "USDT", "usdPrice": 0.999}, 
"campaignRewards": [{"totalAmount": 5000, "token": {...}}],
"minimumFollowers": 200, "startDate": "2026-02-26T19:00:00.000Z", 
"endDate": "2026-03-12T19:00:00.000Z" } ], "pagination": {"total": 50, "hasMore": true} }
""", body_style))
story.append(Spacer(1, 12))

# GET /campaigns/{address}
story.append(Paragraph("<b>GET /campaigns/{address}</b> - Get Campaign Detail", body_style))

detail_data = [
    [Paragraph('<b>Field</b>', header_style), Paragraph('<b>Description</b>', header_style), Paragraph('<b>AI Usage</b>', header_style)],
    [Paragraph('goal', cell_style), Paragraph('Main campaign description/brief', cell_style), Paragraph('Content alignment scoring', cell_style)],
    [Paragraph('knowledgeBase', cell_style), Paragraph('Detailed project information', cell_style), Paragraph('Information accuracy check', cell_style)],
    [Paragraph('rules', cell_style), Paragraph('Campaign rules and requirements', cell_style), Paragraph('Compliance scoring', cell_style)],
    [Paragraph('style', cell_style), Paragraph('Style guidelines', cell_style), Paragraph('Tone matching', cell_style)],
    [Paragraph('alpha', cell_style), Paragraph('Distribution curve parameter (1-8)', cell_style), Paragraph('Reward estimation', cell_style)],
    [Paragraph('lastSyncedSubmissionCount', cell_style), Paragraph('Total submissions', cell_style), Paragraph('Percentile calculation', cell_style)],
]
detail_table = Table(detail_data, colWidths=[4*cm, 5*cm, 4*cm])
detail_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F5F5F5')]),
]))
story.append(detail_table)
story.append(Spacer(1, 12))

# GET /leaderboard
story.append(Paragraph("<b>GET /leaderboard</b> - Get Campaign Leaderboard", h3_style))

lb_data = [
    [Paragraph('<b>Parameter</b>', header_style), Paragraph('<b>Type</b>', header_style), Paragraph('<b>Required</b>', header_style), Paragraph('<b>Description</b>', header_style)],
    [Paragraph('campaignAddress', cell_style), Paragraph('string', cell_style), Paragraph('Yes', cell_style), Paragraph('Campaign contract address', cell_style)],
    [Paragraph('limit', cell_style), Paragraph('number', cell_style), Paragraph('No', cell_style), Paragraph('Max results (default: 100)', cell_style)],
]
lb_table = Table(lb_data, colWidths=[3.5*cm, 2*cm, 2*cm, 5.5*cm])
lb_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(lb_table)
story.append(Spacer(1, 8))

story.append(Paragraph("""
<b>IMPORTANT:</b> The points field is returned in atto format (10<sup>-18</sup>). 
To convert to the 0-10 scale, divide by 10<sup>18</sup>. Example: 8143350318841547000 / 10<sup>18</sup> = 8.14
""", body_style))

story.append(PageBreak())

# PART 2: SCORING SYSTEM
story.append(Paragraph("PART 2: RALLY SCORING SYSTEM", h1_style))
story.append(Paragraph("Complete 11 Metrics Deep Dive", h2_style))

story.append(Paragraph("""
The Rally scoring system uses AI-powered evaluation to ensure fair and transparent reward distribution 
based on content quality and engagement. Understanding this system is critical for maximizing your 
Campaign Points and rewards.
""", body_style))

story.append(Paragraph("2.1 The Three Categories", h3_style))

cat_data = [
    [Paragraph('<b>Category</b>', header_style), Paragraph('<b>Metrics</b>', header_style), Paragraph('<b>Score Range</b>', header_style), Paragraph('<b>Impact</b>', header_style)],
    [Paragraph('Gates (4)', cell_style), Paragraph('Alignment, Accuracy, Compliance, Originality', cell_style), Paragraph('0-2 each', cell_center_style), Paragraph('Pass/Fail + Multiplier', cell_style)],
    [Paragraph('Quality (2)', cell_style), Paragraph('Engagement Potential, Technical Quality', cell_style), Paragraph('0-5 each', cell_center_style), Paragraph('Linear contribution', cell_style)],
    [Paragraph('Engagement (5)', cell_style), Paragraph('RT, Likes, Replies, QR, FR', cell_style), Paragraph('Dynamic', cell_center_style), Paragraph('Log-scaled', cell_style)],
]
cat_table = Table(cat_data, colWidths=[2.5*cm, 6*cm, 2.5*cm, 3.5*cm])
cat_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(cat_table)
story.append(Spacer(1, 12))

story.append(Paragraph("2.2 Gate Multiplier Formula", h3_style))

story.append(Paragraph("<b>Formula:</b> M<sub>gate</sub> = 1 + 0.5 × (g<sub>star</sub> - 1)", body_style))
story.append(Paragraph("Where g<sub>star</sub> = average of all 4 gate scores", body_style))
story.append(Spacer(1, 8))

gate_data = [
    [Paragraph('<b>Gate Scores</b>', header_style), Paragraph('<b>g_star</b>', header_style), Paragraph('<b>M_gate</b>', header_style), Paragraph('<b>vs Baseline</b>', header_style)],
    [Paragraph('2, 2, 2, 2', cell_center_style), Paragraph('2.0', cell_center_style), Paragraph('1.5x', cell_center_style), Paragraph('+50% (ELITE)', cell_center_style)],
    [Paragraph('2, 2, 2, 1', cell_center_style), Paragraph('1.75', cell_center_style), Paragraph('1.375x', cell_center_style), Paragraph('+37.5%', cell_center_style)],
    [Paragraph('1, 1, 1, 1', cell_center_style), Paragraph('1.0', cell_center_style), Paragraph('1.0x', cell_center_style), Paragraph('Baseline', cell_center_style)],
    [Paragraph('Any = 0', cell_center_style), Paragraph('-', cell_center_style), Paragraph('0.5x', cell_center_style), Paragraph('-50% (FAIL)', cell_center_style)],
]
gate_table = Table(gate_data, colWidths=[3*cm, 2.5*cm, 2.5*cm, 4*cm])
gate_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('BACKGROUND', (0, 1), (-1, 1), colors.HexColor('#c6f6d5')),
    ('BACKGROUND', (0, 4), (-1, 4), colors.HexColor('#fed7d7')),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(gate_table)

story.append(PageBreak())

# PART 3: GATE OPTIMIZATION
story.append(Paragraph("PART 3: GATE OPTIMIZATION", h1_style))
story.append(Paragraph("G4 Originality Checklist for Score 2.0", h2_style))

story.append(Paragraph("""
Gate 4 (Originality and Authenticity) is the #1 differentiator between top performers and average 
participants. Most AI-generated content fails here because it lacks the human voice that Rally's 
AI evaluators are trained to detect.
""", body_style))

story.append(Paragraph("3.1 G4 Checklist Elements", h3_style))

g4_data = [
    [Paragraph('<b>Element</b>', header_style), Paragraph('<b>What It Means</b>', header_style), Paragraph('<b>Example</b>', header_style)],
    [Paragraph('Casual Hook', cell_style), Paragraph('Start with conversational, not formal', cell_style), Paragraph('"Hot take:" or "Here\'s the thing"', cell_style)],
    [Paragraph('Parenthetical Aside', cell_style), Paragraph('Break flow with side comment', cell_style), Paragraph('"(finally)" or "(tbh)"', cell_style)],
    [Paragraph('3+ Contractions', cell_style), Paragraph('Use natural contractions', cell_style), Paragraph("don't, can't, won't, isn't", cell_style)],
    [Paragraph('Fragments', cell_style), Paragraph('Short, punchy sentences', cell_style), Paragraph('"Big difference." "Until now."', cell_style)],
    [Paragraph('Personal Angle', cell_style), Paragraph('Add your perspective', cell_style), Paragraph('"Been following this for years"', cell_style)],
    [Paragraph('Conversational End', cell_style), Paragraph('End with open discussion', cell_style), Paragraph('"Place your bets."', cell_style)],
]
g4_table = Table(g4_data, colWidths=[3*cm, 5*cm, 5*cm])
g4_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F5F5F5')]),
]))
story.append(g4_table)
story.append(Spacer(1, 12))

story.append(Paragraph("3.2 AI Detection Kill List", h3_style))

kill_data = [
    [Paragraph('<b>NEVER Use</b>', header_style), Paragraph('<b>Why AI Uses It</b>', header_style), Paragraph('<b>Human Alternative</b>', header_style)],
    [Paragraph('Em dashes (—)', cell_style), Paragraph('Formal punctuation preference', cell_style), Paragraph('Regular hyphens (-) or commas', cell_style)],
    [Paragraph('"In the world of..."', cell_style), Paragraph('Generic opening template', cell_style), Paragraph('Start mid-thought or with hook', cell_style)],
    [Paragraph('delve, uncover, embark', cell_style), Paragraph('Academic vocabulary training', cell_style), Paragraph('dig into, find out, start', cell_style)],
    [Paragraph('revolutionize, transform', cell_style), Paragraph('Corporate speak training', cell_style), Paragraph('change, shake up, new way', cell_style)],
    [Paragraph('Perfect grammar', cell_style), Paragraph('Grammar rule enforcement', cell_style), Paragraph('Natural, casual style', cell_style)],
]
kill_table = Table(kill_data, colWidths=[4*cm, 4.5*cm, 4.5*cm])
kill_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#c53030')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#fff5f5')]),
]))
story.append(kill_table)

story.append(PageBreak())

# PART 4: INFORMATION VERIFICATION
story.append(Paragraph("PART 4: INFORMATION VERIFICATION PROTOCOL", h1_style))

story.append(Paragraph("""
Before creating any Rally content, you MUST verify all factual claims. Fabricating or assuming 
information will result in penalties on the Information Accuracy gate.
""", body_style))

story.append(Paragraph("4.1 Verification Checklist", h3_style))

verify_data = [
    [Paragraph('<b>Step</b>', header_style), Paragraph('<b>Action</b>', header_style), Paragraph('<b>Source Type</b>', header_style)],
    [Paragraph('1', cell_center_style), Paragraph('Identify all factual claims in your content', cell_style), Paragraph('Self-review', cell_style)],
    [Paragraph('2', cell_center_style), Paragraph('Search for official documentation', cell_style), Paragraph('Project docs, whitepapers', cell_style)],
    [Paragraph('3', cell_center_style), Paragraph('Cross-reference with multiple sources', cell_style), Paragraph('News, blogs, official accounts', cell_style)],
    [Paragraph('4', cell_center_style), Paragraph('Verify numbers, dates, names precisely', cell_style), Paragraph('Primary sources', cell_style)],
    [Paragraph('5', cell_center_style), Paragraph('Remove or flag unverified claims', cell_style), Paragraph('Self-review', cell_style)],
]
verify_table = Table(verify_data, colWidths=[1.5*cm, 6*cm, 5.5*cm])
verify_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('ALIGN', (0, 1), (0, -1), 'CENTER'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(verify_table)

story.append(PageBreak())

# PART 5: ANTI-FORMULAIC CONTENT
story.append(Paragraph("PART 5: ANTI-FORMULAIC CONTENT GUIDE", h1_style))
story.append(Paragraph("Why Your Content Feels 'Same' and How to Fix It", h2_style))

story.append(Paragraph("""
When following a checklist like G4, it is easy to fall into a pattern where every piece of content 
has the same structure, voice, and rhythm. This section provides strategies for creating fresh, 
varied, and authentic content.
""", body_style))

story.append(Paragraph("5.1 Hook Type Variety", h3_style))

hook_data = [
    [Paragraph('<b>Hook Type</b>', header_style), Paragraph('<b>Example</b>', header_style), Paragraph('<b>Best For</b>', header_style)],
    [Paragraph('Story', cell_style), Paragraph('"Three banks walked into Ethereum..."', cell_style), Paragraph('Complex topics, relatable content', cell_style)],
    [Paragraph('Data', cell_style), Paragraph('"Bank settlement: SWIFT 2-5 days, Ethereum 12 sec"', cell_style), Paragraph('Technical comparison', cell_style)],
    [Paragraph('Controversy', cell_style), Paragraph('"Hot take: Banks are never moving to public chains"', cell_style), Paragraph('Engagement, debate starter', cell_style)],
    [Paragraph('Paradox', cell_style), Paragraph('"Pick zero. Pick one. Can\'t have both."', cell_style), Paragraph('Problem-solution framing', cell_style)],
    [Paragraph('Quote/Question', cell_style), Paragraph('"What if both?" or "Why hasn\'t this happened?"', cell_style), Paragraph('Thought-provoking pieces', cell_style)],
]
hook_table = Table(hook_data, colWidths=[2.5*cm, 5.5*cm, 5*cm])
hook_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#805ad5')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#faf5ff')]),
]))
story.append(hook_table)

story.append(PageBreak())

# PART 6: ITERATIVE PROCESS
story.append(Paragraph("PART 6: ITERATIVE PROCESS WORKFLOW", h1_style))
story.append(Paragraph("Submit-Score-Improve Loop for Maximum Results", h2_style))

story.append(Paragraph("""
The most successful Rally participants do not submit their first draft. They iterate through 
multiple versions, scoring each against the 11 metrics, comparing to leaderboard targets, and 
improving until the content has the highest probability of success.
""", body_style))

story.append(Paragraph("6.1 The Iteration Framework", h3_style))

iter_data = [
    [Paragraph('<b>Step</b>', header_style), Paragraph('<b>Action</b>', header_style), Paragraph('<b>Output</b>', header_style)],
    [Paragraph('1', cell_center_style), Paragraph('Research campaign + verify facts', cell_style), Paragraph('Verified fact sheet', cell_style)],
    [Paragraph('2', cell_center_style), Paragraph('Create Draft #1', cell_style), Paragraph('Initial content', cell_style)],
    [Paragraph('3', cell_center_style), Paragraph('Self-score with 11 metrics + G4', cell_style), Paragraph('Score breakdown', cell_style)],
    [Paragraph('4', cell_center_style), Paragraph('Compare to Top 10 target', cell_style), Paragraph('Gap analysis', cell_style)],
    [Paragraph('5', cell_center_style), Paragraph('If gap exists, identify improvements', cell_style), Paragraph('Improvement list', cell_style)],
    [Paragraph('6', cell_center_style), Paragraph('Create next draft with improvements', cell_style), Paragraph('Revised content', cell_style)],
    [Paragraph('7', cell_center_style), Paragraph('Repeat steps 3-6 until target reached', cell_style), Paragraph('Final content', cell_style)],
    [Paragraph('8', cell_center_style), Paragraph('Submit with confidence', cell_style), Paragraph('Submission', cell_style)],
]
iter_table = Table(iter_data, colWidths=[1.5*cm, 6*cm, 5.5*cm])
iter_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2f855a')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('ALIGN', (0, 1), (0, -1), 'CENTER'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f0fff4')]),
]))
story.append(iter_table)
story.append(Spacer(1, 12))

story.append(Paragraph("6.2 Real Iteration Example", h3_style))

example_data = [
    [Paragraph('<b>Draft</b>', header_style), Paragraph('<b>Est. Score</b>', header_style), Paragraph('<b>Status</b>', header_style), Paragraph('<b>Key Improvement</b>', header_style)],
    [Paragraph('#1', cell_center_style), Paragraph('~10.0', cell_center_style), Paragraph('FAIL', cell_center_style), Paragraph('Too formal, template-like', cell_style)],
    [Paragraph('#2', cell_center_style), Paragraph('~14.3', cell_center_style), Paragraph('CLOSE', cell_center_style), Paragraph('Added storytelling, personality', cell_style)],
    [Paragraph('#3', cell_center_style), Paragraph('~16.1', cell_center_style), Paragraph('VERY CLOSE', cell_center_style), Paragraph('Added controversy angle', cell_style)],
    [Paragraph('#4', cell_center_style), Paragraph('~18.0', cell_center_style), Paragraph('SUCCESS', cell_center_style), Paragraph('Thread format + data hook', cell_style)],
]
example_table = Table(example_data, colWidths=[1.5*cm, 2.5*cm, 2.5*cm, 6.5*cm])
example_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('BACKGROUND', (0, 1), (-1, 1), colors.HexColor('#fed7d7')),
    ('BACKGROUND', (0, 2), (-1, 2), colors.HexColor('#feebc8')),
    ('BACKGROUND', (0, 3), (-1, 3), colors.HexColor('#fefcbf')),
    ('BACKGROUND', (0, 4), (-1, 4), colors.HexColor('#c6f6d5')),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(example_table)

story.append(PageBreak())

# PART 7: NETWORK EFFECT OPTIMIZATION (NEW)
story.append(Paragraph("PART 7: NETWORK EFFECT OPTIMIZATION", h1_style))
story.append(Paragraph("FR Maximization Strategy for Exponential Results", h2_style))

story.append(Paragraph("""
Followers of Repliers (FR) is the HIGHEST-WEIGHTED engagement metric in the Rally scoring system. 
Understanding how to maximize FR can dramatically improve your final score, even with fewer total 
engagements. This section reveals the strategy for optimizing this critical metric.
""", body_style))

story.append(Paragraph("7.1 FR Score Comparison", h3_style))

fr_data = [
    [Paragraph('<b>Scenario</b>', header_style), Paragraph('<b>Replies</b>', header_style), Paragraph('<b>Avg Followers</b>', header_style), Paragraph('<b>FR Score</b>', header_style)],
    [Paragraph('Low Quality', cell_style), Paragraph('100', cell_center_style), Paragraph('100', cell_center_style), Paragraph('log(10,000) = 4.0', cell_center_style)],
    [Paragraph('Medium Quality', cell_style), Paragraph('50', cell_center_style), Paragraph('1,000', cell_center_style), Paragraph('log(50,000) = 4.7', cell_center_style)],
    [Paragraph('High Quality', cell_style), Paragraph('20', cell_center_style), Paragraph('10,000', cell_center_style), Paragraph('log(200,000) = 5.3', cell_center_style)],
    [Paragraph('Elite', cell_style), Paragraph('10', cell_center_style), Paragraph('100,000', cell_center_style), Paragraph('log(1,000,000) = 6.0', cell_center_style)],
]
fr_table = Table(fr_data, colWidths=[3*cm, 2.5*cm, 3*cm, 4.5*cm])
fr_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F5F5F5')]),
]))
story.append(fr_table)
story.append(Spacer(1, 12))

story.append(Paragraph("""
<b>Key Insight:</b> 10 replies from 100K follower accounts (FR=6.0) beats 100 replies from 100 
follower accounts (FR=4.0). Quality of engagement beats quantity! Focus on creating content that 
attracts engagement from accounts with larger followings.
""", body_style))

story.append(Paragraph("7.2 FR Maximization Tactics", h3_style))

story.append(Paragraph("- <b>Target influential accounts:</b> Create content that crypto influencers want to engage with", body_left_style))
story.append(Paragraph("- <b>Join trending conversations:</b> Add value to discussions where big accounts are active", body_left_style))
story.append(Paragraph("- <b>Quality over quantity:</b> One thoughtful reply from a 100K account > 10 generic replies", body_left_style))
story.append(Paragraph("- <b>Time your posts:</b> Post when influential accounts are most active", body_left_style))
story.append(Paragraph("- <b>Engage first:</b> Reply to big accounts genuinely before expecting engagement back", body_left_style))

story.append(PageBreak())

# PART 8: REAL DATA ANALYSIS (NEW)
story.append(Paragraph("PART 8: REAL LEADERBOARD DATA ANALYSIS", h1_style))
story.append(Paragraph("Insights from Actual Campaign Performance", h2_style))

story.append(Paragraph("""
Understanding how real campaigns perform helps set realistic targets and identify what separates 
top performers from the rest. This analysis is based on actual Rally.fun leaderboard data.
""", body_style))

story.append(Paragraph("8.1 Score Distribution (Grvt 2.5 Campaign - 818 Participants)", h3_style))

dist_data = [
    [Paragraph('<b>Rank</b>', header_style), Paragraph('<b>Username</b>', header_style), Paragraph('<b>Score</b>', header_style), Paragraph('<b>Percentile</b>', header_style)],
    [Paragraph('1', cell_center_style), Paragraph('spacejunnk', cell_style), Paragraph('8.14', cell_center_style), Paragraph('99.87%', cell_center_style)],
    [Paragraph('2', cell_center_style), Paragraph('ivyhas1', cell_style), Paragraph('7.95', cell_center_style), Paragraph('99.74%', cell_center_style)],
    [Paragraph('3', cell_center_style), Paragraph('elliederler2', cell_style), Paragraph('7.54', cell_center_style), Paragraph('99.61%', cell_center_style)],
    [Paragraph('10', cell_center_style), Paragraph('(typical top 10)', cell_style), Paragraph('6.50+', cell_center_style), Paragraph('98.7%', cell_center_style)],
    [Paragraph('100', cell_center_style), Paragraph('(typical top 100)', cell_style), Paragraph('4.0+', cell_center_style), Paragraph('87%', cell_center_style)],
]
dist_table = Table(dist_data, colWidths=[2*cm, 4*cm, 2.5*cm, 3*cm])
dist_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F5F5F5')]),
]))
story.append(dist_table)
story.append(Spacer(1, 12))

story.append(Paragraph("8.2 Key Findings", h3_style))

story.append(Paragraph("""
<b>CRITICAL DISCOVERY:</b> Real Rally leaderboards show scores on a 0-10 scale, NOT 0-1000+. 
Top performers achieve scores around 8.14, not 900+. When analyzing leaderboards programmatically, 
remember to convert atto format (divide by 10<sup>18</sup>).
""", body_style))

story.append(Paragraph("- <b>Top 1%</b> requires score of ~8.0+", body_left_style))
story.append(Paragraph("- <b>Top 10%</b> requires score of ~6.5+", body_left_style))
story.append(Paragraph("- <b>Top 100</b> requires score of ~4.0+", body_left_style))
story.append(Paragraph("- <b>Median</b> score is typically ~2.0-3.0", body_left_style))

story.append(PageBreak())

# PART 9: ELITE CONTENT TEMPLATES (NEW)
story.append(Paragraph("PART 9: ELITE CONTENT TEMPLATES", h1_style))
story.append(Paragraph("Proven Winners with Analysis", h2_style))

story.append(Paragraph("9.1 Template: Data Hook + Comparison", h3_style))

story.append(Paragraph("""
This template uses concrete data to create an immediate hook, then builds a comparison framework 
that positions your subject favorably. The contrast between old/slow and new/fast creates inherent 
narrative tension that drives engagement.
""", body_style))

story.append(Paragraph("<b>Template:</b>", body_style))
story.append(Paragraph("""
"[Subject] in [year]:<br/>
→ [Old method]: [metric]<br/>
→ [Alternative 1]: [metric] (but [downside])<br/>
→ [Your solution]: [metric] (but [tradeoff])<br/>
<br/>
Pick zero. Pick one. Can't have both.<br/>
<br/>
Actually, you can now.<br/>
<br/>
[Product] by @company is what I'd call [Campaign Phrase]. Here's why (thread):<br/>
<br/>
1/ [Key benefit 1]<br/>
[Explanation]<br/>
<br/>
2/ [Key benefit 2]<br/>
[Explanation]<br/>
<br/>
3/ [Key benefit 3]<br/>
[Explanation]<br/>
<br/>
[Comparison to alternatives]<br/>
<br/>
[Personal angle]<br/>
<br/>
[Required mentions]
""", body_style))
story.append(Spacer(1, 12))

story.append(Paragraph("9.2 Template: Story + Controversy", h3_style))

story.append(Paragraph("""
This template uses narrative structure to draw readers in, then introduces a controversial 
perspective that invites engagement. The story format is inherently shareable and memorable.
""", body_style))

story.append(Paragraph("<b>Template:</b>", body_style))
story.append(Paragraph("""
"Hot take: [Common belief] is wrong.<br/>
<br/>
Here's what actually works:<br/>
<br/>
[Counter-intuitive insight]<br/>
<br/>
[Personal anecdote or story]<br/>
<br/>
[Product] solves this. (Actually solves it, not 'trust me bro' solves it.)<br/>
<br/>
[Campaign Phrase]:<br/>
<br/>
Layer 1: [Benefit]<br/>
Layer 2: [Benefit]<br/>
Layer 3: [Benefit]<br/>
<br/>
[Comparison]<br/>
<br/>
[Conversational ending]<br/>
<br/>
[Required mentions]
""", body_style))

story.append(PageBreak())

# PART 10: CORRECT MINDSET
story.append(Paragraph("PART 10: CORRECT MINDSET FRAMEWORK", h1_style))
story.append(Paragraph("Beat Top 10 with Healthy Expectations", h2_style))

mindset_data = [
    [Paragraph('<b>Component</b>', header_style), Paragraph('<b>Setting</b>', header_style), Paragraph('<b>Explanation</b>', header_style)],
    [Paragraph('TARGET', cell_center_style), Paragraph('Beat Top 10', cell_style), Paragraph('Set your goal high enough to challenge yourself', cell_style)],
    [Paragraph('EFFORT', cell_center_style), Paragraph('Maximum', cell_style), Paragraph('Give 100% effort in research, creation, iteration', cell_style)],
    [Paragraph('ACCEPT', cell_center_style), Paragraph('Any result', cell_style), Paragraph('Accept whatever outcome with grace', cell_style)],
]
mindset_table = Table(mindset_data, colWidths=[2.5*cm, 3*cm, 7.5*cm])
mindset_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#dd6b20')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(mindset_table)
story.append(Spacer(1, 12))

story.append(Paragraph("""
This framework separates what you control from what you do not. You control your target (aiming 
high) and your effort (working hard). You do not control the final result. By accepting any 
result, you free yourself from outcome attachment while still maintaining high standards.
""", body_style))

story.append(PageBreak())

# APPENDIX
story.append(Paragraph("APPENDIX: QUICK REFERENCE CARDS", h1_style))

story.append(Paragraph("A.1 Formula Quick Reference", h3_style))
story.append(Paragraph("<b>Gate Multiplier:</b> M<sub>gate</sub> = 1 + 0.5 × (g<sub>star</sub> - 1)", body_style))
story.append(Paragraph("<b>Campaign Points:</b> CP = M<sub>gate</sub> × Σ(W[i] × normalized_metrics[i])", body_style))
story.append(Paragraph("<b>Points Conversion:</b> atto_points ÷ 10<sup>18</sup> = display_score", body_style))
story.append(Spacer(1, 12))

story.append(Paragraph("A.2 G4 Checklist", h3_style))
story.append(Paragraph("[ ] Casual hook  [ ] Parenthetical aside  [ ] 3+ contractions", body_style))
story.append(Paragraph("[ ] Fragments    [ ] Personal angle       [ ] Conversational end", body_style))
story.append(Spacer(1, 12))

story.append(Paragraph("A.3 Kill List", h3_style))
quick_kill = [
    [Paragraph('<b>NEVER Use</b>', header_style), Paragraph('<b>Use Instead</b>', header_style)],
    [Paragraph('Em dashes, "In the world of"', cell_style), Paragraph('Hyphens, start mid-thought', cell_style)],
    [Paragraph('delve, realm, embark, revolutionize', cell_style), Paragraph('dig into, world, start, change', cell_style)],
    [Paragraph('Perfect grammar', cell_style), Paragraph('Natural, casual style', cell_style)],
]
quick_kill_table = Table(quick_kill, colWidths=[6*cm, 6*cm])
quick_kill_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#c53030')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(quick_kill_table)
story.append(Spacer(1, 12))

story.append(Paragraph("A.4 Iteration Checklist", h3_style))
story.append(Paragraph("[ ] Research + verify  [ ] Draft #1  [ ] Self-score  [ ] Compare to Top 10", body_style))
story.append(Paragraph("[ ] Identify gaps  [ ] Iterate  [ ] Repeat until target met  [ ] Submit", body_style))

# Build PDF
doc.build(story)
print(f"PDF generated: {output_path}")
