#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from reportlab.lib.pagesizes import A4
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, ListFlowable, ListItem
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.lib import colors
from reportlab.lib.units import cm, inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily
import os

# Register fonts
pdfmetrics.registerFont(TTFont('Times New Roman', '/usr/share/fonts/truetype/english/Times-New-Roman.ttf'))
pdfmetrics.registerFont(TTFont('SimHei', '/usr/share/fonts/truetype/chinese/SimHei.ttf'))

# Register font families for bold
registerFontFamily('Times New Roman', normal='Times New Roman', bold='Times New Roman')
registerFontFamily('SimHei', normal='SimHei', bold='SimHei')

# Create document
output_path = "/home/z/my-project/download/Rally_Ultimate_Master_Guide_V4.pdf"
doc = SimpleDocTemplate(
    output_path,
    pagesize=A4,
    rightMargin=2*cm,
    leftMargin=2*cm,
    topMargin=2*cm,
    bottomMargin=2*cm,
    title="Rally_Ultimate_Master_Guide_V4",
    author="Z.ai",
    creator="Z.ai",
    subject="Complete Rally.fun Content Optimization Guide V4"
)

# Styles
styles = getSampleStyleSheet()

# Custom styles
title_style = ParagraphStyle(
    'CustomTitle',
    parent=styles['Title'],
    fontName='Times New Roman',
    fontSize=28,
    leading=34,
    alignment=TA_CENTER,
    spaceAfter=20
)

subtitle_style = ParagraphStyle(
    'CustomSubtitle',
    parent=styles['Normal'],
    fontName='Times New Roman',
    fontSize=14,
    leading=18,
    alignment=TA_CENTER,
    spaceAfter=30
)

h1_style = ParagraphStyle(
    'CustomH1',
    parent=styles['Heading1'],
    fontName='Times New Roman',
    fontSize=18,
    leading=22,
    spaceBefore=20,
    spaceAfter=12,
    textColor=colors.HexColor('#1a365d')
)

h2_style = ParagraphStyle(
    'CustomH2',
    parent=styles['Heading2'],
    fontName='Times New Roman',
    fontSize=14,
    leading=18,
    spaceBefore=16,
    spaceAfter=8,
    textColor=colors.HexColor('#2c5282')
)

h3_style = ParagraphStyle(
    'CustomH3',
    parent=styles['Heading3'],
    fontName='Times New Roman',
    fontSize=12,
    leading=15,
    spaceBefore=12,
    spaceAfter=6,
    textColor=colors.HexColor('#2d3748')
)

body_style = ParagraphStyle(
    'CustomBody',
    parent=styles['Normal'],
    fontName='Times New Roman',
    fontSize=10.5,
    leading=16,
    alignment=TA_JUSTIFY,
    spaceAfter=8
)

body_left_style = ParagraphStyle(
    'CustomBodyLeft',
    parent=styles['Normal'],
    fontName='Times New Roman',
    fontSize=10.5,
    leading=16,
    alignment=TA_LEFT,
    spaceAfter=8
)

bullet_style = ParagraphStyle(
    'CustomBullet',
    parent=styles['Normal'],
    fontName='Times New Roman',
    fontSize=10,
    leading=14,
    leftIndent=20,
    spaceAfter=4
)

code_style = ParagraphStyle(
    'CustomCode',
    parent=styles['Normal'],
    fontName='Times New Roman',
    fontSize=9,
    leading=12,
    backColor=colors.HexColor('#f7fafc'),
    borderColor=colors.HexColor('#e2e8f0'),
    borderWidth=1,
    borderPadding=8,
    leftIndent=10,
    rightIndent=10,
    spaceAfter=8
)

# Table styles
header_style = ParagraphStyle(
    'TableHeader',
    fontName='Times New Roman',
    fontSize=10,
    textColor=colors.white,
    alignment=TA_CENTER
)

cell_style = ParagraphStyle(
    'TableCell',
    fontName='Times New Roman',
    fontSize=9,
    alignment=TA_LEFT
)

cell_center_style = ParagraphStyle(
    'TableCellCenter',
    fontName='Times New Roman',
    fontSize=9,
    alignment=TA_CENTER
)

# Build content
story = []

# Cover Page
story.append(Spacer(1, 100))
story.append(Paragraph("RALLY ULTIMATE MASTER GUIDE", title_style))
story.append(Paragraph("V4 - Complete Content Optimization System", subtitle_style))
story.append(Spacer(1, 20))
story.append(Paragraph("Including: Anti-Formulaic Content + Iterative Process Workflow", subtitle_style))
story.append(Spacer(1, 40))
story.append(Paragraph("Complete Rally.fun API Documentation", body_style))
story.append(Paragraph("Scoring System Deep Dive", body_style))
story.append(Paragraph("G4 Originality Checklist", body_style))
story.append(Paragraph("Information Verification Protocol", body_style))
story.append(Paragraph("Anti-Formulaic Content Guide (NEW)", body_style))
story.append(Paragraph("Iterative Process Workflow (NEW)", body_style))
story.append(Spacer(1, 40))
story.append(Paragraph("Version 4.0 - Elite Edition", body_style))
story.append(Paragraph("Generated by Z.ai", body_style))

story.append(PageBreak())

# Table of Contents
story.append(Paragraph("TABLE OF CONTENTS", h1_style))
story.append(Spacer(1, 10))

toc_items = [
    ("PART 1: RALLY SCORING SYSTEM", "11 Metrics Deep Dive"),
    ("PART 2: GATE OPTIMIZATION", "G4 Originality Checklist"),
    ("PART 3: INFORMATION VERIFICATION", "Pre-Submission Protocol"),
    ("PART 4: ANTI-FORMULAIC CONTENT", "Avoiding Template Patterns (NEW)"),
    ("PART 5: ITERATIVE PROCESS WORKFLOW", "Submit-Score-Improve Loop (NEW)"),
    ("PART 6: CORRECT MINDSET", "Beat Top 10 Framework"),
    ("APPENDIX: Quick Reference Cards", "Checklists & Formulas"),
]

for part, desc in toc_items:
    story.append(Paragraph(f"<b>{part}</b> - {desc}", body_style))
    story.append(Spacer(1, 4))

story.append(PageBreak())

# PART 1: SCORING SYSTEM
story.append(Paragraph("PART 1: RALLY SCORING SYSTEM", h1_style))
story.append(Paragraph("Complete 11 Metrics Deep Dive", h2_style))

story.append(Paragraph("""
The Rally scoring system uses AI-powered evaluation to ensure fair and transparent reward distribution 
based on content quality and engagement. Understanding this system is critical for maximizing your 
Campaign Points and rewards. The system evaluates content across three distinct categories, each with 
specific metrics that contribute to your final score.
""", body_style))

story.append(Paragraph("1.1 The Three Categories", h3_style))

# Categories table
cat_data = [
    [Paragraph('<b>Category</b>', header_style), Paragraph('<b>Metrics</b>', header_style), Paragraph('<b>Score Range</b>', header_style), Paragraph('<b>Impact</b>', header_style)],
    [Paragraph('Gates (4)', cell_style), Paragraph('Alignment, Accuracy, Compliance, Originality', cell_style), Paragraph('0-2 each', cell_center_style), Paragraph('Pass/Fail + Multiplier', cell_style)],
    [Paragraph('Quality (2)', cell_style), Paragraph('Engagement Potential, Technical Quality', cell_style), Paragraph('0-5 each', cell_center_style), Paragraph('Linear contribution', cell_style)],
    [Paragraph('Engagement (5)', cell_style), Paragraph('RT, Likes, Replies, QR, FR', cell_style), Paragraph('Dynamic', cell_center_style), Paragraph('Log-scaled', cell_style)],
]

cat_table = Table(cat_data, colWidths=[2.5*cm, 6*cm, 2.5*cm, 3.5*cm])
cat_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('BACKGROUND', (0, 1), (-1, 1), colors.white),
    ('BACKGROUND', (0, 2), (-1, 2), colors.HexColor('#F5F5F5')),
    ('BACKGROUND', (0, 3), (-1, 3), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(cat_table)
story.append(Spacer(1, 16))

story.append(Paragraph("1.2 Gate Multiplier Formula", h3_style))

story.append(Paragraph("""
The Gate Multiplier is the MOST IMPACTFUL factor in your final score. A perfect gate score (all 2.0) 
gives you a 1.5x multiplier, while any failed gate (score 0) disqualifies your submission entirely. 
This makes gate optimization critical before any other consideration.
""", body_style))

story.append(Paragraph("<b>Formula:</b> M<sub>gate</sub> = 1 + 0.5 × (g<sub>star</sub> - 1)", body_style))
story.append(Paragraph("Where g<sub>star</sub> = average of all 4 gate scores", body_style))
story.append(Spacer(1, 8))

# Gate multiplier table
gate_data = [
    [Paragraph('<b>Gate Scores</b>', header_style), Paragraph('<b>g_star</b>', header_style), Paragraph('<b>M_gate</b>', header_style), Paragraph('<b>vs Baseline</b>', header_style)],
    [Paragraph('2, 2, 2, 2', cell_center_style), Paragraph('2.0', cell_center_style), Paragraph('1.5x', cell_center_style), Paragraph('+50% (ELITE)', cell_center_style)],
    [Paragraph('2, 2, 2, 1', cell_center_style), Paragraph('1.75', cell_center_style), Paragraph('1.375x', cell_center_style), Paragraph('+37.5%', cell_center_style)],
    [Paragraph('2, 2, 1, 1', cell_center_style), Paragraph('1.5', cell_center_style), Paragraph('1.25x', cell_center_style), Paragraph('+25%', cell_center_style)],
    [Paragraph('1, 1, 1, 1', cell_center_style), Paragraph('1.0', cell_center_style), Paragraph('1.0x', cell_center_style), Paragraph('Baseline', cell_center_style)],
    [Paragraph('Any = 0', cell_center_style), Paragraph('-', cell_center_style), Paragraph('0.5x', cell_center_style), Paragraph('-50% (FAIL)', cell_center_style)],
]

gate_table = Table(gate_data, colWidths=[3*cm, 2.5*cm, 2.5*cm, 4*cm])
gate_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('BACKGROUND', (0, 1), (-1, 1), colors.HexColor('#c6f6d5')),
    ('BACKGROUND', (0, 2), (-1, 2), colors.white),
    ('BACKGROUND', (0, 3), (-1, 3), colors.HexColor('#F5F5F5')),
    ('BACKGROUND', (0, 4), (-1, 4), colors.white),
    ('BACKGROUND', (0, 5), (-1, 5), colors.HexColor('#fed7d7')),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(gate_table)
story.append(Spacer(1, 16))

story.append(Paragraph("1.3 Final Score Calculation", h3_style))

story.append(Paragraph("""
Your final Campaign Points are calculated by combining the Gate Multiplier with your Quality and 
Engagement scores. The formula creates a weighted sum that rewards both content quality and real 
audience interaction, while the gate multiplier can significantly amplify or penalize your results.
""", body_style))

story.append(Paragraph("<b>Complete Formula:</b>", body_style))
story.append(Paragraph("Campaign_Points = M<sub>gate</sub> × Σ(W[i] × normalized_metrics[i])", body_style))
story.append(Spacer(1, 8))

story.append(Paragraph("""
Where W is the vector of metric weights (0-1 for each of the 11 metrics), and normalized metrics 
include EP, TQ, log(RT+1), log(Likes+1), log(Replies+1), QR, and log(FR+1). Higher weights increase 
the impact of specific metrics on your final score.
""", body_style))

story.append(PageBreak())

# PART 2: GATE OPTIMIZATION
story.append(Paragraph("PART 2: GATE OPTIMIZATION", h1_style))
story.append(Paragraph("G4 Originality Checklist for Score 2.0", h2_style))

story.append(Paragraph("""
Gate 4 (Originality and Authenticity) is the #1 differentiator between top performers and average 
participants. Most AI-generated content fails here because it lacks the human voice that Rally's 
AI evaluators are trained to detect. This checklist provides the specific elements you need to 
include to achieve a perfect 2.0 score on this critical gate.
""", body_style))

story.append(Paragraph("2.1 G4 Checklist Elements", h3_style))

# G4 Checklist table
g4_data = [
    [Paragraph('<b>Element</b>', header_style), Paragraph('<b>What It Means</b>', header_style), Paragraph('<b>Example</b>', header_style)],
    [Paragraph('Casual Hook', cell_style), Paragraph('Start with conversational, not formal', cell_style), Paragraph('"Hot take:" or "Here\'s the thing"', cell_style)],
    [Paragraph('Parenthetical Aside', cell_style), Paragraph('Break flow with side comment', cell_style), Paragraph('"(finally)" or "(tbh)"', cell_style)],
    [Paragraph('3+ Contractions', cell_style), Paragraph('Use natural contractions', cell_style), Paragraph("don't, can't, won't, isn't", cell_style)],
    [Paragraph('Fragments', cell_style), Paragraph('Short, punchy sentences', cell_style), Paragraph('"Big difference." "Until now."', cell_style)],
    [Paragraph('Personal Angle', cell_style), Paragraph('Add your perspective', cell_style), Paragraph('"Been following this for years"', cell_style)],
    [Paragraph('Conversational End', cell_style), Paragraph('End with open discussion', cell_style), Paragraph('"Place your bets."', cell_style)],
]

g4_table = Table(g4_data, colWidths=[3*cm, 5*cm, 5*cm])
g4_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('BACKGROUND', (0, 1), (-1, -1), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F5F5F5')]),
]))
story.append(g4_table)
story.append(Spacer(1, 16))

story.append(Paragraph("2.2 AI Detection Kill List", h3_style))

story.append(Paragraph("""
Certain patterns instantly flag content as AI-generated. These elements appear frequently in 
machine-written text and should be avoided at all costs. Replacing them with human alternatives 
significantly improves your authenticity score.
""", body_style))

# Kill list table
kill_data = [
    [Paragraph('<b>NEVER Use</b>', header_style), Paragraph('<b>Why AI Uses It</b>', header_style), Paragraph('<b>Human Alternative</b>', header_style)],
    [Paragraph('Em dashes (—)', cell_style), Paragraph('Formal punctuation preference', cell_style), Paragraph('Regular hyphens (-) or commas', cell_style)],
    [Paragraph('"In the world of..."', cell_style), Paragraph('Generic opening template', cell_style), Paragraph('Start mid-thought or with hook', cell_style)],
    [Paragraph('delve, uncover, embark', cell_style), Paragraph('Academic vocabulary training', cell_style), Paragraph('dig into, find out, start', cell_style)],
    [Paragraph('revolutionize, transform', cell_style), Paragraph('Corporate speak training', cell_style), Paragraph('change, shake up, new way', cell_style)],
    [Paragraph('Perfect grammar', cell_style), Paragraph('Grammar rule enforcement', cell_style), Paragraph('Natural, casual style', cell_style)],
    [Paragraph('Long explanations', cell_style), Paragraph('Comprehensive coverage bias', cell_style), Paragraph('Trust reader to understand', cell_style)],
]

kill_table = Table(kill_data, colWidths=[4*cm, 4.5*cm, 4.5*cm])
kill_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#c53030')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('BACKGROUND', (0, 1), (-1, -1), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#fff5f5')]),
]))
story.append(kill_table)
story.append(Spacer(1, 16))

story.append(PageBreak())

# PART 3: INFORMATION VERIFICATION
story.append(Paragraph("PART 3: INFORMATION VERIFICATION PROTOCOL", h1_style))
story.append(Paragraph("Pre-Submission Verification Steps", h2_style))

story.append(Paragraph("""
Before creating any Rally content, you MUST verify all factual claims. Fabricating or assuming 
information will result in penalties on the Information Accuracy gate. This protocol ensures every 
claim in your content is backed by verified sources and accurate data.
""", body_style))

story.append(Paragraph("3.1 Verification Checklist", h3_style))

verify_data = [
    [Paragraph('<b>Step</b>', header_style), Paragraph('<b>Action</b>', header_style), Paragraph('<b>Source Type</b>', header_style)],
    [Paragraph('1', cell_center_style), Paragraph('Identify all factual claims in your content', cell_style), Paragraph('Self-review', cell_style)],
    [Paragraph('2', cell_center_style), Paragraph('Search for official documentation', cell_style), Paragraph('Project docs, whitepapers', cell_style)],
    [Paragraph('3', cell_center_style), Paragraph('Cross-reference with multiple sources', cell_style), Paragraph('News, blogs, official accounts', cell_style)],
    [Paragraph('4', cell_center_style), Paragraph('Verify numbers, dates, names precisely', cell_style), Paragraph('Primary sources', cell_style)],
    [Paragraph('5', cell_center_style), Paragraph('Remove or flag unverified claims', cell_style), Paragraph('Self-review', cell_style)],
]

verify_table = Table(verify_data, colWidths=[1.5*cm, 6*cm, 5.5*cm])
verify_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('BACKGROUND', (0, 1), (-1, -1), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('ALIGN', (0, 1), (0, -1), 'CENTER'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F5F5F5')]),
]))
story.append(verify_table)
story.append(Spacer(1, 16))

story.append(Paragraph("3.2 Common Verification Mistakes", h3_style))

story.append(Paragraph("""
Many content creators make verification errors that cost them points on the Information Accuracy 
gate. Understanding these common mistakes helps you avoid them and maintain high accuracy scores 
across all your submissions.
""", body_style))

story.append(Paragraph("- <b>Assuming without checking:</b> Never assume facts about a project, even if they seem obvious", body_left_style))
story.append(Paragraph("- <b>Using outdated information:</b> Always check the date of your sources", body_left_style))
story.append(Paragraph("- <b>Misquoting numbers:</b> Double-check all statistics and metrics", body_left_style))
story.append(Paragraph("- <b>Confusing similar projects:</b> Ensure you are referencing the correct project", body_left_style))
story.append(Paragraph("- <b>Overclaiming partnerships:</b> Verify official partnership announcements", body_left_style))

story.append(PageBreak())

# PART 4: ANTI-FORMULAIC CONTENT (NEW)
story.append(Paragraph("PART 4: ANTI-FORMULAIC CONTENT GUIDE", h1_style))
story.append(Paragraph("Why Your Content Feels 'Same' and How to Fix It", h2_style))

story.append(Paragraph("""
One of the biggest problems with systematic content creation is that all outputs start to feel 
identical. This section addresses why content becomes formulaic and provides concrete strategies 
for creating fresh, varied, and authentic content that stands out from the crowd.
""", body_style))

story.append(Paragraph("4.1 The Formulaic Trap", h3_style))

story.append(Paragraph("""
When following a checklist like G4, it is easy to fall into a pattern where every piece of content 
has the same structure, voice, and rhythm. The AI evaluators and human readers can both detect 
this template-like quality, which hurts your Originality score even if all checklist elements are 
technically present.
""", body_style))

# Formulaic problems table
formulaic_data = [
    [Paragraph('<b>Problem</b>', header_style), Paragraph('<b>Why It Happens</b>', header_style), Paragraph('<b>Solution</b>', header_style)],
    [Paragraph('Same hook style', cell_style), Paragraph('Default to one approach', cell_style), Paragraph('Vary: story, data, controversy, paradox, quote', cell_style)],
    [Paragraph('Identical voice', cell_style), Paragraph('Over-optimization for tone', cell_style), Paragraph('Adapt voice to TOPIC, not just checklist', cell_style)],
    [Paragraph('Predictable angle', cell_style), Paragraph('Same perspective each time', cell_style), Paragraph('Try: critic, enthusiast, skeptic, newcomer', cell_style)],
    [Paragraph('Template structure', cell_style), Paragraph('Following formula rigidly', cell_style), Paragraph('Break patterns: start mid-thought, use dialogue', cell_style)],
]

formulaic_table = Table(formulaic_data, colWidths=[3*cm, 4*cm, 6*cm])
formulaic_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#805ad5')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('BACKGROUND', (0, 1), (-1, -1), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#faf5ff')]),
]))
story.append(formulaic_table)
story.append(Spacer(1, 16))

story.append(Paragraph("4.2 Hook Type Variety", h3_style))

story.append(Paragraph("""
The hook is the first thing readers see, and using the same hook style repeatedly signals 
formulaic content. Rotate between these different hook types to keep your content fresh and 
unpredictable while still meeting checklist requirements.
""", body_style))

# Hook types table
hook_data = [
    [Paragraph('<b>Hook Type</b>', header_style), Paragraph('<b>Example</b>', header_style), Paragraph('<b>Best For</b>', header_style)],
    [Paragraph('Story', cell_style), Paragraph('"Three banks walked into Ethereum..."', cell_style), Paragraph('Complex topics, relatable content', cell_style)],
    [Paragraph('Data', cell_style), Paragraph('"Bank settlement: SWIFT 2-5 days, Ethereum 12 sec"', cell_style), Paragraph('Technical comparison, proof points', cell_style)],
    [Paragraph('Controversy', cell_style), Paragraph('"Hot take: Banks are never moving to public chains"', cell_style), Paragraph('Engagement, debate starter', cell_style)],
    [Paragraph('Paradox', cell_style), Paragraph('"Pick zero. Pick one. Can\'t have both."', cell_style), Paragraph('Problem-solution framing', cell_style)],
    [Paragraph('Quote/Question', cell_style), Paragraph('"What if both?" or "Why hasn\'t this happened?"', cell_style), Paragraph('Thought-provoking pieces', cell_style)],
]

hook_table = Table(hook_data, colWidths=[2.5*cm, 5.5*cm, 5*cm])
hook_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('BACKGROUND', (0, 1), (-1, -1), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F5F5F5')]),
]))
story.append(hook_table)
story.append(Spacer(1, 16))

story.append(Paragraph("4.3 Voice Adaptation Strategy", h3_style))

story.append(Paragraph("""
Instead of forcing the same voice onto every topic, let the subject matter guide your tone. 
A technical infrastructure piece should sound different from a market analysis or an opinion 
piece. This natural adaptation signals authenticity to both AI evaluators and human readers.
""", body_style))

story.append(Paragraph("<b>Voice Guidelines by Topic Type:</b>", body_style))
story.append(Paragraph("- <b>Technical infrastructure:</b> Analytical, precise, slightly formal but conversational", body_left_style))
story.append(Paragraph("- <b>Market analysis:</b> Opinionated, data-driven, confident", body_left_style))
story.append(Paragraph("- <b>Project announcement:</b> Enthusiastic, informative, clear", body_left_style))
story.append(Paragraph("- <b>Problem-solution:</b> Conversational, relatable, practical", body_left_style))
story.append(Paragraph("- <b>Controversial take:</b> Bold, direct, invite debate", body_left_style))

story.append(PageBreak())

# PART 5: ITERATIVE PROCESS WORKFLOW
story.append(Paragraph("PART 5: ITERATIVE PROCESS WORKFLOW", h1_style))
story.append(Paragraph("Submit-Score-Improve Loop for Maximum Results", h2_style))

story.append(Paragraph("""
The most successful Rally participants do not submit their first draft. They iterate through 
multiple versions, scoring each against the 11 metrics, comparing to leaderboard targets, and 
improving until the content has the highest probability of success. This section outlines the 
complete iterative process.
""", body_style))

story.append(Paragraph("5.1 The Iteration Framework", h3_style))

# Iteration steps
iter_data = [
    [Paragraph('<b>Step</b>', header_style), Paragraph('<b>Action</b>', header_style), Paragraph('<b>Output</b>', header_style)],
    [Paragraph('1', cell_center_style), Paragraph('Research campaign + verify facts', cell_style), Paragraph('Verified fact sheet', cell_style)],
    [Paragraph('2', cell_center_style), Paragraph('Create Draft #1', cell_style), Paragraph('Initial content', cell_style)],
    [Paragraph('3', cell_center_style), Paragraph('Self-score with 11 metrics + G4', cell_style), Paragraph('Score breakdown', cell_style)],
    [Paragraph('4', cell_center_style), Paragraph('Compare to Top 10 target', cell_style), Paragraph('Gap analysis', cell_style)],
    [Paragraph('5', cell_center_style), Paragraph('If gap exists, identify improvements', cell_style), Paragraph('Improvement list', cell_style)],
    [Paragraph('6', cell_center_style), Paragraph('Create Draft #2 with improvements', cell_style), Paragraph('Revised content', cell_style)],
    [Paragraph('7', cell_center_style), Paragraph('Repeat steps 3-6 until target reached', cell_style), Paragraph('Final content', cell_style)],
    [Paragraph('8', cell_center_style), Paragraph('Submit with confidence', cell_style), Paragraph('Submission', cell_style)],
]

iter_table = Table(iter_data, colWidths=[1.5*cm, 6*cm, 5.5*cm])
iter_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2f855a')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('BACKGROUND', (0, 1), (-1, -1), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('ALIGN', (0, 1), (0, -1), 'CENTER'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f0fff4')]),
]))
story.append(iter_table)
story.append(Spacer(1, 16))

story.append(Paragraph("5.2 Self-Scoring Template", h3_style))

story.append(Paragraph("""
Use this template to score your own content before submission. Be honest and critical - 
overestimating your score leads to disappointing results. Compare against the leaderboard 
target for your campaign.
""", body_style))

# Self-scoring template
score_data = [
    [Paragraph('<b>Metric</b>', header_style), Paragraph('<b>Range</b>', header_style), Paragraph('<b>Your Score</b>', header_style), Paragraph('<b>Notes</b>', header_style)],
    [Paragraph('G1: Content Alignment', cell_style), Paragraph('0-2', cell_center_style), Paragraph('___', cell_center_style), Paragraph('', cell_style)],
    [Paragraph('G2: Information Accuracy', cell_style), Paragraph('0-2', cell_center_style), Paragraph('___', cell_center_style), Paragraph('', cell_style)],
    [Paragraph('G3: Campaign Compliance', cell_style), Paragraph('0-2', cell_center_style), Paragraph('___', cell_center_style), Paragraph('', cell_style)],
    [Paragraph('G4: Originality', cell_style), Paragraph('0-2', cell_center_style), Paragraph('___', cell_center_style), Paragraph('', cell_style)],
    [Paragraph('EP: Engagement Potential', cell_style), Paragraph('0-5', cell_center_style), Paragraph('___', cell_center_style), Paragraph('', cell_style)],
    [Paragraph('TQ: Technical Quality', cell_style), Paragraph('0-5', cell_center_style), Paragraph('___', cell_center_style), Paragraph('', cell_style)],
    [Paragraph('g_star (avg gates)', cell_style), Paragraph('0-2', cell_center_style), Paragraph('___', cell_center_style), Paragraph('', cell_style)],
    [Paragraph('M_gate', cell_style), Paragraph('0.5-1.5', cell_center_style), Paragraph('___', cell_center_style), Paragraph('', cell_style)],
]

score_table = Table(score_data, colWidths=[4*cm, 2*cm, 2.5*cm, 4.5*cm])
score_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('BACKGROUND', (0, 1), (-1, -1), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F5F5F5')]),
]))
story.append(score_table)
story.append(Spacer(1, 16))

story.append(Paragraph("5.3 Real Iteration Example", h3_style))

story.append(Paragraph("""
Below is an example from an actual campaign showing how scores improved through iteration. 
Notice how each iteration addressed specific weaknesses identified in the self-scoring process, 
leading to a final draft that beat the Top 10 target.
""", body_style))

# Real iteration example
example_data = [
    [Paragraph('<b>Draft</b>', header_style), Paragraph('<b>Est. Score</b>', header_style), Paragraph('<b>Status</b>', header_style), Paragraph('<b>Key Improvement</b>', header_style)],
    [Paragraph('#1', cell_center_style), Paragraph('~10.0', cell_center_style), Paragraph('FAIL', cell_center_style), Paragraph('Too formal, template-like', cell_style)],
    [Paragraph('#2', cell_center_style), Paragraph('~14.3', cell_center_style), Paragraph('CLOSE', cell_center_style), Paragraph('Added storytelling, personality', cell_style)],
    [Paragraph('#3', cell_center_style), Paragraph('~16.1', cell_center_style), Paragraph('VERY CLOSE', cell_center_style), Paragraph('Added controversy angle', cell_style)],
    [Paragraph('#4', cell_center_style), Paragraph('~18.0', cell_center_style), Paragraph('SUCCESS', cell_center_style), Paragraph('Thread format + data hook', cell_style)],
]

example_table = Table(example_data, colWidths=[1.5*cm, 2.5*cm, 2.5*cm, 6.5*cm])
example_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('BACKGROUND', (0, 1), (-1, 1), colors.HexColor('#fed7d7')),
    ('BACKGROUND', (0, 2), (-1, 2), colors.HexColor('#feebc8')),
    ('BACKGROUND', (0, 3), (-1, 3), colors.HexColor('#fefcbf')),
    ('BACKGROUND', (0, 4), (-1, 4), colors.HexColor('#c6f6d5')),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(example_table)

story.append(PageBreak())

# PART 6: CORRECT MINDSET
story.append(Paragraph("PART 6: CORRECT MINDSET FRAMEWORK", h1_style))
story.append(Paragraph("Beat Top 10 with Healthy Expectations", h2_style))

story.append(Paragraph("""
Your mindset going into Rally significantly impacts your results. The wrong mindset leads to 
frustration and suboptimal content. The right mindset keeps you motivated and focused on 
continuous improvement, regardless of outcomes.
""", body_style))

story.append(Paragraph("6.1 The Framework", h3_style))

# Mindset framework
mindset_data = [
    [Paragraph('<b>Component</b>', header_style), Paragraph('<b>Setting</b>', header_style), Paragraph('<b>Explanation</b>', header_style)],
    [Paragraph('TARGET', cell_center_style), Paragraph('Beat Top 10', cell_style), Paragraph('Set your goal high enough to challenge yourself', cell_style)],
    [Paragraph('EFFORT', cell_center_style), Paragraph('Maximum', cell_style), Paragraph('Give 100% effort in research, creation, iteration', cell_style)],
    [Paragraph('ACCEPT', cell_center_style), Paragraph('Any result', cell_style), Paragraph('Accept whatever outcome with grace', cell_style)],
]

mindset_table = Table(mindset_data, colWidths=[2.5*cm, 3*cm, 7.5*cm])
mindset_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#dd6b20')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('BACKGROUND', (0, 1), (-1, -1), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#fffaf0')]),
]))
story.append(mindset_table)
story.append(Spacer(1, 16))

story.append(Paragraph("6.2 Why This Mindset Works", h3_style))

story.append(Paragraph("""
This framework separates what you control from what you do not. You control your target (aiming 
high), your effort (working hard). You do not control the final result (AI scoring, competitor 
performance, engagement metrics). By accepting any result, you free yourself from outcome 
attachment while still maintaining high standards.
""", body_style))

story.append(Paragraph("""
The key insight is that success on Rally comes from consistent application of the process, not 
from any single submission. Some campaigns will have stronger competition. Some topics will 
naturally attract more engagement. Your job is to maximize your probability of success through 
thorough research, quality content, and iterative improvement.
""", body_style))

story.append(Paragraph("6.3 Common Mindset Mistakes", h3_style))

story.append(Paragraph("- <b>Attaching to outcomes:</b> Getting upset when you do not beat Top 10", body_left_style))
story.append(Paragraph("- <b>Skipping iteration:</b> Submitting first draft without improvement", body_left_style))
story.append(Paragraph("- <b>Blaming the system:</b> Claiming AI scoring is unfair instead of improving", body_left_style))
story.append(Paragraph("- <b>Setting low targets:</b> Aiming for participation instead of excellence", body_left_style))
story.append(Paragraph("- <b>Giving up:</b> Stopping after one unsuccessful campaign", body_left_style))

story.append(PageBreak())

# APPENDIX
story.append(Paragraph("APPENDIX: QUICK REFERENCE CARDS", h1_style))

story.append(Paragraph("A.1 Formula Quick Reference", h3_style))

story.append(Paragraph("<b>Gate Multiplier:</b> M<sub>gate</sub> = 1 + 0.5 × (g<sub>star</sub> - 1)", body_style))
story.append(Paragraph("<b>Campaign Points:</b> CP = M<sub>gate</sub> × Σ(W[i] × normalized_metrics[i])", body_style))
story.append(Paragraph("<b>Log Scaling:</b> score = log(metric + 1)", body_style))
story.append(Paragraph("<b>Points Conversion:</b> atto_points ÷ 10<sup>18</sup> = display_score", body_style))
story.append(Spacer(1, 12))

story.append(Paragraph("A.2 G4 Checklist Quick Reference", h3_style))

story.append(Paragraph("[ ] Casual/conversational hook", body_left_style))
story.append(Paragraph("[ ] Parenthetical aside", body_left_style))
story.append(Paragraph("[ ] 3+ contractions", body_left_style))
story.append(Paragraph("[ ] Sentence fragments", body_left_style))
story.append(Paragraph("[ ] Personal angle", body_left_style))
story.append(Paragraph("[ ] Conversational ending", body_left_style))
story.append(Spacer(1, 12))

story.append(Paragraph("A.3 Kill List Quick Reference", h3_style))

# Quick kill list
quick_kill = [
    [Paragraph('<b>NEVER Use</b>', header_style), Paragraph('<b>Use Instead</b>', header_style)],
    [Paragraph('Em dashes', cell_style), Paragraph('Regular hyphens (-)', cell_style)],
    [Paragraph('Smart quotes', cell_style), Paragraph('Straight quotes', cell_style)],
    [Paragraph('"In the world of..."', cell_style), Paragraph('Start mid-thought', cell_style)],
    [Paragraph('delve, realm, embark', cell_style), Paragraph('dig into, world, start', cell_style)],
    [Paragraph('revolutionize, transform', cell_style), Paragraph('change, shake up', cell_style)],
    [Paragraph('Perfect grammar', cell_style), Paragraph('Natural, casual style', cell_style)],
]

quick_kill_table = Table(quick_kill, colWidths=[6*cm, 6*cm])
quick_kill_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#c53030')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('BACKGROUND', (0, 1), (-1, -1), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#fff5f5')]),
]))
story.append(quick_kill_table)
story.append(Spacer(1, 16))

story.append(Paragraph("A.4 Iteration Checklist", h3_style))

story.append(Paragraph("[ ] Research completed + facts verified", body_left_style))
story.append(Paragraph("[ ] Draft #1 created", body_left_style))
story.append(Paragraph("[ ] Self-scored with 11 metrics", body_left_style))
story.append(Paragraph("[ ] Compared to Top 10 target", body_left_style))
story.append(Paragraph("[ ] Gap identified + improvements made", body_left_style))
story.append(Paragraph("[ ] Draft #2 created (repeat if needed)", body_left_style))
story.append(Paragraph("[ ] Final score exceeds target", body_left_style))
story.append(Paragraph("[ ] Submitted with confidence", body_left_style))

# Build PDF
doc.build(story)
print(f"PDF generated: {output_path}")
