import ZAI from 'z-ai-web-dev-sdk';

const CAMPAIGN_BRIEF = {
  description: `Prediction markets had their moment. Argumentation markets are next, and argue.fun is already live on Base while most people haven't noticed.

Post on X about argue.fun in a way that makes your audience feel like they're missing something. The best posts will make people feel behind, not informed.`,
  
  rules: [
    "You must mention @arguedotfun",
    "You must reference argue.fun or $ARGUE",
    "Your post MUST create a sense of urgency or FOMO",
    "Posts that read as neutral descriptions will be penalized",
    "DO NOT write a thread. Single short post only",
    "If your post reads like it was generated by an LLM, it will be penalized"
  ],
  
  knowledgeBase: `argue.fun is the first argumentation market, live on Base. AI agents and humans can create debates on any topic, take a side, stake on their position, and argue it out. Community judges vote on the winner. Winners earn real rewards.

Argumentation markets vs prediction markets: Prediction markets tell you what people believe. Argumentation markets tell you WHY people believe what they believe.`
};

const NEW_CONTENTS = [
  {
    id: 1,
    content: `prediction markets told you the odds. argue.fun tells you the reasoning.

watched agents debate for stakes on Base while the timeline scrolled past. that's the signal.

@arguedotfun is live. $ARGUE is moving. if you're waiting for permission you're already late.

argue.fun`
  },
  {
    id: 2,
    content: `ai agents trade billions but never explain why. that breaks today.

@arguedotfun is live on Base and the agents are already debating.

if you're still waiting for a thread to explain it you're the liquidity.

$ARGUE
argue.fun`
  },
  {
    id: 3,
    content: `missed the prediction market wave because i waited for clarity.

not making that mistake twice.

argumentation markets are here and @arguedotfun is the only one live on Base.

you're either early or you're liquidity.

argue.fun
$ARGUE`
  },
  {
    id: 4,
    content: `most people think this is still a concept. it's not.

debates are happening right now with real stakes.

@arguedotfun removed the friction for agents and nobody noticed.

that's how you get priced out.

$ARGUE
argue.fun`
  },
  {
    id: 5,
    content: `we built oracles for prices. we built markets for beliefs.

nobody built anything for logic until now.

@arguedotfun is live. agents are arguing. judges are voting.

if you're not looking you're already behind.

$ARGUE
argue.fun`
  }
];

const VALIDATOR_PROMPT = `You are a STRICT and OBJECTIVE evaluator for Rally.fun content scoring system. Evaluate content based on the Rally Scoring System.

## SCORING SYSTEM

### GATES (4 metrics, scored 0-2 each) - MUST ALL PASS
1. **Content Alignment (G1)**: How well does content align with campaign message?
   - 0 = Fail: No alignment
   - 1 = Pass: Basic alignment
   - 2 = Excellent: Perfect alignment with campaign essence

2. **Information Accuracy (G2)**: Factual correctness
   - 0 = Fail: False information
   - 1 = Pass: Accurate basic info
   - 2 = Excellent: Accurate with proper context

3. **Campaign Compliance (G3)**: Adherence to rules (mention @arguedotfun, $ARGUE, FOMO)
   - 0 = Fail: Missing required elements
   - 1 = Pass: Meets basic requirements
   - 2 = Excellent: Perfect execution

4. **Originality & Authenticity (G4)**: Human voice, not AI-generated
   - 0 = Fail: Generic AI patterns
   - 1 = Pass: Some originality
   - 2 = Excellent: Feels HUMAN-written, authentic

### QUALITY METRICS (0-5 each)
5. **Engagement Potential (EP)**: Hook effectiveness, FOMO creation
6. **Technical Quality (TQ)**: Writing quality, formatting

## AI DETECTION KILL LIST (penalize)
- Em dashes, smart quotes
- AI phrases: "delve into", "revolutionize", "realm", "transform"
- Over-explaining, perfect grammar

## OUTPUT - Return ONLY valid JSON:
{
  "gates": {"content_alignment": 0-2, "information_accuracy": 0-2, "campaign_compliance": 0-2, "originality_authenticity": 0-2, "gate_pass": true/false},
  "quality": {"engagement_potential": 0-5, "technical_quality": 0-5},
  "gate_multiplier": 0.5-1.5,
  "total_score": 0-10,
  "disqualified": true/false,
  "strengths": ["list 2-4 items"],
  "weaknesses": ["list 1-3 items"],
  "recommendations": ["list 1-3 items"]
}`;

async function evaluateContent(zai: any, content: string, contentId: number, validatorId: number) {
  const userPrompt = `## CAMPAIGN BRIEF
**Description:** ${CAMPAIGN_BRIEF.description}
**Rules:** ${CAMPAIGN_BRIEF.rules.join('\n')}
**Knowledge:** ${CAMPAIGN_BRIEF.knowledgeBase}

---

## CONTENT TO EVALUATE (Content #${contentId}, Validator #${validatorId})
"""
${content}
"""

Evaluate STRICTLY. Return JSON only.`;

  const completion = await zai.chat.completions.create({
    messages: [
      { role: 'assistant', content: VALIDATOR_PROMPT },
      { role: 'user', content: userPrompt }
    ],
    thinking: { type: 'disabled' }
  });

  const responseText = completion.choices[0]?.message?.content || '';
  
  try {
    let jsonStr = responseText;
    const jsonMatch = responseText.match(/```json\s*([\s\S]*?)\s*```/);
    if (jsonMatch) jsonStr = jsonMatch[1];
    else {
      const rawMatch = responseText.match(/\{[\s\S]*\}/);
      if (rawMatch) jsonStr = rawMatch[0];
    }
    return JSON.parse(jsonStr);
  } catch (e) {
    console.error(`Parse error for content ${contentId}, validator ${validatorId}`);
    return {
      gates: { content_alignment: 0, information_accuracy: 0, campaign_compliance: 0, originality_authenticity: 0, gate_pass: false },
      quality: { engagement_potential: 0, technical_quality: 0 },
      gate_multiplier: 0.5,
      total_score: 0,
      disqualified: true,
      strengths: [],
      weaknesses: ["Evaluation parsing failed"],
      recommendations: []
    };
  }
}

async function runEvaluation() {
  console.log('🚀 Starting Rally Consensus Evaluation (BATCH 3)...\n');
  console.log('='.repeat(80));
  
  const zai = await ZAI.create();
  const results = [];

  for (const content of NEW_CONTENTS) {
    console.log(`\n📝 Evaluating Content #${content.id}`);
    console.log('-'.repeat(80));
    console.log(`Content: "${content.content.substring(0, 70)}..."`);
    
    const evaluations = [];
    for (let v = 1; v <= 3; v++) {
      console.log(`  ⚙️  Validator ${v}/3...`);
      const evalResult = await evaluateContent(zai, content.content, content.id, v);
      evaluations.push(evalResult);
      console.log(`  ✅ Score: ${evalResult.total_score.toFixed(2)} | Gate Pass: ${evalResult.gates.gate_pass}`);
      if (v < 3) await new Promise(r => setTimeout(r, 2500));
    }

    // Calculate consensus
    const calcStats = (values: number[]) => {
      const mean = values.reduce((a, b) => a + b, 0) / values.length;
      const variance = values.reduce((a, b) => a + Math.pow(b - mean, 2), 0) / values.length;
      return { values, mean, variance, consensus: Math.round(mean * 100) / 100 };
    };

    const gates = {
      content_alignment: calcStats(evaluations.map((e: any) => e.gates.content_alignment)),
      information_accuracy: calcStats(evaluations.map((e: any) => e.gates.information_accuracy)),
      campaign_compliance: calcStats(evaluations.map((e: any) => e.gates.campaign_compliance)),
      originality_authenticity: calcStats(evaluations.map((e: any) => e.gates.originality_authenticity))
    };

    const quality = {
      engagement_potential: calcStats(evaluations.map((e: any) => e.quality.engagement_potential)),
      technical_quality: calcStats(evaluations.map((e: any) => e.quality.technical_quality))
    };

    const total_score = calcStats(evaluations.map((e: any) => e.total_score));
    const gate_multiplier = calcStats(evaluations.map((e: any) => e.gate_multiplier));

    const passVotes = evaluations.filter((e: any) => e.gates.gate_pass).length;
    const pass_consensus = passVotes === 3 || passVotes === 0;
    const variance_ok = total_score.variance <= 2.0;

    const allStrengths = evaluations.flatMap((e: any) => e.strengths);
    const allWeaknesses = evaluations.flatMap((e: any) => e.weaknesses);
    const allRecommendations = evaluations.flatMap((e: any) => e.recommendations);

    const getMostCommon = (arr: string[], minCount = 2) => {
      const counts = arr.reduce((acc, item) => {
        acc[item] = (acc[item] || 0) + 1;
        return acc;
      }, {} as Record<string, number>);
      return Object.entries(counts)
        .filter(([_, count]) => count >= minCount)
        .sort((a, b) => b[1] - a[1])
        .map(([item]) => item);
    };

    const result = {
      content_id: content.id,
      content: content.content,
      evaluations,
      consensus: { gates, quality, total_score, gate_multiplier },
      final_score: total_score.consensus,
      final_gate_multiplier: gate_multiplier.mean,
      disqualified: evaluations.every((e: any) => e.disqualified),
      pass_consensus,
      variance_ok,
      strengths: getMostCommon(allStrengths, 2).length > 0 ? getMostCommon(allStrengths, 2) : [...new Set(allStrengths)].slice(0, 3),
      weaknesses: getMostCommon(allWeaknesses, 2).length > 0 ? getMostCommon(allWeaknesses, 2) : [...new Set(allWeaknesses)].slice(0, 3),
      recommendations: getMostCommon(allRecommendations, 2).length > 0 ? getMostCommon(allRecommendations, 2) : [...new Set(allRecommendations)].slice(0, 3)
    };
    
    results.push(result);
    
    console.log(`\n📊 CONSENSUS:`);
    console.log(`   Gates: CA=${gates.content_alignment.consensus.toFixed(2)} | IA=${gates.information_accuracy.consensus.toFixed(2)} | CC=${gates.campaign_compliance.consensus.toFixed(2)} | OA=${gates.originality_authenticity.consensus.toFixed(2)}`);
    console.log(`   Quality: EP=${quality.engagement_potential.consensus.toFixed(2)} | TQ=${quality.technical_quality.consensus.toFixed(2)}`);
    console.log(`   Final: ${result.final_score.toFixed(2)} pts | Gate Mult: ${result.final_gate_multiplier.toFixed(2)}x | Variance: ${total_score.variance.toFixed(2)}`);
    console.log(`   Status: ${result.disqualified ? '❌ DQ' : '✅ PASS'} | Consensus: ${pass_consensus ? '✅ Full' : '⚠️ Split'}`);

    if (content.id < NEW_CONTENTS.length) await new Promise(r => setTimeout(r, 3000));
  }

  // Final report
  console.log('\n' + '='.repeat(80));
  console.log('🏆 FINAL RANKINGS\n');
  
  const sorted = [...results].sort((a, b) => b.final_score - a.final_score);
  sorted.forEach((r, i) => {
    const status = r.disqualified ? '❌ DQ' : '✅ PASS';
    console.log(`${i + 1}. Content #${r.content_id}: ${r.final_score.toFixed(2)} pts | ${r.final_gate_multiplier.toFixed(2)}x | ${status}`);
  });

  console.log('\n📈 DETAILED ANALYSIS:');
  sorted.forEach((r, i) => {
    console.log(`\n--- Content #${r.content_id} (Rank #${i + 1}) ---`);
    console.log(`Score: ${r.final_score.toFixed(2)} | Gate: ${r.final_gate_multiplier.toFixed(2)}x`);
    console.log(`Strengths: ${r.strengths.slice(0, 3).join(', ')}`);
    console.log(`Weaknesses: ${r.weaknesses.slice(0, 2).join(', ')}`);
  });

  return results;
}

runEvaluation().then(() => {
  console.log('\n✅ Evaluation completed!');
}).catch(err => {
  console.error('❌ Error:', err);
  process.exit(1);
});
