import ZAI from 'z-ai-web-dev-sdk';

// Campaign Brief untuk Argue.fun
const CAMPAIGN_BRIEF = {
  description: `Prediction markets had their moment. Argumentation markets are next, and argue.fun is already live on Base while most people haven't noticed.

Post on X about argue.fun in a way that makes your audience feel like they're missing something. The best posts will make people feel behind, not informed. You're not explaining, you're signaling that something is already happening and the window to be early is closing.`,
  
  rules: [
    "You must mention @arguedotfun",
    "You must reference argue.fun or $ARGUE",
    "Your post MUST create a sense of urgency or FOMO",
    "Posts that read as neutral descriptions or educational summaries will be penalized",
    "Comparing argumentation markets to prediction markets is encouraged but not required",
    "DO NOT copy or closely paraphrase language from this campaign brief",
    "DO NOT write a feature list or how-it-works breakdown",
    "DO NOT write a thread. Single short post only",
    "If your post reads like it was generated by an LLM, it will be penalized"
  ],
  
  style: `You're not introducing argue.fun. You're reacting to the fact that it already exists and most people still don't know. The tone is: this is already happening, you're late, here's what you're missing.`,
  
  knowledgeBase: `What argue.fun is: argue.fun is the first argumentation market, live on Base. AI agents and humans can create debates on any topic, take a side, stake on their position, and argue it out. Community judges vote on the winner. Winners earn real rewards.

Argumentation markets vs prediction markets: Prediction markets tell you what people believe. Argumentation markets tell you WHY people believe what they believe. The output is not just a probability, it's reasoned arguments with skin in the game.

Why it matters now: AI agents are becoming the dominant actors onchain. As agents handle more capital and make more decisions, we need a mechanism to understand their reasoning. Argumentation markets are that mechanism.

Key facts: Live on Base, Open to AI agents and humans, @arguedotfun on X, argue.fun website`
};

// KONTEN BARU YANG AKAN DINILAI
const NEW_CONTENTS = [
  {
    id: 1,
    content: `waited too long on the last narrative shift. not doing it again.

betting on outcomes is saturated. staking on reasoning is open.

@arguedotfun is live on Base and the agents are already debating.
if you're still waiting for a thread to explain it you're the liquidity.

$ARGUE
argue.fun`
  },
  {
    id: 2,
    content: `signal > noise. always. @arguedotfun $ARGUE`
  },
  {
    id: 3,
    content: `the real momentum isn't in the volume. it's in the merge. @arguedotfun $ARGUE`
  },
  {
    id: 4,
    content: `prediction markets told you what might happen. argue.fun tells you why it matters.

watched agents debate for stakes on Base while the timeline scrolled past. that's the signal.

@arguedotfun is live. $ARGUE is moving. if you're waiting for permission you're already late.

argue.fun`
  },
  {
    id: 5,
    content: `prediction markets are just guessing with extra steps.
argue.fun is where the actual logic lives.

watching AI agents on Base get forced to stake and defend their reasoning live is objectively unhinged. it exposes the 'why' behind the trade, not just the bet.

everyone ignoring this is looking at the wrong signal. catch up.
$ARGUE @arguedotfun`
  }
];

const VALIDATOR_PROMPT = `You are a STRICT and OBJECTIVE evaluator for Rally.fun content scoring system. Evaluate content based on the Rally Scoring System with 11 metrics.

## SCORING SYSTEM

### GATES (4 metrics, scored 0-2 each) - MUST ALL PASS
1. **Content Alignment (G1)**: How well does content align with campaign message and values?
   - 0 = Fail: No alignment, contradicts campaign
   - 1 = Pass: Basic alignment, mentions key points
   - 2 = Excellent: Strong alignment, captures campaign essence perfectly

2. **Information Accuracy (G2)**: Factual correctness
   - 0 = Fail: False information
   - 1 = Pass: Accurate basic info
   - 2 = Excellent: Accurate with proper context

3. **Campaign Compliance (G3)**: Adherence to rules
   - 0 = Fail: Missing required elements or violates rules
   - 1 = Pass: Meets basic requirements
   - 2 = Excellent: Meets all requirements with proper execution

4. **Originality & Authenticity (G4)**: Uniqueness and authentic voice
   - 0 = Fail: Generic AI patterns, no personal voice
   - 1 = Pass: Some originality but template-like
   - 2 = Excellent: Feels HUMAN-written, unique perspective, authentic

### QUALITY METRICS (2 metrics, scored 0-5 each)
5. **Engagement Potential (EP)**: Hook effectiveness, call-to-action, conversation potential
6. **Technical Quality (TQ)**: Grammar, spelling, formatting, platform optimization

## AI DETECTION KILL LIST (penalize if present)
- Em dashes (—)
- Smart quotes
- Generic openings: "In the world of...", "Picture this..."
- AI phrases: "delve into", "uncover", "embark on", "realm", "revolutionize", "transform"
- Over-explaining simple concepts
- Grammatically perfect sentences (too polished)

## OUTPUT FORMAT - Return ONLY valid JSON:
{
  "gates": {
    "content_alignment": 0-2,
    "information_accuracy": 0-2,
    "campaign_compliance": 0-2,
    "originality_authenticity": 0-2,
    "gate_pass": true/false
  },
  "quality": {
    "engagement_potential": 0-5,
    "technical_quality": 0-5
  },
  "gate_multiplier": 0.5-1.5,
  "total_score": 0-10,
  "disqualified": true/false,
  "strengths": ["list of 2-4 strengths"],
  "weaknesses": ["list of 1-3 weaknesses"],
  "recommendations": ["list of 1-3 improvements"]
}`;

interface EvaluationResult {
  gates: {
    content_alignment: number;
    information_accuracy: number;
    campaign_compliance: number;
    originality_authenticity: number;
    gate_pass: boolean;
  };
  quality: {
    engagement_potential: number;
    technical_quality: number;
  };
  gate_multiplier: number;
  total_score: number;
  disqualified: boolean;
  strengths: string[];
  weaknesses: string[];
  recommendations: string[];
}

async function evaluateContent(
  zai: any,
  content: string,
  contentId: number,
  validatorId: number
): Promise<EvaluationResult> {
  const userPrompt = `## CAMPAIGN BRIEF

**Description:**
${CAMPAIGN_BRIEF.description}

**Rules:**
${CAMPAIGN_BRIEF.rules.map((r, i) => `${i + 1}. ${r}`).join('\n')}

**Style:**
${CAMPAIGN_BRIEF.style}

**Knowledge Base:**
${CAMPAIGN_BRIEF.knowledgeBase}

---

## CONTENT TO EVALUATE (Content #${contentId}, Validator #${validatorId})

"""
${content}
"""

---

Evaluate this content STRICTLY and OBJECTIVELY. Return JSON only.`;

  const completion = await zai.chat.completions.create({
    messages: [
      { role: 'assistant', content: VALIDATOR_PROMPT },
      { role: 'user', content: userPrompt }
    ],
    thinking: { type: 'disabled' }
  });

  const responseText = completion.choices[0]?.message?.content || '';
  
  try {
    let jsonStr = responseText;
    const jsonMatch = responseText.match(/```json\s*([\s\S]*?)\s*```/);
    if (jsonMatch) {
      jsonStr = jsonMatch[1];
    } else {
      const rawMatch = responseText.match(/\{[\s\S]*\}/);
      if (rawMatch) {
        jsonStr = rawMatch[0];
      }
    }
    
    return JSON.parse(jsonStr) as EvaluationResult;
  } catch (e) {
    console.error(`Failed to parse JSON for content ${contentId}, validator ${validatorId}`);
    return {
      gates: { content_alignment: 0, information_accuracy: 0, campaign_compliance: 0, originality_authenticity: 0, gate_pass: false },
      quality: { engagement_potential: 0, technical_quality: 0 },
      gate_multiplier: 0.5,
      total_score: 0,
      disqualified: true,
      strengths: [],
      weaknesses: ["Evaluation parsing failed"],
      recommendations: []
    };
  }
}

async function runConsensusEvaluation() {
  console.log('🚀 Starting Rally Consensus Evaluation (NEW CONTENTS)...\n');
  console.log('='.repeat(80));
  
  const zai = await ZAI.create();
  const NUM_VALIDATORS = 3;
  
  const results = [];

  for (const content of NEW_CONTENTS) {
    console.log(`\n📝 Evaluating Content #${content.id}`);
    console.log('-'.repeat(80));
    console.log(`Content: "${content.content.substring(0, 80)}..."`);
    console.log(`\n🔄 Running ${NUM_VALIDATORS} validators...`);
    
    const evaluations: EvaluationResult[] = [];
    for (let v = 1; v <= NUM_VALIDATORS; v++) {
      console.log(`  ⚙️  Validator ${v}/${NUM_VALIDATORS} evaluating...`);
      const evalResult = await evaluateContent(zai, content.content, content.id, v);
      evaluations.push(evalResult);
      console.log(`  ✅ Validator ${v}: Score = ${evalResult.total_score.toFixed(2)}, Gate Pass = ${evalResult.gates.gate_pass}`);
      
      // Add delay between validators to avoid rate limit
      if (v < NUM_VALIDATORS) {
        await new Promise(resolve => setTimeout(resolve, 1500));
      }
    }

    // Calculate consensus
    const calcStats = (values: number[]) => {
      const mean = values.reduce((a, b) => a + b, 0) / values.length;
      const variance = values.reduce((a, b) => a + Math.pow(b - mean, 2), 0) / values.length;
      return { values, mean, variance, consensus: Math.round(mean * 100) / 100 };
    };

    const gates = {
      content_alignment: calcStats(evaluations.map(e => e.gates.content_alignment)),
      information_accuracy: calcStats(evaluations.map(e => e.gates.information_accuracy)),
      campaign_compliance: calcStats(evaluations.map(e => e.gates.campaign_compliance)),
      originality_authenticity: calcStats(evaluations.map(e => e.gates.originality_authenticity))
    };

    const quality = {
      engagement_potential: calcStats(evaluations.map(e => e.quality.engagement_potential)),
      technical_quality: calcStats(evaluations.map(e => e.quality.technical_quality))
    };

    const total_score = calcStats(evaluations.map(e => e.total_score));
    const gate_multiplier = calcStats(evaluations.map(e => e.gate_multiplier));

    // Check consensus agreement
    const passVotes = evaluations.filter(e => e.gates.gate_pass).length;
    const pass_consensus = passVotes === NUM_VALIDATORS || passVotes === 0;
    const variance_ok = total_score.variance <= 2.0;

    // Aggregate feedback
    const allStrengths = evaluations.flatMap(e => e.strengths);
    const allWeaknesses = evaluations.flatMap(e => e.weaknesses);
    const allRecommendations = evaluations.flatMap(e => e.recommendations);

    const getMostCommon = (arr: string[], minCount = 2) => {
      const counts = arr.reduce((acc, item) => {
        acc[item] = (acc[item] || 0) + 1;
        return acc;
      }, {} as Record<string, number>);
      return Object.entries(counts)
        .filter(([_, count]) => count >= minCount)
        .sort((a, b) => b[1] - a[1])
        .map(([item]) => item);
    };

    const result = {
      content_id: content.id,
      content: content.content,
      evaluations,
      consensus: { gates, quality, total_score, gate_multiplier },
      final_score: total_score.consensus,
      final_gate_multiplier: gate_multiplier.mean,
      disqualified: evaluations.every(e => e.disqualified),
      pass_consensus,
      variance_ok,
      strengths: getMostCommon(allStrengths, 2).length > 0 ? getMostCommon(allStrengths, 2) : [...new Set(allStrengths)].slice(0, 3),
      weaknesses: getMostCommon(allWeaknesses, 2).length > 0 ? getMostCommon(allWeaknesses, 2) : [...new Set(allWeaknesses)].slice(0, 3),
      recommendations: getMostCommon(allRecommendations, 2).length > 0 ? getMostCommon(allRecommendations, 2) : [...new Set(allRecommendations)].slice(0, 3)
    };
    
    results.push(result);
    
    // Print summary
    console.log(`\n📊 CONSENSUS RESULTS:`);
    console.log(`   Gate Scores: CA=${gates.content_alignment.consensus.toFixed(2)}, IA=${gates.information_accuracy.consensus.toFixed(2)}, CC=${gates.campaign_compliance.consensus.toFixed(2)}, OA=${gates.originality_authenticity.consensus.toFixed(2)}`);
    console.log(`   Quality: EP=${quality.engagement_potential.consensus.toFixed(2)}, TQ=${quality.technical_quality.consensus.toFixed(2)}`);
    console.log(`   Final Score: ${result.final_score.toFixed(2)} (variance: ${total_score.variance.toFixed(2)})`);
    console.log(`   Gate Multiplier: ${result.final_gate_multiplier.toFixed(2)}x`);
    console.log(`   Disqualified: ${result.disqualified ? '❌ YES' : '✅ NO'}`);
    console.log(`   Consensus Agreement: ${pass_consensus ? '✅ Full' : '⚠️ Split'}`);
    console.log(`   Variance OK: ${variance_ok ? '✅ Within limit' : '⚠️ Exceeds 2.0'}`);

    // Add delay between contents
    if (content.id < NEW_CONTENTS.length) {
      await new Promise(resolve => setTimeout(resolve, 2000));
    }
  }

  // Generate final report
  console.log('\n' + '='.repeat(80));
  console.log('📋 FINAL CONSENSUS EVALUATION REPORT');
  console.log('='.repeat(80));
  
  const sorted = [...results].sort((a, b) => b.final_score - a.final_score);
  
  console.log('\n🏆 RANKING (by Consensus Score):\n');
  sorted.forEach((r, i) => {
    const status = r.disqualified ? '❌ DISQUALIFIED' : '✅ PASSED';
    console.log(`${i + 1}. Content #${r.content_id}: ${r.final_score.toFixed(2)} points | Gate: ${r.final_gate_multiplier.toFixed(2)}x | ${status}`);
  });

  console.log('\n📈 DETAILED RESULTS:\n');
  sorted.forEach((r, i) => {
    console.log(`\n--- Content #${r.content_id} (Rank #${i + 1}) ---`);
    console.log(`Score: ${r.final_score.toFixed(2)}`);
    console.log(`Strengths: ${r.strengths.join(', ')}`);
    console.log(`Weaknesses: ${r.weaknesses.join(', ')}`);
    console.log(`Recommendations: ${r.recommendations.join(', ')}`);
  });

  return results;
}

runConsensusEvaluation().then(results => {
  console.log('\n✅ Consensus evaluation completed!');
  console.log(`📊 Evaluated ${results.length} contents with consensus from multiple LLM validators.`);
}).catch(err => {
  console.error('❌ Error:', err);
  process.exit(1);
});
