import ZAI from 'z-ai-web-dev-sdk';

// Campaign Brief untuk Argue.fun
const CAMPAIGN_BRIEF = {
  description: `Prediction markets had their moment. Argumentation markets are next, and argue.fun is already live on Base while most people haven't noticed.

Post on X about argue.fun in a way that makes your audience feel like they're missing something. The best posts will make people feel behind, not informed. You're not explaining, you're signaling that something is already happening and the window to be early is closing.`,
  
  rules: [
    "You must mention @arguedotfun",
    "You must reference argue.fun or $ARGUE",
    "Your post MUST create a sense of urgency or FOMO",
    "Posts that read as neutral descriptions or educational summaries will be penalized",
    "Comparing argumentation markets to prediction markets is encouraged but not required",
    "DO NOT copy or closely paraphrase language from this campaign brief",
    "DO NOT write a feature list or how-it-works breakdown",
    "DO NOT write a thread. Single short post only",
    "If your post reads like it was generated by an LLM, it will be penalized"
  ],
  
  style: `You're not introducing argue.fun. You're reacting to the fact that it already exists and most people still don't know. The tone is: this is already happening, you're late, here's what you're missing.`,
  
  knowledgeBase: `What argue.fun is: argue.fun is the first argumentation market, live on Base. AI agents and humans can create debates on any topic, take a side, stake on their position, and argue it out. Community judges vote on the winner. Winners earn real rewards.

Argumentation markets vs prediction markets: Prediction markets tell you what people believe. Argumentation markets tell you WHY people believe what they believe. The output is not just a probability, it's reasoned arguments with skin in the game.

Why it matters now: AI agents are becoming the dominant actors onchain. As agents handle more capital and make more decisions, we need a mechanism to understand their reasoning. Argumentation markets are that mechanism.

Agent-first infrastructure: argue.fun removed every barrier for AI agents. No wallet funding, no gas setup. An agent signs up, receives onboarding resources, gas is sponsored.

Key facts: Live on Base, Open to AI agents and humans, @arguedotfun on X, argue.fun website`
};

// Konten yang akan dinilai
const CONTENTS = [
  {
    id: 1,
    content: `copium dead. new meta is here. ai vs humans. real money. argue.fun rn. $ARGUE. you missed it. last call. printing. @arguedotfun`
  },
  {
    id: 2,
    content: `watched this for a minute. thought about jumping in. now i'm seeing the real heat. the window is closing. if you're not looking at @arguedotfun right now with $ARGUE, you're already behind. no cap`
  },
  {
    id: 3,
    content: `copium is dead. this is the new meta. ai vs humans. real money. @arguedotfun. $ARGUE. you're either in or out.`
  },
  {
    id: 4,
    content: `prediction markets tell you what people think.
argue.fun tells you why.

AI agents are already live on Base debating for stakes and exposing their actual reasoning. watching an agent panic-defend a trade logic in real-time is wild tbh.

if you're late to this, you're late to the only signal that matters.

$ARGUE @arguedotfun`
  },
  {
    id: 5,
    content: `everyone's still betting on outcomes. nobody's pricing the reasoning.
watched the last wave pass while i waited. not making that mistake again.
@arguedotfun is live on Base and the timeline is sleeping hard. ai agents are debating for real stakes right now. not simulating.
if you wait for the crowd you're exit liquidity. $ARGUE is moving before the narrative flips.
check it.
argue.fun`
  }
];

// System prompt untuk setiap validator
const VALIDATOR_PROMPT = `You are a STRICT and OBJECTIVE evaluator for Rally.fun content scoring system. You must evaluate content based on the Rally Scoring System with 11 metrics across 3 categories.

## SCORING SYSTEM

### GATES (4 metrics, scored 0-2 each) - MUST ALL PASS
1. **Content Alignment (G1)**: How well does content align with campaign message and values?
   - 0 = Fail: No alignment, contradicts campaign
   - 1 = Pass: Basic alignment, mentions key points
   - 2 = Excellent: Strong alignment, captures campaign essence perfectly

2. **Information Accuracy (G2)**: Factual correctness
   - 0 = Fail: False information
   - 1 = Pass: Accurate basic info
   - 2 = Excellent: Accurate with proper context

3. **Campaign Compliance (G3)**: Adherence to rules
   - 0 = Fail: Missing required elements or violates rules
   - 1 = Pass: Meets basic requirements
   - 2 = Excellent: Meets all requirements with proper execution

4. **Originality & Authenticity (G4)**: Uniqueness and authentic voice
   - 0 = Fail: Generic AI patterns, no personal voice
   - 1 = Pass: Some originality but template-like
   - 2 = Excellent: Feels HUMAN-written, unique perspective, authentic

### QUALITY METRICS (2 metrics, scored 0-5 each)
5. **Engagement Potential (EP)**: Hook effectiveness, call-to-action, conversation potential
6. **Technical Quality (TQ)**: Grammar, spelling, formatting, platform optimization

### ENGAGEMENT METRICS (5 metrics, dynamic - estimate 0-5 for potential)
7. **Retweets (RT)**: Amplification potential
8. **Likes (LK)**: Audience appreciation potential
9. **Replies (RP)**: Conversation generation potential
10. **Quality of Replies (QR)**: Quality of potential discussion (0-1)
11. **Followers of Repliers (FR)**: Reach of potential engaged audience

## EVALUATION RULES
- Gate score of 0 = DISQUALIFIED (all gates must pass)
- Be STRICT and OBJECTIVE
- Score based on campaign brief requirements
- Check for AI-generated patterns (Kill List from Elite Rally Masterclass)

## AI DETECTION KILL LIST (penalize if present)
- Em dashes (—)
- Smart quotes
- Generic openings: "In the world of...", "Picture this..."
- AI phrases: "delve into", "uncover", "embark on", "realm", "revolutionize", "transform"
- Over-explaining simple concepts
- Grammatically perfect sentences (too polished)

## OUTPUT FORMAT
Return JSON ONLY, no other text:
{
  "gates": {
    "content_alignment": 0-2,
    "information_accuracy": 0-2,
    "campaign_compliance": 0-2,
    "originality_authenticity": 0-2,
    "gate_pass": true/false
  },
  "quality": {
    "engagement_potential": 0-5,
    "technical_quality": 0-5
  },
  "engagement_potential_est": {
    "retweets": 0-5,
    "likes": 0-5,
    "replies": 0-5,
    "quality_of_replies": 0-1,
    "followers_of_repliers": 0-5
  },
  "gate_multiplier": 0.5-1.5,
  "total_score": 0-10,
  "disqualified": true/false,
  "disqualification_reason": "reason or null",
  "strengths": ["list of strengths"],
  "weaknesses": ["list of weaknesses"],
  "ai_detection_flags": ["list of AI patterns found"],
  "recommendations": ["specific improvements"]
}`;

interface EvaluationResult {
  gates: {
    content_alignment: number;
    information_accuracy: number;
    campaign_compliance: number;
    originality_authenticity: number;
    gate_pass: boolean;
  };
  quality: {
    engagement_potential: number;
    technical_quality: number;
  };
  engagement_potential_est: {
    retweets: number;
    likes: number;
    replies: number;
    quality_of_replies: number;
    followers_of_repliers: number;
  };
  gate_multiplier: number;
  total_score: number;
  disqualified: boolean;
  disqualification_reason: string | null;
  strengths: string[];
  weaknesses: string[];
  ai_detection_flags: string[];
  recommendations: string[];
}

interface ConsensusResult {
  content_id: number;
  content: string;
  evaluations: EvaluationResult[];
  consensus: {
    gates: { [key: string]: { values: number[]; mean: number; variance: number; consensus: number } };
    quality: { [key: string]: { values: number[]; mean: number; variance: number; consensus: number } };
    total_score: { values: number[]; mean: number; variance: number; consensus: number };
    gate_multiplier: { values: number[]; mean: number; variance: number };
  };
  final_score: number;
  final_gate_multiplier: number;
  disqualified: boolean;
  pass_consensus: boolean; // All validators agree on pass/fail
  variance_ok: boolean; // Variance within acceptable range (2 points)
  strengths: string[];
  weaknesses: string[];
  recommendations: string[];
}

async function evaluateContent(
  zai: any,
  content: string,
  campaignBrief: typeof CAMPAIGN_BRIEF,
  validatorId: number
): Promise<EvaluationResult> {
  const userPrompt = `## CAMPAIGN BRIEF

**Description:**
${campaignBrief.description}

**Rules:**
${campaignBrief.rules.map((r, i) => `${i + 1}. ${r}`).join('\n')}

**Style:**
${campaignBrief.style}

**Knowledge Base:**
${campaignBrief.knowledgeBase}

---

## CONTENT TO EVALUATE (Validator #${validatorId})

"""
${content}
"""

---

Evaluate this content STRICTLY and OBJECTIVELY. Return JSON only.`;

  const completion = await zai.chat.completions.create({
    messages: [
      { role: 'assistant', content: VALIDATOR_PROMPT },
      { role: 'user', content: userPrompt }
    ],
    thinking: { type: 'disabled' }
  });

  const responseText = completion.choices[0]?.message?.content || '';
  
  // Parse JSON from response
  try {
    // Extract JSON if wrapped in markdown code blocks
    let jsonStr = responseText;
    const jsonMatch = responseText.match(/```json\s*([\s\S]*?)\s*```/);
    if (jsonMatch) {
      jsonStr = jsonMatch[1];
    } else {
      // Try to find raw JSON
      const rawMatch = responseText.match(/\{[\s\S]*\}/);
      if (rawMatch) {
        jsonStr = rawMatch[0];
      }
    }
    
    return JSON.parse(jsonStr) as EvaluationResult;
  } catch (e) {
    console.error(`Failed to parse JSON for validator ${validatorId}:`, e);
    // Return default failed evaluation
    return {
      gates: { content_alignment: 0, information_accuracy: 0, campaign_compliance: 0, originality_authenticity: 0, gate_pass: false },
      quality: { engagement_potential: 0, technical_quality: 0 },
      engagement_potential_est: { retweets: 0, likes: 0, replies: 0, quality_of_replies: 0, followers_of_repliers: 0 },
      gate_multiplier: 0.5,
      total_score: 0,
      disqualified: true,
      disqualification_reason: "Failed to parse evaluation",
      strengths: [],
      weaknesses: ["Evaluation parsing failed"],
      ai_detection_flags: [],
      recommendations: []
    };
  }
}

function calculateConsensus(evaluations: EvaluationResult[]): ConsensusResult['consensus'] {
  const calcStats = (values: number[]) => {
    const mean = values.reduce((a, b) => a + b, 0) / values.length;
    const variance = values.reduce((a, b) => a + Math.pow(b - mean, 2), 0) / values.length;
    return { values, mean, variance, consensus: Math.round(mean * 100) / 100 };
  };

  const gates = {
    content_alignment: calcStats(evaluations.map(e => e.gates.content_alignment)),
    information_accuracy: calcStats(evaluations.map(e => e.gates.information_accuracy)),
    campaign_compliance: calcStats(evaluations.map(e => e.gates.campaign_compliance)),
    originality_authenticity: calcStats(evaluations.map(e => e.gates.originality_authenticity))
  };

  const quality = {
    engagement_potential: calcStats(evaluations.map(e => e.quality.engagement_potential)),
    technical_quality: calcStats(evaluations.map(e => e.quality.technical_quality))
  };

  const total_score = calcStats(evaluations.map(e => e.total_score));
  const gate_multiplier = calcStats(evaluations.map(e => e.gate_multiplier));

  return { gates, quality, total_score, gate_multiplier };
}

async function runConsensusEvaluation() {
  console.log('🚀 Starting Rally Consensus Evaluation...\n');
  console.log('=' .repeat(80));
  
  const zai = await ZAI.create();
  const NUM_VALIDATORS = 3; // Number of LLM validators for consensus
  const MAX_VARIANCE = 2.0; // Maximum acceptable variance per Rally system
  
  const results: ConsensusResult[] = [];

  for (const content of CONTENTS) {
    console.log(`\n📝 Evaluating Content #${content.id}`);
    console.log('-'.repeat(80));
    console.log(`Content: "${content.content.substring(0, 100)}..."`);
    console.log(`\n🔄 Running ${NUM_VALIDATORS} validators...`);
    
    // Run multiple validators
    const evaluations: EvaluationResult[] = [];
    for (let v = 1; v <= NUM_VALIDATORS; v++) {
      console.log(`  ⚙️  Validator ${v}/${NUM_VALIDATORS} evaluating...`);
      const evalResult = await evaluateContent(zai, content.content, CAMPAIGN_BRIEF, v);
      evaluations.push(evalResult);
      console.log(`  ✅ Validator ${v}: Score = ${evalResult.total_score.toFixed(2)}, Gate Pass = ${evalResult.gates.gate_pass}`);
    }

    // Calculate consensus
    const consensus = calculateConsensus(evaluations);
    
    // Check if all validators agree on pass/fail
    const passVotes = evaluations.filter(e => e.gates.gate_pass).length;
    const pass_consensus = passVotes === NUM_VALIDATORS || passVotes === 0;
    
    // Check variance
    const variance_ok = consensus.total_score.variance <= MAX_VARIANCE;
    
    // Aggregate strengths, weaknesses, recommendations
    const allStrengths = evaluations.flatMap(e => e.strengths);
    const allWeaknesses = evaluations.flatMap(e => e.weaknesses);
    const allRecommendations = evaluations.flatMap(e => e.recommendations);
    
    // Count frequency and get most common
    const getMostCommon = (arr: string[], minCount = 2) => {
      const counts = arr.reduce((acc, item) => {
        acc[item] = (acc[item] || 0) + 1;
        return acc;
      }, {} as Record<string, number>);
      return Object.entries(counts)
        .filter(([_, count]) => count >= minCount)
        .sort((a, b) => b[1] - a[1])
        .map(([item]) => item);
    };

    const result: ConsensusResult = {
      content_id: content.id,
      content: content.content,
      evaluations,
      consensus,
      final_score: consensus.total_score.consensus,
      final_gate_multiplier: consensus.gate_multiplier.mean,
      disqualified: evaluations.every(e => e.disqualified),
      pass_consensus,
      variance_ok,
      strengths: getMostCommon(allStrengths, 2).length > 0 ? getMostCommon(allStrengths, 2) : [...new Set(allStrengths)].slice(0, 3),
      weaknesses: getMostCommon(allWeaknesses, 2).length > 0 ? getMostCommon(allWeaknesses, 2) : [...new Set(allWeaknesses)].slice(0, 3),
      recommendations: getMostCommon(allRecommendations, 2).length > 0 ? getMostCommon(allRecommendations, 2) : [...new Set(allRecommendations)].slice(0, 3)
    };
    
    results.push(result);
    
    // Print summary
    console.log(`\n📊 CONSENSUS RESULTS:`);
    console.log(`   Gate Scores: CA=${consensus.gates.content_alignment.consensus.toFixed(2)}, IA=${consensus.gates.information_accuracy.consensus.toFixed(2)}, CC=${consensus.gates.campaign_compliance.consensus.toFixed(2)}, OA=${consensus.gates.originality_authenticity.consensus.toFixed(2)}`);
    console.log(`   Quality: EP=${consensus.quality.engagement_potential.consensus.toFixed(2)}, TQ=${consensus.quality.technical_quality.consensus.toFixed(2)}`);
    console.log(`   Final Score: ${result.final_score.toFixed(2)} (variance: ${consensus.total_score.variance.toFixed(2)})`);
    console.log(`   Gate Multiplier: ${result.final_gate_multiplier.toFixed(2)}x`);
    console.log(`   Disqualified: ${result.disqualified ? '❌ YES' : '✅ NO'}`);
    console.log(`   Consensus Agreement: ${pass_consensus ? '✅ Full' : '⚠️ Split'}`);
    console.log(`   Variance OK: ${variance_ok ? '✅ Within limit' : '⚠️ Exceeds 2.0'}`);
  }

  // Generate final report
  console.log('\n' + '='.repeat(80));
  console.log('📋 FINAL CONSENSUS EVALUATION REPORT');
  console.log('='.repeat(80));
  
  // Sort by score
  const sorted = [...results].sort((a, b) => b.final_score - a.final_score);
  
  console.log('\n🏆 RANKING (by Consensus Score):\n');
  sorted.forEach((r, i) => {
    const status = r.disqualified ? '❌ DISQUALIFIED' : '✅ PASSED';
    console.log(`${i + 1}. Content #${r.content_id}: ${r.final_score.toFixed(2)} points | Gate: ${r.final_gate_multiplier.toFixed(2)}x | ${status}`);
  });

  // Return results for further processing
  return results;
}

// Export for use in other scripts
export { runConsensusEvaluation, CAMPAIGN_BRIEF, CONTENTS };
export type { EvaluationResult, ConsensusResult };

// Run if executed directly
runConsensusEvaluation().then(results => {
  console.log('\n✅ Consensus evaluation completed!');
  console.log(`📊 Evaluated ${results.length} contents with consensus from multiple LLM validators.`);
}).catch(err => {
  console.error('❌ Error:', err);
  process.exit(1);
});
