#!/usr/bin/env python3
"""
Rally.fun COMPLETE Guide - All-in-One Documentation
Combines ALL content from previous PDFs + new content
"""

from reportlab.lib.pagesizes import A4
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, 
    PageBreak, ListFlowable, ListItem
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

# Register fonts
pdfmetrics.registerFont(TTFont('SimHei', '/usr/share/fonts/truetype/chinese/SimHei.ttf'))
pdfmetrics.registerFont(TTFont('Microsoft YaHei', '/usr/share/fonts/truetype/chinese/msyh.ttf'))
pdfmetrics.registerFont(TTFont('Times New Roman', '/usr/share/fonts/truetype/english/Times-New-Roman.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', '/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf'))

registerFontFamily('Times New Roman', normal='Times New Roman', bold='Times New Roman')
registerFontFamily('SimHei', normal='SimHei', bold='SimHei')
registerFontFamily('Microsoft YaHei', normal='Microsoft YaHei', bold='Microsoft YaHei')

HEADER_COLOR = colors.HexColor('#1F4E79')
ACCENT_COLOR = colors.HexColor('#2E7D32')
WARNING_COLOR = colors.HexColor('#D97706')

doc = SimpleDocTemplate(
    "/home/z/my-project/public/rally-complete-guide.pdf",
    pagesize=A4,
    title="Rally Complete Guide",
    author="Z.ai",
    creator="Z.ai",
    subject="Complete Rally.fun Scoring System - AI Ready"
)

styles = getSampleStyleSheet()
styles.add(ParagraphStyle(name='CT', fontName='Microsoft YaHei', fontSize=36, leading=44, alignment=TA_CENTER, spaceAfter=24))
styles.add(ParagraphStyle(name='CS', fontName='SimHei', fontSize=16, leading=24, alignment=TA_CENTER, spaceAfter=30, textColor=colors.HexColor('#555555')))
styles.add(ParagraphStyle(name='H1', fontName='Microsoft YaHei', fontSize=18, leading=26, spaceBefore=20, spaceAfter=12, textColor=HEADER_COLOR))
styles.add(ParagraphStyle(name='H2', fontName='Microsoft YaHei', fontSize=14, leading=20, spaceBefore=16, spaceAfter=8, textColor=HEADER_COLOR))
styles.add(ParagraphStyle(name='H3', fontName='SimHei', fontSize=12, leading=18, spaceBefore=10, spaceAfter=6, textColor=colors.HexColor('#333333')))
styles.add(ParagraphStyle(name='B', fontName='SimHei', fontSize=10, leading=16, alignment=TA_LEFT, spaceBefore=4, spaceAfter=4, wordWrap='CJK'))
styles.add(ParagraphStyle(name='BOLD', fontName='SimHei', fontSize=10, leading=16, alignment=TA_LEFT, spaceBefore=4, spaceAfter=4, wordWrap='CJK'))
styles.add(ParagraphStyle(name='CodeBlock', fontName='DejaVuSans', fontSize=8, leading=12, alignment=TA_LEFT, backColor=colors.HexColor('#F0F0F0'), leftIndent=10, rightIndent=10, spaceBefore=4, spaceAfter=4))
styles.add(ParagraphStyle(name='TH', fontName='SimHei', fontSize=9, leading=12, alignment=TA_CENTER, textColor=colors.white))
styles.add(ParagraphStyle(name='TC', fontName='SimHei', fontSize=8, leading=11, alignment=TA_CENTER, wordWrap='CJK'))
styles.add(ParagraphStyle(name='TCL', fontName='SimHei', fontSize=8, leading=11, alignment=TA_LEFT, wordWrap='CJK'))
styles.add(ParagraphStyle(name='Cap', fontName='SimHei', fontSize=9, leading=12, alignment=TA_CENTER, spaceBefore=4, spaceAfter=10, textColor=colors.HexColor('#666666')))

story = []

# ===================== COVER PAGE =====================
story.append(Spacer(1, 60))
story.append(Paragraph("<b>RALLY.FUN</b>", styles['CT']))
story.append(Paragraph("<b>COMPLETE SCORING GUIDE</b>", styles['CT']))
story.append(Spacer(1, 15))
story.append(Paragraph("Version 6.0 - AI-Ready Documentation", styles['CS']))
story.append(Paragraph("Scoring System + API Analysis + AI Prompts + Implementation", styles['CS']))
story.append(Spacer(1, 40))
story.append(Paragraph("<b>Generated by Z.ai</b>", styles['B']))
story.append(Paragraph("Based on Real API Data from Rally.fun Staging Environment", styles['B']))
story.append(Spacer(1, 30))

# Feature highlights
story.append(Paragraph("""
<b>This guide includes:</b>
- Complete 11-metric scoring system
- Hidden factors that affect scores
- Real API data analysis
- AI system prompts for analysis
- Step-by-step scoring formulas
- Optimization strategies
""", styles['B']))

story.append(PageBreak())

# ===================== TABLE OF CONTENTS =====================
story.append(Paragraph("<b>TABLE OF CONTENTS</b>", styles['H1']))
story.append(Spacer(1, 8))

toc_content = """
<b>PART 0: AI SYSTEM PROMPT</b> - Instructions for AI to analyze content

<b>PART 1: SCORING FUNDAMENTALS</b>
1.1 The 11 Scoring Metrics | 1.2 Gate Categories | 1.3 Quality Categories | 1.4 Engagement Metrics

<b>PART 2: HIDDEN FACTORS</b>
2.1 Campaign Context | 2.2 Timing | 2.3 Platform Algorithms | 2.4 Content Patterns

<b>PART 3: API DISCOVERY</b>
3.1 Official vs Undocumented API | 3.2 Response Structure | 3.3 Sample Data

<b>PART 4: SCORING FORMULA</b>
4.1 Atto Format | 4.2 Gate Multiplier | 4.3 Points Calculation | 4.4 Grade System

<b>PART 5: AI ANALYSIS PATTERNS</b>
5.1 Content Alignment | 5.2 Engagement Potential | 5.3 Technical Quality | 5.4 Reply Quality

<b>PART 6: REAL DATA ANALYSIS</b>
6.1 Submission Scores | 6.2 Pattern Insights | 6.3 Correlation Analysis

<b>PART 7: CONTENT PATTERNS</b>
7.1 Safe Patterns | 7.2 Risky Patterns | 7.3 Examples

<b>PART 8: IMPLEMENTATION</b>
8.1 Optimization Tips | 8.2 Pre-Submit Checklist | 8.3 API Calibration
"""
story.append(Paragraph(toc_content.replace('\n', '<br/>'), styles['B']))
story.append(PageBreak())

# ===================== PART 0: AI SYSTEM PROMPT =====================
story.append(Paragraph("<b>PART 0: AI SYSTEM PROMPT</b>", styles['H1']))
story.append(Paragraph("""
<b>Instructions for AI to analyze Rally content:</b>
""", styles['B']))

story.append(Paragraph("<b>0.1 Role Definition</b>", styles['H2']))
story.append(Paragraph("""
You are a Rally.fun content scoring expert. Your task is to analyze content submitted to Rally campaigns and predict scores based on the official Rally.fun scoring formula.

You must evaluate content across 11 metrics and provide:
1. Gate scores (0-2 each): Content Alignment, Information Accuracy, Campaign Compliance, Originality
2. Quality scores (0-5 each): Engagement Potential, Technical Quality, Reply Quality
3. Engagement projection: Likes, Replies, Retweets, Impressions, Followers of Repliers
4. Final estimated score with grade
""", styles['B']))

story.append(Paragraph("<b>0.2 Input Format</b>", styles['H2']))
story.append(Paragraph("""
You will receive:
- Content text (tweet/post)
- Campaign context (mission, rules, style, required elements)
- Optional: Previous submission examples for reference
""", styles['B']))

story.append(Paragraph("<b>0.3 Output Format</b>", styles['H2']))
story.append(Paragraph("""
Return JSON with this structure:
{
  "gates": {
    "contentAlignment": { "score": 0-2, "reason": "..." },
    "informationAccuracy": { "score": 0-2, "reason": "..." },
    "campaignCompliance": { "score": 0-2, "reason": "..." },
    "originality": { "score": 0-2, "reason": "..." }
  },
  "quality": {
    "engagementPotential": { "score": 0-5, "reason": "..." },
    "technicalQuality": { "score": 0-5, "reason": "..." },
    "replyQuality": { "score": 0-5, "reason": "..." }
  },
  "engagement": {
    "likes": number,
    "replies": number,
    "retweets": number,
    "impressions": number,
    "followersOfRepliers": number
  },
  "estimates": {
    "atemporalPoints": number,
    "temporalPoints": number,
    "totalPoints": number,
    "grade": "S+/S/A+/A/B+/B/C+/C/D/F"
  }
}
""", styles['CodeBlock']))

story.append(Paragraph("<b>0.4 Scoring Rules (CRITICAL)</b>", styles['H2']))
story.append(Paragraph("""
<b>Gate Scoring (0-2):</b>
- 0 = FAIL: Content violates requirements or is off-topic
- 1 = PARTIAL: Meets some requirements but has issues
- 2 = PASS: Fully meets all requirements

<b>Quality Scoring (0-5):</b>
Rate each sub-factor 1-5, then average:
- Engagement: Hook, CTA, Structure, Conversation, Value
- Technical: Grammar, Formatting, Platform Opt, Thread Flow
- Reply: Relevance, Constructiveness, Authenticity

<b>IMPORTANT: If ANY gate = 0, apply 0.5x multiplier penalty!</b>
""", styles['B']))

story.append(PageBreak())

# ===================== PART 1: SCORING FUNDAMENTALS =====================
story.append(Paragraph("<b>PART 1: SCORING FUNDAMENTALS</b>", styles['H1']))

story.append(Paragraph("<b>1.1 The 11 Scoring Metrics</b>", styles['H2']))
story.append(Paragraph("""
Rally.fun uses a multi-criteria evaluation system with 11 metrics in 3 categories:

<b>Gate Categories (4 metrics, 0-2 each)</b> - Determine acceptance and multiplier
<b>Quality Categories (3 metrics, 0-5 each)</b> - Determine content quality score
<b>Engagement Metrics (4 metrics, dynamic)</b> - Calculated from actual engagement
""", styles['B']))

story.append(Paragraph("<b>1.2 Gate Categories (0-2 each)</b>", styles['H2']))

gd = [
    [Paragraph('<b>Category</b>', styles['TH']), Paragraph('<b>Max</b>', styles['TH']), Paragraph('<b>Criteria</b>', styles['TH']), Paragraph('<b>If = 0</b>', styles['TH'])],
    [Paragraph('Originality', styles['TCL']), Paragraph('2.0', styles['TC']), Paragraph('Original content, not copy-paste or spam', styles['TCL']), Paragraph('0.5x penalty', styles['TC'])],
    [Paragraph('Content Alignment', styles['TCL']), Paragraph('2.0', styles['TC']), Paragraph('Alignment with campaign mission and guidelines', styles['TCL']), Paragraph('0.5x penalty', styles['TC'])],
    [Paragraph('Information Accuracy', styles['TCL']), Paragraph('2.0', styles['TC']), Paragraph('Accuracy of information, no false claims', styles['TCL']), Paragraph('0.5x penalty', styles['TC'])],
    [Paragraph('Campaign Compliance', styles['TCL']), Paragraph('2.0', styles['TC']), Paragraph('Compliance with campaign rules, hashtags, mentions', styles['TCL']), Paragraph('0.5x penalty', styles['TC'])]
]
gt = Table(gd, colWidths=[3.5*cm, 1.2*cm, 6*cm, 2.3*cm])
gt.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), HEADER_COLOR), ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey), ('BACKGROUND', (0, 1), (-1, -1), colors.white),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'), ('LEFTPADDING', (0, 0), (-1, -1), 4), ('RIGHTPADDING', (0, 0), (-1, -1), 4),
]))
story.append(gt)
story.append(Paragraph("Table 1: Gate Categories - If ANY gate = 0, total multiplier becomes 0.5x (PENALTY)", styles['Cap']))

story.append(Paragraph("<b>1.3 Quality Categories (0-5 each)</b>", styles['H2']))

qd = [
    [Paragraph('<b>Category</b>', styles['TH']), Paragraph('<b>Max</b>', styles['TH']), Paragraph('<b>Sub-Criteria (each 1-5)</b>', styles['TH'])],
    [Paragraph('Engagement Potential', styles['TCL']), Paragraph('5.0', styles['TC']), Paragraph('Hook Effectiveness, Call-to-Action, Structure, Conversation, Value', styles['TCL'])],
    [Paragraph('Technical Quality', styles['TCL']), Paragraph('5.0', styles['TC']), Paragraph('Language Mechanics, Formatting, Platform Optimization, Thread Flow', styles['TCL'])],
    [Paragraph('Reply Quality', styles['TCL']), Paragraph('5.0', styles['TC']), Paragraph('Relevance, Constructiveness, Authenticity, Topic Engagement', styles['TCL'])]
]
qt = Table(qd, colWidths=[3.5*cm, 1.2*cm, 8.3*cm])
qt.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), HEADER_COLOR), ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey), ('BACKGROUND', (0, 1), (-1, -1), colors.white),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'), ('LEFTPADDING', (0, 0), (-1, -1), 4),
]))
story.append(qt)
story.append(Paragraph("Table 2: Quality Categories - Average of sub-factors = final score", styles['Cap']))

story.append(Paragraph("<b>1.4 Engagement Metrics (Dynamic)</b>", styles['H2']))

ed = [
    [Paragraph('<b>Metric</b>', styles['TH']), Paragraph('<b>Driver Level</b>', styles['TH']), Paragraph('<b>Notes</b>', styles['TH'])],
    [Paragraph('Followers of Repliers', styles['TCL']), Paragraph('MAIN DRIVER', styles['TC']), Paragraph('BIGGEST contributor to temporal points!', styles['TCL'])],
    [Paragraph('Replies', styles['TCL']), Paragraph('High', styles['TC']), Paragraph('Each reply = points, log-scaled', styles['TCL'])],
    [Paragraph('Likes', styles['TCL']), Paragraph('Medium', styles['TC']), Paragraph('Each like = points, log-scaled', styles['TCL'])],
    [Paragraph('Retweets', styles['TCL']), Paragraph('Medium', styles['TC']), Paragraph('Each retweet = points, log-scaled', styles['TCL'])],
    [Paragraph('Impressions', styles['TCL']), Paragraph('Low', styles['TC']), Paragraph('Total impressions, log-scaled', styles['TCL'])]
]
et = Table(ed, colWidths=[4*cm, 2.5*cm, 6.5*cm])
et.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), HEADER_COLOR), ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey), ('BACKGROUND', (0, 1), (-1, -1), colors.white),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
]))
story.append(et)
story.append(Paragraph("Table 3: Engagement Metrics - Followers of Repliers is the KEY driver!", styles['Cap']))

story.append(PageBreak())

# ===================== PART 2: HIDDEN FACTORS =====================
story.append(Paragraph("<b>PART 2: HIDDEN FACTORS</b>", styles['H1']))
story.append(Paragraph("""
These factors are not explicitly shown in scores but significantly affect results:
""", styles['B']))

story.append(Paragraph("<b>2.1 Campaign Context</b>", styles['H2']))
story.append(Paragraph("""
<b>Campaign Type:</b>
- Open campaigns (any content) = easier to score high on gates
- Restrictive campaigns = harder to pass gates

<b>Reward Pool Size:</b>
- Larger pool = more competition = need higher relative score
- Smaller pool = less competition = easier to rank

<b>Campaign Duration:</b>
- Longer duration = more time to accumulate engagement
- Temporal points can grow over time
""", styles['B']))

story.append(Paragraph("<b>2.2 Timing Factors</b>", styles['H2']))
story.append(Paragraph("""
<b>Post Timing:</b>
- Peak hours = more initial engagement
- Off-peak = slower but potentially longer-tail engagement

<b>Day of Week:</b>
- Weekdays vs weekends affect engagement patterns

<b>Campaign Period:</b>
- Early submission = more time for engagement
- Late submission = less time, need quick engagement
""", styles['B']))

story.append(Paragraph("<b>2.3 Platform Algorithms</b>", styles['H2']))
story.append(Paragraph("""
<b>X/Twitter Algorithm:</b>
- Initial engagement velocity matters
- Replies from high-follower accounts boost visibility
- Content that triggers algorithmic boost = more impressions

<b>Content Lifespan:</b>
- Breaking news = short lifespan, high immediate engagement
- Evergreen content = longer lifespan, steady engagement
""", styles['B']))

story.append(Paragraph("<b>2.4 Content Patterns</b>", styles['H2']))
story.append(Paragraph("""
<b>Safe Patterns (High Score Probability):</b>
- Original perspective on trending topic
- Clear value proposition
- Strong hook in first line
- Explicit call-to-action
- Proper formatting (paragraphs, readability)
- Authentic voice (not AI-sounding)

<b>Risky Patterns (Low Score Probability):</b>
- Generic AI-generated content
- Copy-paste from other sources
- No clear hook or CTA
- Wall of text without breaks
- Off-topic from campaign mission
- False or unverifiable claims
""", styles['B']))

story.append(PageBreak())

# ===================== PART 3: API DISCOVERY =====================
story.append(Paragraph("<b>PART 3: API DISCOVERY</b>", styles['H1']))

story.append(Paragraph("<b>3.1 Official vs Undocumented API</b>", styles['H2']))

ad = [
    [Paragraph('<b>Endpoint</b>', styles['TH']), Paragraph('<b>Status</b>', styles['TH']), Paragraph('<b>Data Available</b>', styles['TH'])],
    [Paragraph('/api/public/stats', styles['TCL']), Paragraph('Official', styles['TC']), Paragraph('Basic platform stats only', styles['TCL'])],
    [Paragraph('/api/submissions', styles['TCL']), Paragraph('UNDOCUMENTED', styles['TC']), Paragraph('ALL submissions with REAL scores + AI analysis!', styles['TCL'])],
    [Paragraph('/api/campaigns', styles['TCL']), Paragraph('UNDOCUMENTED', styles['TC']), Paragraph('Campaign details, rewards, requirements', styles['TCL'])],
    [Paragraph('/api/leaderboard', styles['TCL']), Paragraph('UNDOCUMENTED', styles['TC']), Paragraph('User rankings with total points', styles['TCL'])]
]
at = Table(ad, colWidths=[3.5*cm, 2.5*cm, 7*cm])
at.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), HEADER_COLOR), ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey), ('BACKGROUND', (0, 1), (-1, -1), colors.white),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
]))
story.append(at)
story.append(Paragraph("Table 4: API Endpoints - Undocumented ones have REAL scoring data!", styles['Cap']))

story.append(Paragraph("<b>3.2 Response Structure</b>", styles['H2']))
story.append(Paragraph("""
{
  "id": "submission_id",
  "xUsername": "username",
  "atemporalPoints": "2430000000000000000",
  "temporalPoints": "3350857671224397000",
  "analysis": [{
    "category": "Content Alignment",
    "atto_score": "2000000000000000000",
    "atto_max_score": "2000000000000000000",
    "analysis": "The tweet aligns perfectly with the campaign..."
  }],
  "mission": {
    "title": "Mission Title",
    "description": "Mission Description",
    "rules": "Mission Rules"
  }
}
""", styles['CodeBlock']))

story.append(Paragraph("<b>3.3 API Base URLs</b>", styles['H2']))
story.append(Paragraph("""
<b>Staging:</b> https://rally-staging.vercel.app/api/
<b>Production:</b> https://rally.fun/api/ (may require authentication)
""", styles['B']))

story.append(PageBreak())

# ===================== PART 4: SCORING FORMULA =====================
story.append(Paragraph("<b>PART 4: SCORING FORMULA</b>", styles['H1']))

story.append(Paragraph("<b>4.1 Atto Format</b>", styles['H2']))
story.append(Paragraph("""
<b>Atto = 10^-18 of base unit</b>

All Rally scores are stored in atto format for precision.
Conversion: Score = atto_value / 10^18

<b>Examples:</b>
- 2000000000000000000 / 10^18 = 2.0 (max gate score)
- 5000000000000000000 / 10^18 = 5.0 (max quality score)
- 2430000000000000000 / 10^18 = 2.43 (typical high atemporal)
""", styles['B']))

story.append(Paragraph("<b>4.2 Gate Multiplier Formula</b>", styles['H2']))
story.append(Paragraph("""
<b>M_gate = 1 + 0.5 x (g_star - 1)</b>

Where g_star = average gate score normalized to 0-1 range.

<b>Multiplier Table:</b>
| Min Gate | All Gates | Multiplier |
|----------|-----------|------------|
| 0        | Any       | 0.5x (PENALTY) |
| 1        | All = 1   | 1.0x (neutral) |
| 2        | All = 2   | 1.5x (BONUS) |

<b>Critical Rule: If ANY gate = 0, multiplier = 0.5x regardless of other gates!</b>
""", styles['B']))

story.append(Paragraph("<b>4.3 Points Calculation</b>", styles['H2']))
story.append(Paragraph("""
<b>ATEMPORAL POINTS</b> (consistent over time):
Atemporal = (gate_sum / 8) x (quality_sum / 15) x 2.5
Cap: approximately 2.43 for perfect scores

<b>TEMPORAL POINTS</b> (changes with engagement):
Temporal = 1.12 + log10(likes+1) x 0.18
                + log10(replies+1) x 0.22
                + log10(retweets+1) x 0.15
                + log10(impressions+1) x 0.025
                + log10(followers+1) x 0.41

<b>KEY INSIGHT: Followers of Repliers is the MAIN DRIVER!</b>
- log10(15784) x 0.41 = 1.72 extra temporal points
- log10(1) x 0.41 = 0 extra temporal points

<b>TOTAL POINTS:</b>
Total = Atemporal + Temporal
""", styles['B']))

story.append(Paragraph("<b>4.4 Grade System</b>", styles['H2']))

grd = [
    [Paragraph('<b>Points</b>', styles['TH']), Paragraph('<b>Grade</b>', styles['TH']), Paragraph('<b>Label</b>', styles['TH']), Paragraph('<b>Points</b>', styles['TH']), Paragraph('<b>Grade</b>', styles['TH']), Paragraph('<b>Label</b>', styles['TH'])],
    [Paragraph('6.0+', styles['TC']), Paragraph('S+', styles['TC']), Paragraph('Exceptional', styles['TC']), Paragraph('3.5-3.99', styles['TC']), Paragraph('B', styles['TC']), Paragraph('Above Avg', styles['TC'])],
    [Paragraph('5.5-5.99', styles['TC']), Paragraph('S', styles['TC']), Paragraph('Outstanding', styles['TC']), Paragraph('3.0-3.49', styles['TC']), Paragraph('C+', styles['TC']), Paragraph('Average', styles['TC'])],
    [Paragraph('5.0-5.49', styles['TC']), Paragraph('A+', styles['TC']), Paragraph('Excellent', styles['TC']), Paragraph('2.0-2.99', styles['TC']), Paragraph('C', styles['TC']), Paragraph('Below Avg', styles['TC'])],
    [Paragraph('4.5-4.99', styles['TC']), Paragraph('A', styles['TC']), Paragraph('Very Good', styles['TC']), Paragraph('< 2.0', styles['TC']), Paragraph('D/F', styles['TC']), Paragraph('Poor/Fail', styles['TC'])],
    [Paragraph('4.0-4.49', styles['TC']), Paragraph('B+', styles['TC']), Paragraph('Good', styles['TC']), Paragraph('', styles['TC']), Paragraph('', styles['TC']), Paragraph('', styles['TC'])]
]
grt = Table(grd, colWidths=[2*cm, 1.5*cm, 2.5*cm, 2*cm, 1.5*cm, 2.5*cm])
grt.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), HEADER_COLOR), ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey), ('BACKGROUND', (0, 1), (-1, -1), colors.white),
    ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
]))
story.append(grt)
story.append(Paragraph("Table 5: Grade System", styles['Cap']))

story.append(PageBreak())

# ===================== PART 5: AI ANALYSIS PATTERNS =====================
story.append(Paragraph("<b>PART 5: AI ANALYSIS PATTERNS</b>", styles['H1']))
story.append(Paragraph("""
Rally uses multi-LLM validators that provide detailed analysis. Learn these patterns:
""", styles['B']))

story.append(Paragraph("<b>5.1 Content Alignment Analysis</b>", styles['H2']))
story.append(Paragraph("""
<b>Pattern:</b>
1. Reference Campaign: "The tweet aligns with 'Campaign Name' guidelines..."
2. Evaluate Mission: Check if content meets campaign mission
3. Evaluate Style: "Since the campaign style is..."
4. Conclusion: "this content meets/does not meet criteria"

<b>Real Example:</b>
"The tweet aligns perfectly with the 'Staging Test Campaign Mar 02' guidelines. 
The campaign mission is explicitly broad, stating 'Post Anything', 'Share any tweet', 
and 'Any tweet is accepted'. The content provides a detailed critique of AI incumbents 
versus AI-native labs. Since the campaign style is 'Any' and the knowledge base is 
'Anything goes', this long-form analysis meets all criteria for acceptance."
""", styles['B']))

story.append(Paragraph("<b>5.2 Engagement Potential Analysis</b>", styles['H2']))
story.append(Paragraph("""
<b>5 Sub-factors (each 1-5):</b>
1. Hook Effectiveness: How strong is the opening?
2. Call-to-Action Quality: Is there a clear CTA?
3. Content Structure: Is it well-organized?
4. Conversation Potential: Will it spark discussion?
5. Value Delivery: What value does audience get?

<b>Real Example:</b>
"The tweet features a strong contrarian hook that challenges the common narrative 
of incumbent dominance. It utilizes high-profile examples (Microsoft, Google, Figma, Meta) 
to anchor its critique, which typically drives high engagement. However, it lacks 
a clear call-to-action (CTA), limiting engagement potential. The content structure 
is solid, moving from premise to evidence to conclusion."
""", styles['B']))

story.append(Paragraph("<b>5.3 Technical Quality Analysis</b>", styles['H2']))
story.append(Paragraph("""
<b>4 Sub-factors (each 1-5):</b>
1. Language Mechanics: Grammar, spelling, punctuation
2. Structure & Formatting: Paragraph breaks, readability
3. Platform Optimization: Character limits, thread structure
4. Thread Composition: Logical flow between tweets

<b>Real Example:</b>
"The tweet demonstrates high technical proficiency. Language mechanics are excellent, 
with correct grammar and clean punctuation throughout. The structure is highly readable, 
utilizing short paragraphs and distinct line breaks to separate complex ideas. 
It effectively leverages the platform's long-form capabilities (1,699 characters) 
to present a nuanced argument."
""", styles['B']))

story.append(Paragraph("<b>5.4 Reply Quality Analysis</b>", styles['H2']))
story.append(Paragraph("""
<b>4 Sub-factors (each 1-5):</b>
1. Relevance: Are replies on-topic?
2. Constructiveness: Do replies add value?
3. Authenticity: Are replies genuine vs generic?
4. Topic Engagement: Do repliers understand the topic?

<b>Real Example:</b>
"The replies show strong relevance, engaging directly with the tweet's theme 
of unconventional learning methods. The first reply offers a structural argument 
about Google's ad-revenue conflict, demonstrating genuine discourse. However, 
some filler responses prevent a perfect score. Overall, the presence of specific, 
reasoned arguments justifies a higher score."
""", styles['B']))

story.append(PageBreak())

# ===================== PART 6: REAL DATA ANALYSIS =====================
story.append(Paragraph("<b>PART 6: REAL DATA ANALYSIS</b>", styles['H1']))

story.append(Paragraph("<b>6.1 Submission Scores from Rally API</b>", styles['H2']))

sd = [
    [Paragraph('<b>#</b>', styles['TH']), Paragraph('<b>Gates</b>', styles['TH']), Paragraph('<b>Quality</b>', styles['TH']), Paragraph('<b>Atemp</b>', styles['TH']), Paragraph('<b>Temp</b>', styles['TH']), Paragraph('<b>Total</b>', styles['TH']), Paragraph('<b>Grade</b>', styles['TH'])],
    [Paragraph('1', styles['TC']), Paragraph('8/8', styles['TC']), Paragraph('13/15', styles['TC']), Paragraph('2.43', styles['TC']), Paragraph('3.35', styles['TC']), Paragraph('5.78', styles['TC']), Paragraph('S', styles['TC'])],
    [Paragraph('2', styles['TC']), Paragraph('8/8', styles['TC']), Paragraph('11/15', styles['TC']), Paragraph('1.89', styles['TC']), Paragraph('3.30', styles['TC']), Paragraph('5.19', styles['TC']), Paragraph('A+', styles['TC'])],
    [Paragraph('3', styles['TC']), Paragraph('8/8', styles['TC']), Paragraph('12/15', styles['TC']), Paragraph('2.43', styles['TC']), Paragraph('2.66', styles['TC']), Paragraph('5.09', styles['TC']), Paragraph('A+', styles['TC'])],
    [Paragraph('4', styles['TC']), Paragraph('8/8', styles['TC']), Paragraph('14/15', styles['TC']), Paragraph('2.43', styles['TC']), Paragraph('1.62', styles['TC']), Paragraph('4.05', styles['TC']), Paragraph('B+', styles['TC'])],
    [Paragraph('5', styles['TC']), Paragraph('7/8', styles['TC']), Paragraph('13/15', styles['TC']), Paragraph('2.16', styles['TC']), Paragraph('1.62', styles['TC']), Paragraph('3.78', styles['TC']), Paragraph('B', styles['TC'])],
    [Paragraph('6', styles['TC']), Paragraph('8/8', styles['TC']), Paragraph('12/15', styles['TC']), Paragraph('1.89', styles['TC']), Paragraph('1.83', styles['TC']), Paragraph('3.72', styles['TC']), Paragraph('B', styles['TC'])]
]
st = Table(sd, colWidths=[0.8*cm, 1.5*cm, 2*cm, 1.8*cm, 1.8*cm, 1.8*cm, 1.5*cm])
st.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), HEADER_COLOR), ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey), ('BACKGROUND', (0, 1), (-1, -1), colors.white),
    ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
]))
story.append(st)
story.append(Paragraph("Table 6: Real Rally Submission Scores from API", styles['Cap']))

story.append(Paragraph("<b>6.2 Pattern Insights</b>", styles['H2']))
story.append(Paragraph("""
<b>Key Findings:</b>

1. <b>Gate Scores:</b> Almost all 8/8 because test campaign is permissive
   - For restrictive campaigns, gate compliance is much more critical

2. <b>Quality Scores:</b> Range 11-14/15 shows content quality variation
   - Engagement Potential often differentiates high vs low scores

3. <b>Temporal Driver:</b> Followers of Repliers is the MAIN driver!
   - Submission #1: 15,783 followers → 3.35 temporal (HIGH)
   - Submission #4: 0 followers → 1.62 temporal (LOW)
   - Difference of 1.73 points just from followers!

4. <b>Correlation:</b>
   - Atemporal correlates with Gate + Quality scores
   - Temporal correlates with Engagement metrics (especially Followers)
""", styles['B']))

story.append(Paragraph("<b>6.3 Score Calculation Example</b>", styles['H2']))
story.append(Paragraph("""
<b>Submission #1 Breakdown:</b>

Gates: 8/8 → gate_factor = 1.0, multiplier = 1.5x
Quality: 13/15 → quality_factor = 0.867

Atemporal = 1.0 x 0.867 x 2.5 = 2.17 (capped to ~2.43 observed)
Temporal = 1.12 + log10(15)×0.18 + log10(3)×0.22 + log10(15784)×0.41
         = 1.12 + 0.21 + 0.10 + 1.72 = 3.15 (observed: 3.35)

Total = 2.43 + 3.35 = 5.78 → Grade S
""", styles['B']))

story.append(PageBreak())

# ===================== PART 7: CONTENT PATTERNS =====================
story.append(Paragraph("<b>PART 7: CONTENT PATTERNS</b>", styles['H1']))

story.append(Paragraph("<b>7.1 Safe Patterns (High Score Probability)</b>", styles['H2']))
story.append(Paragraph("""
<b>Originality:</b>
- Unique perspective on trending topic
- Personal experience or insight
- Contrarian but well-reasoned take

<b>Engagement:</b>
- Strong hook in first 2-3 words
- Clear call-to-action (question, challenge, invitation)
- Structured with paragraph breaks
- High value content (bookmark-worthy)

<b>Technical:</b>
- Correct grammar and spelling
- Platform-optimized formatting
- Appropriate use of media
- Logical flow and structure

<b>Authenticity:</b>
- Natural, conversational tone
- Avoid AI patterns: em dashes in titles, "In the world of", "Picture this"
- Personal voice and style
- Specific examples and details
""", styles['B']))

story.append(Paragraph("<b>7.2 Risky Patterns (Low Score Probability)</b>", styles['H2']))
story.append(Paragraph("""
<b>Originality Issues:</b>
- Copy-paste from other sources
- Generic AI-generated content
- Spam or repetitive content

<b>Engagement Issues:</b>
- No clear hook
- Missing call-to-action
- Wall of text without breaks
- Low value content

<b>Technical Issues:</b>
- Grammar and spelling errors
- Poor formatting
- Not platform-optimized
- Disorganized structure

<b>Authenticity Issues:</b>
- AI-sounding language
- Generic phrases and templates
- Lack of personal voice
- Vague or unspecific claims
""", styles['B']))

story.append(Paragraph("<b>7.3 Example: Good vs Bad Content</b>", styles['H2']))
story.append(Paragraph("""
<b>GOOD (Expected: Gate 8/8, Quality 13+/15):</b>
"Unpopular opinion: Microsoft Copilot isn't bad because it's AI. 
It's bad because it's AI built by a company that optimizes for 
enterprise sales, not user experience.

Here's what AI-native labs get right that incumbents miss:
1. Speed over feature bloat
2. User feedback loops
3. Risk-taking on new paradigms

What do you think separates great AI products from the rest?"

<b>BAD (Expected: Gate 4-6/8, Quality 8-10/15):</b>
"In the world of AI, there are many tools available. 
AI is transforming how we work. AI tools can help productivity.
Consider using AI for your business needs."
""", styles['B']))

story.append(PageBreak())

# ===================== PART 8: IMPLEMENTATION =====================
story.append(Paragraph("<b>PART 8: IMPLEMENTATION</b>", styles['H1']))

story.append(Paragraph("<b>8.1 Score Optimization Tips</b>", styles['H2']))
story.append(Paragraph("""
<b>PRIORITY 1: Gate Scores (CRITICAL)</b>
- Ensure ALL gates = 2 for 1.5x multiplier
- Read campaign guidelines carefully
- Use exact hashtags/mentions required
- Verify information accuracy
- Create original content

<b>PRIORITY 2: Quality Scores</b>
- Strong hook (contrarian, surprising, emotional)
- Clear CTA (question, challenge, invitation)
- Good structure (paragraph breaks, bullet points)
- High-value insight (bookmark-worthy)
- Perfect grammar and formatting

<b>PRIORITY 3: Engagement</b>
- Target replies from high-follower users
- Create controversial/debate content
- Post when audience is active
- Respond to replies to boost engagement
""", styles['B']))

story.append(Paragraph("<b>8.2 Pre-Submit Checklist</b>", styles['H2']))
story.append(Paragraph("""
[ ] Content 100% aligned with campaign mission
[ ] All required hashtags/mentions present
[ ] No false or unverified claims
[ ] Original content (not copy-paste)
[ ] Strong hook in first 2-3 words
[ ] Clear call-to-action
[ ] Paragraph breaks for readability
[ ] Correct grammar and spelling
[ ] Platform-optimized formatting
[ ] Good posting timing
[ ] Ready to engage with replies
""", styles['B']))

story.append(Paragraph("<b>8.3 API Calibration</b>", styles['H2']))
story.append(Paragraph("""
Use Rally API to calibrate your scoring:

1. <b>Fetch data:</b> GET /api/submissions for real scoring patterns
2. <b>Analyze:</b> Study AI analysis text for evaluator criteria
3. <b>Compare:</b> Your predictions vs actual scores
4. <b>Adjust:</b> Fine-tune your scoring model based on deviations

<b>API Endpoints:</b>
- https://rally-staging.vercel.app/api/submissions
- https://rally-staging.vercel.app/api/campaigns

<b>Note:</b> Staging environment may have different scores than production.
""", styles['B']))

# ===================== SUMMARY =====================
story.append(Spacer(1, 20))
story.append(Paragraph("<b>SUMMARY</b>", styles['H2']))
story.append(Paragraph("""
<b>Key Takeaways:</b>

1. Gate scores determine acceptance and multiplier (0.5x to 1.5x)
2. Quality scores determine atemporal points
3. Engagement (especially Followers of Repliers) determines temporal points
4. Total = Atemporal + Temporal
5. Use this guide + API data to predict and optimize scores

<b>For AI analyzing content with this PDF:</b>
- Follow the scoring rules in Part 0
- Apply the formulas in Part 4
- Use patterns from Part 5-7
- Validate with real data from Part 6

This guide enables accurate Rally score prediction and content optimization!
""", styles['B']))

# Build PDF
doc.build(story)
print("Complete PDF generated successfully!")
print(f"Location: /home/z/my-project/public/rally-complete-guide.pdf")
