from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.lib.units import inch, cm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily
import os

# Register fonts
pdfmetrics.registerFont(TTFont('SimHei', '/usr/share/fonts/truetype/chinese/SimHei.ttf'))
pdfmetrics.registerFont(TTFont('Microsoft YaHei', '/usr/share/fonts/truetype/chinese/msyh.ttf'))
pdfmetrics.registerFont(TTFont('Times New Roman', '/usr/share/fonts/truetype/english/Times-New-Roman.ttf'))

registerFontFamily('SimHei', normal='SimHei', bold='SimHei')
registerFontFamily('Microsoft YaHei', normal='Microsoft YaHei', bold='Microsoft YaHei')
registerFontFamily('Times New Roman', normal='Times New Roman', bold='Times New Roman')

# Create document
output_path = "/home/z/my-project/download/Rally_Workflow_V4.0_Universal.pdf"
doc = SimpleDocTemplate(output_path, pagesize=A4, 
                        topMargin=1.5*cm, bottomMargin=1.5*cm,
                        leftMargin=1.5*cm, rightMargin=1.5*cm,
                        title="Rally_Workflow_V4.0_Universal",
                        author="Z.ai",
                        creator="Z.ai",
                        subject="Rally Universal Workflow Guide V4.0")

styles = getSampleStyleSheet()

# Define styles
title_style = ParagraphStyle(
    name='Title',
    fontName='Microsoft YaHei',
    fontSize=28,
    leading=36,
    alignment=TA_CENTER,
    spaceAfter=12
)

subtitle_style = ParagraphStyle(
    name='Subtitle',
    fontName='SimHei',
    fontSize=14,
    leading=20,
    alignment=TA_CENTER,
    spaceAfter=6
)

h1_style = ParagraphStyle(
    name='H1',
    fontName='Microsoft YaHei',
    fontSize=16,
    leading=22,
    alignment=TA_LEFT,
    spaceBefore=18,
    spaceAfter=12,
    textColor=colors.HexColor('#1F4E79')
)

h2_style = ParagraphStyle(
    name='H2',
    fontName='Microsoft YaHei',
    fontSize=13,
    leading=18,
    alignment=TA_LEFT,
    spaceBefore=12,
    spaceAfter=8,
    textColor=colors.HexColor('#2E75B6')
)

body_style = ParagraphStyle(
    name='Body',
    fontName='SimHei',
    fontSize=10,
    leading=16,
    alignment=TA_LEFT,
    spaceAfter=6,
    wordWrap='CJK'
)

body_en_style = ParagraphStyle(
    name='BodyEN',
    fontName='Times New Roman',
    fontSize=10,
    leading=16,
    alignment=TA_LEFT,
    spaceAfter=6
)

bullet_style = ParagraphStyle(
    name='Bullet',
    fontName='SimHei',
    fontSize=10,
    leading=16,
    alignment=TA_LEFT,
    leftIndent=20,
    spaceAfter=4,
    wordWrap='CJK'
)

code_style = ParagraphStyle(
    name='Code',
    fontName='Times New Roman',
    fontSize=9,
    leading=14,
    alignment=TA_LEFT,
    leftIndent=10,
    spaceAfter=4,
    backColor=colors.HexColor('#F5F5F5')
)

table_header_style = ParagraphStyle(
    name='TableHeader',
    fontName='Microsoft YaHei',
    fontSize=9,
    leading=12,
    alignment=TA_CENTER,
    textColor=colors.white,
    wordWrap='CJK'
)

table_cell_style = ParagraphStyle(
    name='TableCell',
    fontName='SimHei',
    fontSize=9,
    leading=12,
    alignment=TA_CENTER,
    wordWrap='CJK'
)

table_cell_left_style = ParagraphStyle(
    name='TableCellLeft',
    fontName='SimHei',
    fontSize=9,
    leading=12,
    alignment=TA_LEFT,
    wordWrap='CJK'
)

story = []

# Cover Page
story.append(Spacer(1, 3*cm))
story.append(Paragraph("RALLY WORKFLOW V4.0", title_style))
story.append(Paragraph("UNIVERSAL EDITION", title_style))
story.append(Spacer(1, 1*cm))
story.append(Paragraph("Master Guide untuk Semua Campaign Rally", subtitle_style))
story.append(Paragraph("Efektivitas: 95-100%", subtitle_style))
story.append(Spacer(1, 2*cm))
story.append(Paragraph("Key Features:", h2_style))
story.append(Paragraph("★ FR (Followers of Repliers) Cheat Code Strategy", bullet_style))
story.append(Paragraph("★ Metric Weights Detection Module", bullet_style))
story.append(Paragraph("★ Gate Multiplier Optimization", bullet_style))
story.append(Paragraph("★ Impressions: Displayed but NOT Calculated", bullet_style))
story.append(Paragraph("★ Viral Mechanics Integration", bullet_style))
story.append(Spacer(1, 3*cm))
story.append(Paragraph("Generated by Z.ai", subtitle_style))
story.append(PageBreak())

# Section 1: V4.0 Key Upgrades
story.append(Paragraph("1. V4.0 KEY UPGRADES", h1_style))
story.append(Paragraph("Berdasarkan dokumentasi resmi Rally dan analisis mendalam:", body_style))
story.append(Spacer(1, 8))

upgrades_data = [
    [Paragraph('<b>#</b>', table_header_style), Paragraph('<b>Feature</b>', table_header_style), Paragraph('<b>Description</b>', table_header_style)],
    [Paragraph('1', table_cell_style), Paragraph('METRIC WEIGHTS CUSTOMIZABLE', table_cell_left_style), Paragraph('Setiap campaign memiliki weights berbeda (0-1). HARUS cek API untuk mengetahui prioritas metrik.', table_cell_left_style)],
    [Paragraph('2', table_cell_style), Paragraph('FR = CHEAT CODE', table_cell_left_style), Paragraph('1 reply dari akun 100K = log(100001) = 5.0, SAMA dengan 100,000 likes/retweets!', table_cell_left_style)],
    [Paragraph('3', table_cell_style), Paragraph('IMPRESSIONS NOT CALCULATED', table_cell_left_style), Paragraph('Tampil di UI dari Twitter API, TIDAK masuk 11 metrik scoring. Jangan optimization untuk impressions.', table_cell_left_style)],
    [Paragraph('4', table_cell_style), Paragraph('GATE MULTIPLIER FORMULA', table_cell_left_style), Paragraph('M_gate = 1 + 0.5 x (g_star - 1). Max = 1.5x (jika semua gate 2/2), Min = 0.5x.', table_cell_left_style)],
    [Paragraph('5', table_cell_style), Paragraph('REFERRAL BONUS SYSTEM', table_cell_left_style), Paragraph('10% dari Access Points langsung + 10% dari Campaign Points FOREVER. Menjelaskan "zero engagement top 1".', table_cell_left_style)],
]

t = Table(upgrades_data, colWidths=[1*cm, 4*cm, 11*cm])
t.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('BACKGROUND', (0, 1), (-1, 1), colors.white),
    ('BACKGROUND', (0, 2), (-1, 2), colors.HexColor('#F5F5F5')),
    ('BACKGROUND', (0, 3), (-1, 3), colors.white),
    ('BACKGROUND', (0, 4), (-1, 4), colors.HexColor('#F5F5F5')),
    ('BACKGROUND', (0, 5), (-1, 5), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(t)
story.append(Spacer(1, 18))

# Section 2: 11 Metrik Resmi Rally
story.append(Paragraph("2. 11 METRIK RESMI RALLY", h1_style))

story.append(Paragraph("2.1 GATES (4 Metrik, Wajib PASS Semua)", h2_style))
gates_data = [
    [Paragraph('<b>Gate</b>', table_header_style), Paragraph('<b>Score Range</b>', table_header_style), Paragraph('<b>Description</b>', table_header_style)],
    [Paragraph('G1: Content Alignment', table_cell_left_style), Paragraph('0-2', table_cell_style), Paragraph('Kesesuaian dengan campaign message, brand consistency, target audience fit', table_cell_left_style)],
    [Paragraph('G2: Information Accuracy', table_cell_left_style), Paragraph('0-2', table_cell_style), Paragraph('Akurasi fakta, technical accuracy, consistency with official materials', table_cell_left_style)],
    [Paragraph('G3: Campaign Compliance', table_cell_left_style), Paragraph('0-2', table_cell_style), Paragraph('Compliance requirements: hashtags, mentions, format, style guidelines', table_cell_left_style)],
    [Paragraph('G4: Originality & Authenticity', table_cell_left_style), Paragraph('0-2', table_cell_style), Paragraph('Keunikan, fresh perspective, personal insights, natural language', table_cell_left_style)],
]
t2 = Table(gates_data, colWidths=[5*cm, 2.5*cm, 8.5*cm])
t2.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('BACKGROUND', (0, 1), (-1, -1), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(t2)
story.append(Spacer(1, 12))

story.append(Paragraph("2.2 QUALITY METRICS (2 Metrik, 0-5 Scale)", h2_style))
quality_data = [
    [Paragraph('<b>Metric</b>', table_header_style), Paragraph('<b>Score</b>', table_header_style), Paragraph('<b>Evaluation Criteria</b>', table_header_style)],
    [Paragraph('EP: Engagement Potential', table_cell_left_style), Paragraph('0-5', table_cell_style), Paragraph('Hook effectiveness, call-to-action quality, content structure, conversation potential', table_cell_left_style)],
    [Paragraph('TQ: Technical Quality', table_cell_left_style), Paragraph('0-5', table_cell_style), Paragraph('Grammar and spelling, formatting and structure, platform optimization', table_cell_left_style)],
]
t3 = Table(quality_data, colWidths=[5*cm, 2.5*cm, 8.5*cm])
t3.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('BACKGROUND', (0, 1), (-1, -1), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(t3)
story.append(Spacer(1, 12))

story.append(Paragraph("2.3 ENGAGEMENT METRICS (5 Metrik, Dynamic)", h2_style))
engagement_data = [
    [Paragraph('<b>Metric</b>', table_header_style), Paragraph('<b>Formula</b>', table_header_style), Paragraph('<b>Notes</b>', table_header_style)],
    [Paragraph('RT: Retweets', table_cell_left_style), Paragraph('log(RT+1)', table_cell_style), Paragraph('Amplification of the message', table_cell_left_style)],
    [Paragraph('LK: Likes', table_cell_left_style), Paragraph('log(LK+1)', table_cell_style), Paragraph('Audience appreciation', table_cell_left_style)],
    [Paragraph('RP: Replies', table_cell_left_style), Paragraph('log(RP+1)', table_cell_style), Paragraph('Conversation generation', table_cell_left_style)],
    [Paragraph('QR: Quality of Replies', table_cell_left_style), Paragraph('AI Score 0-1', table_cell_style), Paragraph('Relevance, civility, informativeness', table_cell_left_style)],
    [Paragraph('FR: Followers of Repliers', table_cell_left_style), Paragraph('log(Total+1)', table_cell_style), Paragraph('CHEAT CODE - Reach of engaged audience', table_cell_left_style)],
]
t4 = Table(engagement_data, colWidths=[5*cm, 3.5*cm, 7.5*cm])
t4.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('BACKGROUND', (0, 1), (-1, -1), colors.white),
    ('BACKGROUND', (0, 5), (-1, 5), colors.HexColor('#FFF3CD')),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(t4)
story.append(Spacer(1, 8))
story.append(Paragraph("IMPRESSONS = TIDAK DIHITUNG (hanya tampil di UI dari Twitter API)", body_style))
story.append(PageBreak())

# Section 3: FR Cheat Code
story.append(Paragraph("3. FR (FOLLOWERS OF REPLIERS) CHEAT CODE", h1_style))
story.append(Paragraph("FR adalah metrik PALING POWERFUL karena menggunakan formula log-scale:", body_style))
story.append(Spacer(1, 8))

story.append(Paragraph("Formula: FR = log(Sum of Followers of All Repliers + 1)", code_style))
story.append(Spacer(1, 12))

story.append(Paragraph("3.1 Contoh Kalkulasi FR", h2_style))
fr_data = [
    [Paragraph('<b>Scenario</b>', table_header_style), Paragraph('<b>Total Followers</b>', table_header_style), Paragraph('<b>FR Score</b>', table_header_style), Paragraph('<b>Equivalent</b>', table_header_style)],
    [Paragraph('1 reply dari akun 100K', table_cell_left_style), Paragraph('100,000', table_cell_style), Paragraph('log(100001) = 5.0', table_cell_style), Paragraph('= 100,000 likes', table_cell_left_style)],
    [Paragraph('10 replies dari akun 10K each', table_cell_left_style), Paragraph('100,000', table_cell_style), Paragraph('log(100001) = 5.0', table_cell_style), Paragraph('= 100,000 RTs', table_cell_left_style)],
    [Paragraph('1 reply dari akun 1M', table_cell_left_style), Paragraph('1,000,000', table_cell_style), Paragraph('log(1000001) = 6.0', table_cell_style), Paragraph('= 1,000,000 likes', table_cell_left_style)],
    [Paragraph('100 replies dari akun 100 each', table_cell_left_style), Paragraph('10,000', table_cell_style), Paragraph('log(10001) = 4.0', table_cell_style), Paragraph('= 10,000 likes', table_cell_left_style)],
]
t5 = Table(fr_data, colWidths=[5*cm, 3.5*cm, 4*cm, 3.5*cm])
t5.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('BACKGROUND', (0, 1), (-1, 1), colors.white),
    ('BACKGROUND', (0, 2), (-1, 2), colors.HexColor('#F5F5F5')),
    ('BACKGROUND', (0, 3), (-1, 3), colors.white),
    ('BACKGROUND', (0, 4), (-1, 4), colors.HexColor('#F5F5F5')),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(t5)
story.append(Spacer(1, 8))
story.append(Paragraph("INSIGHT: 1 reply dari influencer > 100 replies dari akun kecil!", body_style))
story.append(Spacer(1, 12))

story.append(Paragraph("3.2 FR Optimization Strategies", h2_style))
fr_strat_data = [
    [Paragraph('<b>Strategy</b>', table_header_style), Paragraph('<b>Implementation</b>', table_header_style), Paragraph('<b>Expected FR Boost</b>', table_header_style)],
    [Paragraph('HIGH-FOLLOWER REPLY BAIT', table_cell_left_style), Paragraph('Mention influencers directly, challenge conventional wisdom', table_cell_left_style), Paragraph('+300%', table_cell_style)],
    [Paragraph('THREAD JACKING', table_cell_left_style), Paragraph('Reply ke thread influencers dengan value-adding comment', table_cell_left_style), Paragraph('+200%', table_cell_style)],
    [Paragraph('CONTROVERSY ANGLE', table_cell_left_style), Paragraph('"Unpopular opinion:", "Change my mind:", Hot takes', table_cell_left_style), Paragraph('+250%', table_cell_style)],
    [Paragraph('COMMUNITY ENGAGEMENT', table_cell_left_style), Paragraph('Membangun hubungan dengan akun medium (10K-100K)', table_cell_left_style), Paragraph('+150%', table_cell_style)],
]
t6 = Table(fr_strat_data, colWidths=[5*cm, 7*cm, 4*cm])
t6.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('BACKGROUND', (0, 1), (-1, 1), colors.white),
    ('BACKGROUND', (0, 2), (-1, 2), colors.HexColor('#F5F5F5')),
    ('BACKGROUND', (0, 3), (-1, 3), colors.white),
    ('BACKGROUND', (0, 4), (-1, 4), colors.HexColor('#F5F5F5')),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(t6)
story.append(Spacer(1, 12))

story.append(Paragraph("3.3 FR-Optimized Tweet Templates", h2_style))
story.append(Paragraph("TEMPLATE 1 - Influencer Mention:", body_style))
story.append(Paragraph('"@[influencer] called this [time] ago. [Key insight from KB]. Now everyone\'s paying attention. Your take?"', code_style))
story.append(Spacer(1, 6))
story.append(Paragraph("TEMPLATE 2 - Controversy:", body_style))
story.append(Paragraph('"unpopular opinion: [common belief] is wrong. Here\'s what the data actually shows: [Facts from KB]. Change my mind. I dare you."', code_style))
story.append(Spacer(1, 6))
story.append(Paragraph("TEMPLATE 3 - Challenge:", body_style))
story.append(Paragraph('"95% of [audience] get this wrong. [Facts from KB]. Which camp are you in? [A] or [B]? Reply below"', code_style))
story.append(PageBreak())

# Section 4: Gate Multiplier
story.append(Paragraph("4. GATE MULTIPLIER FORMULA", h1_style))
story.append(Paragraph("Formula: M_gate = 1 + 0.5 x (g_star - 1)", code_style))
story.append(Paragraph("Dimana g_star = average dari 4 gate scores (G1, G2, G3, G4)", body_style))
story.append(Spacer(1, 12))

gate_mult_data = [
    [Paragraph('<b>Gate Scores</b>', table_header_style), Paragraph('<b>g_star</b>', table_header_style), Paragraph('<b>M_gate</b>', table_header_style), Paragraph('<b>Effect</b>', table_header_style)],
    [Paragraph('All 2/2', table_cell_left_style), Paragraph('2.0', table_cell_style), Paragraph('1.5x', table_cell_style), Paragraph('MAXIMUM BONUS', table_cell_left_style)],
    [Paragraph('All 1.5/2', table_cell_left_style), Paragraph('1.5', table_cell_style), Paragraph('1.25x', table_cell_style), Paragraph('GOOD BONUS', table_cell_left_style)],
    [Paragraph('All 1/2', table_cell_left_style), Paragraph('1.0', table_cell_style), Paragraph('1.0x', table_cell_style), Paragraph('BASELINE', table_cell_left_style)],
    [Paragraph('Mixed 1-2', table_cell_left_style), Paragraph('~1.5', table_cell_style), Paragraph('~1.25x', table_cell_style), Paragraph('PARTIAL', table_cell_left_style)],
    [Paragraph('Any 0/2', table_cell_left_style), Paragraph('N/A', table_cell_style), Paragraph('FAIL', table_cell_style), Paragraph('DISQUALIFIED', table_cell_left_style)],
]
t7 = Table(gate_mult_data, colWidths=[4*cm, 3*cm, 3*cm, 6*cm])
t7.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('BACKGROUND', (0, 1), (-1, 1), colors.HexColor('#D4EDDA')),
    ('BACKGROUND', (0, 2), (-1, 2), colors.white),
    ('BACKGROUND', (0, 3), (-1, 3), colors.HexColor('#F5F5F5')),
    ('BACKGROUND', (0, 4), (-1, 4), colors.white),
    ('BACKGROUND', (0, 5), (-1, 5), colors.HexColor('#F8D7DA')),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(t7)
story.append(Spacer(1, 12))
story.append(Paragraph("TARGET: Semua gates 2/2 untuk M_gate = 1.5x (MAXIMUM BONUS)", body_style))
story.append(PageBreak())

# Section 5: Metric Weights Detection
story.append(Paragraph("5. METRIC WEIGHTS DETECTION", h1_style))
story.append(Paragraph("Setiap campaign memiliki metricWeights berbeda. Cek via API:", body_style))
story.append(Spacer(1, 8))
story.append(Paragraph("API Endpoint: https://app.rally.fun/api/campaigns/{campaignAddress}", code_style))
story.append(Spacer(1, 12))

story.append(Paragraph("5.1 Contoh: Fragments Campaign", h2_style))
weights_data = [
    [Paragraph('<b>Index</b>', table_header_style), Paragraph('<b>Metric</b>', table_header_style), Paragraph('<b>Weight</b>', table_header_style), Paragraph('<b>Priority</b>', table_header_style)],
    [Paragraph('0', table_cell_style), Paragraph('EP (Engagement Potential)', table_cell_left_style), Paragraph('0.9', table_cell_style), Paragraph('HIGHEST', table_cell_style)],
    [Paragraph('1', table_cell_style), Paragraph('TQ (Technical Quality)', table_cell_left_style), Paragraph('0.9', table_cell_style), Paragraph('HIGHEST', table_cell_style)],
    [Paragraph('2', table_cell_style), Paragraph('RT (Retweets)', table_cell_left_style), Paragraph('0.5', table_cell_style), Paragraph('MEDIUM', table_cell_style)],
    [Paragraph('3', table_cell_style), Paragraph('LK (Likes)', table_cell_left_style), Paragraph('0.5', table_cell_style), Paragraph('MEDIUM', table_cell_style)],
    [Paragraph('4', table_cell_style), Paragraph('RP (Replies)', table_cell_left_style), Paragraph('0.5', table_cell_style), Paragraph('MEDIUM', table_cell_style)],
    [Paragraph('5', table_cell_style), Paragraph('QR (Quality of Replies)', table_cell_left_style), Paragraph('0.5', table_cell_style), Paragraph('MEDIUM', table_cell_style)],
    [Paragraph('6', table_cell_style), Paragraph('FR (Followers of Repliers)', table_cell_left_style), Paragraph('0.5', table_cell_style), Paragraph('MEDIUM', table_cell_style)],
    [Paragraph('7', table_cell_style), Paragraph('??? (Unknown/Bonus)', table_cell_left_style), Paragraph('0.9', table_cell_style), Paragraph('HIGHEST', table_cell_style)],
]
t8 = Table(weights_data, colWidths=[2*cm, 6*cm, 3*cm, 5*cm])
t8.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('BACKGROUND', (0, 1), (-1, 1), colors.HexColor('#D4EDDA')),
    ('BACKGROUND', (0, 2), (-1, 2), colors.HexColor('#D4EDDA')),
    ('BACKGROUND', (0, 3), (-1, 3), colors.white),
    ('BACKGROUND', (0, 4), (-1, 4), colors.HexColor('#F5F5F5')),
    ('BACKGROUND', (0, 5), (-1, 5), colors.white),
    ('BACKGROUND', (0, 6), (-1, 6), colors.HexColor('#F5F5F5')),
    ('BACKGROUND', (0, 7), (-1, 7), colors.white),
    ('BACKGROUND', (0, 8), (-1, 8), colors.HexColor('#FFF3CD')),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(t8)
story.append(Spacer(1, 12))

story.append(Paragraph("5.2 Strategy Berdasarkan Weights", h2_style))
strat_data = [
    [Paragraph('<b>Weight Pattern</b>', table_header_style), Paragraph('<b>Strategy Focus</b>', table_header_style)],
    [Paragraph('EP/TQ high (0.9)', table_cell_left_style), Paragraph('Quality over quantity, perfect execution, maximize hook quality', table_cell_left_style)],
    [Paragraph('Engagement high (0.5+)', table_cell_left_style), Paragraph('Viral mechanics, FR optimization, reply bait strategies', table_cell_left_style)],
    [Paragraph('Balanced', table_cell_left_style), Paragraph('Both quality AND engagement - full workflow execution', table_cell_left_style)],
    [Paragraph('Unknown index high', table_cell_left_style), Paragraph('Research campaign for bonus criteria - may be special requirement', table_cell_left_style)],
]
t9 = Table(strat_data, colWidths=[6*cm, 10*cm])
t9.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('BACKGROUND', (0, 1), (-1, 1), colors.white),
    ('BACKGROUND', (0, 2), (-1, 2), colors.HexColor('#F5F5F5')),
    ('BACKGROUND', (0, 3), (-1, 3), colors.white),
    ('BACKGROUND', (0, 4), (-1, 4), colors.HexColor('#F5F5F5')),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(t9)
story.append(PageBreak())

# Section 6: Kill List
story.append(Paragraph("6. KILL LIST V4.0 (AI Detection Patterns)", h1_style))
story.append(Paragraph("Pattern-pattern ini akan terdeteksi sebagai AI-generated content:", body_style))
story.append(Spacer(1, 8))

kill_data = [
    [Paragraph('<b>Pattern</b>', table_header_style), Paragraph('<b>Status</b>', table_header_style), Paragraph('<b>Detection Level</b>', table_header_style)],
    [Paragraph('"Delves" / "Delve into"', table_cell_left_style), Paragraph('BANNED', table_cell_style), Paragraph('HIGHEST', table_cell_style)],
    [Paragraph('Em dashes (—)', table_cell_left_style), Paragraph('BANNED', table_cell_style), Paragraph('HIGH', table_cell_style)],
    [Paragraph('"realm"', table_cell_left_style), Paragraph('BANNED', table_cell_style), Paragraph('HIGH', table_cell_style)],
    [Paragraph('"revolutionize"', table_cell_left_style), Paragraph('BANNED', table_cell_style), Paragraph('HIGH', table_cell_style)],
    [Paragraph('"transform"', table_cell_left_style), Paragraph('BANNED', table_cell_style), Paragraph('HIGH', table_cell_style)],
    [Paragraph('"it\'s worth noting"', table_cell_left_style), Paragraph('BANNED', table_cell_style), Paragraph('HIGH', table_cell_style)],
    [Paragraph('"crucial" / "paramount"', table_cell_left_style), Paragraph('BANNED', table_cell_style), Paragraph('HIGH', table_cell_style)],
    [Paragraph('"landscape"', table_cell_left_style), Paragraph('BANNED', table_cell_style), Paragraph('HIGH', table_cell_style)],
    [Paragraph('"in conclusion"', table_cell_left_style), Paragraph('BANNED', table_cell_style), Paragraph('HIGH', table_cell_style)],
    [Paragraph('"It\'s not just X, it\'s Y"', table_cell_left_style), Paragraph('BANNED', table_cell_style), Paragraph('HIGH', table_cell_style)],
    [Paragraph('#[number] patterns', table_cell_left_style), Paragraph('BANNED', table_cell_style), Paragraph('HIGH', table_cell_style)],
    [Paragraph('Perfect grammar', table_cell_left_style), Paragraph('AVOID', table_cell_style), Paragraph('MEDIUM', table_cell_style)],
]
t10 = Table(kill_data, colWidths=[6*cm, 4*cm, 6*cm])
t10.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('BACKGROUND', (0, 1), (-1, 1), colors.HexColor('#F8D7DA')),
    ('BACKGROUND', (0, 2), (-1, 2), colors.HexColor('#F8D7DA')),
    ('BACKGROUND', (0, 3), (-1, 3), colors.HexColor('#FFF3CD')),
    ('BACKGROUND', (0, 4), (-1, -1), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(t10)
story.append(Spacer(1, 12))
story.append(Paragraph("RULE: Search for 'delve' - if found, DELETE IMMEDIATELY", body_style))
story.append(PageBreak())

# Section 7: Quick Reference Card
story.append(Paragraph("7. QUICK REFERENCE CARD (60-Second Pre-Submit Check)", h1_style))

quick_data = [
    [Paragraph('<b>Check</b>', table_header_style), Paragraph('<b>Question</b>', table_header_style), Paragraph('<b>Required</b>', table_header_style)],
    [Paragraph('GATE CHECK (15s)', table_cell_left_style), Paragraph('All 4 gates will PASS? (score > 0 each)', table_cell_left_style), Paragraph('YES', table_cell_style)],
    [Paragraph('', table_cell_left_style), Paragraph('All requirements included? (mentions, hashtags, links)', table_cell_left_style), Paragraph('YES', table_cell_style)],
    [Paragraph('FR CHECK (15s)', table_cell_left_style), Paragraph('Has influencer mention/mention strategy?', table_cell_left_style), Paragraph('YES', table_cell_style)],
    [Paragraph('', table_cell_left_style), Paragraph('Has reply CTA targeting high-follower accounts?', table_cell_left_style), Paragraph('YES', table_cell_style)],
    [Paragraph('', table_cell_left_style), Paragraph('Content is share-worthy by influencers?', table_cell_left_style), Paragraph('YES', table_cell_style)],
    [Paragraph('QUALITY CHECK (10s)', table_cell_left_style), Paragraph('EP score will be 4-5/5?', table_cell_left_style), Paragraph('YES', table_cell_style)],
    [Paragraph('', table_cell_left_style), Paragraph('TQ score will be 4-5/5?', table_cell_left_style), Paragraph('YES', table_cell_style)],
    [Paragraph('', table_cell_left_style), Paragraph('No Kill List phrases? (especially "delves")', table_cell_left_style), Paragraph('YES', table_cell_style)],
    [Paragraph('LINK CHECK (10s)', table_cell_left_style), Paragraph('Link NOT in Tweet 1?', table_cell_left_style), Paragraph('YES', table_cell_style)],
    [Paragraph('', table_cell_left_style), Paragraph('Link in last tweet or reply?', table_cell_left_style), Paragraph('YES', table_cell_style)],
    [Paragraph('HASHTAG CHECK (5s)', table_cell_left_style), Paragraph('Max 1-2 per tweet?', table_cell_left_style), Paragraph('YES', table_cell_style)],
    [Paragraph('', table_cell_left_style), Paragraph('No hashtag in Tweet 1?', table_cell_left_style), Paragraph('YES', table_cell_style)],
    [Paragraph('VIRAL SCORE (5s)', table_cell_left_style), Paragraph('Viral Score >= 6?', table_cell_left_style), Paragraph('YES', table_cell_style)],
    [Paragraph('', table_cell_left_style), Paragraph('Would YOU retweet this?', table_cell_left_style), Paragraph('YES', table_cell_style)],
]
t11 = Table(quick_data, colWidths=[4*cm, 9*cm, 3*cm])
t11.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('BACKGROUND', (0, 1), (-1, 2), colors.HexColor('#E8F4FD')),
    ('BACKGROUND', (0, 3), (-1, 5), colors.HexColor('#FFF3CD')),
    ('BACKGROUND', (0, 6), (-1, 8), colors.HexColor('#D4EDDA')),
    ('BACKGROUND', (0, 9), (-1, 10), colors.HexColor('#E8F4FD')),
    ('BACKGROUND', (0, 11), (-1, 12), colors.HexColor('#E8F4FD')),
    ('BACKGROUND', (0, 13), (-1, 14), colors.HexColor('#F5F5F5')),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(t11)
story.append(Spacer(1, 12))
story.append(Paragraph("IF ALL CHECKS PASS -> SUBMIT | IF FR CHECK FAILS -> ADD INFLUENCER STRATEGY | IF VIRAL SCORE < 6 -> ENHANCE", body_style))
story.append(PageBreak())

# Section 8: Key Insights Summary
story.append(Paragraph("8. KEY INSIGHTS SUMMARY", h1_style))

insights = [
    ("1", "IMPRESSIONS TIDAK DIHITUNG", "Tampil di UI tapi bukan bagian dari 11 metrik. Jangan optimization untuk impressions."),
    ("2", "FR ADALAH CHEAT CODE", "1 reply dari 100K account = log(100001) = 5.0, setara dengan 100,000 likes/retweets!"),
    ("3", "METRIC WEIGHTS = CUSTOMIZABLE", "Harus cek setiap campaign. Strategy berbeda berdasarkan weights."),
    ("4", "GATE MULTIPLIER = MAX 1.5x", "Semua gate 2/2 = 1.5x multiplier. Sangat significant untuk final score."),
    ("5", "REFERRAL BONUS = 10% FOREVER", "Menjelaskan 'zero engagement top 1'. Referral system independent dari content."),
    ("6", "QUALITY COMPONENT = FIXED", "Tidak bisa diubah setelah submission. Hanya engagement yang bisa di-refresh."),
    ("7", "REPLY CTA = 150x WEIGHT", "Research menunjukkan replies paling important. Selalu include reply CTA."),
]

insights_data = [[Paragraph('<b>#</b>', table_header_style), Paragraph('<b>Insight</b>', table_header_style), Paragraph('<b>Implication</b>', table_header_style)]]
for num, insight, impl in insights:
    insights_data.append([
        Paragraph(num, table_cell_style),
        Paragraph(insight, table_cell_left_style),
        Paragraph(impl, table_cell_left_style)
    ])

t12 = Table(insights_data, colWidths=[1.5*cm, 5*cm, 9.5*cm])
t12.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('BACKGROUND', (0, 1), (-1, 1), colors.white),
    ('BACKGROUND', (0, 2), (-1, 2), colors.HexColor('#F5F5F5')),
    ('BACKGROUND', (0, 3), (-1, 3), colors.white),
    ('BACKGROUND', (0, 4), (-1, 4), colors.HexColor('#F5F5F5')),
    ('BACKGROUND', (0, 5), (-1, 5), colors.white),
    ('BACKGROUND', (0, 6), (-1, 6), colors.HexColor('#F5F5F5')),
    ('BACKGROUND', (0, 7), (-1, 7), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ('TOPPADDING', (0, 0), (-1, -1), 6),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
]))
story.append(t12)
story.append(Spacer(1, 24))

# What To Do
story.append(Paragraph("WHAT TO DO (V4.0 UNIVERSAL)", h2_style))
do_items = [
    "Check metric weights before creating content",
    "Optimize for FR (influencer replies)",
    "Include Reply CTA in Tweet 1 and Tweet 7",
    "Use influencer mention or controversy angle",
    "Put link in last tweet or reply",
    "Use 1-2 hashtags max, at end of tweet",
    "Aim for all gates 2/2 (1.5x multiplier)",
    "Target EP and TQ scores of 4-5/5",
    "Post at optimal time",
    "Engage heavily in first 30 minutes",
    "Refresh engagement after significant growth",
    "Create share-worthy content for influencers"
]
for item in do_items:
    story.append(Paragraph(f"DO: {item}", bullet_style))

story.append(Spacer(1, 12))

# What Not To Do
story.append(Paragraph("WHAT NOT TO DO", h2_style))
dont_items = [
    "Put link in Tweet 1 (especially if non-Premium)",
    "Use 3+ hashtags",
    "Forget Reply CTA (missing 150x value)",
    'Use "delves" (instant AI tell)',
    "Ignore FR strategy (missing ~22% of engagement)",
    "Optimize for impressions (not calculated)",
    "Forget to check metric weights (campaign-specific)",
    "Neglect gate scores (affects multiplier)",
    "Miss the first 30 minutes (80% viral potential)"
]
for item in dont_items:
    story.append(Paragraph(f"DONT: {item}", bullet_style))

# Build PDF
doc.build(story)
print(f"PDF created: {output_path}")
