from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.units import inch, cm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily
import os

# Register fonts
pdfmetrics.registerFont(TTFont('SimHei', '/usr/share/fonts/truetype/chinese/SimHei.ttf'))
pdfmetrics.registerFont(TTFont('Microsoft YaHei', '/usr/share/fonts/truetype/chinese/msyh.ttf'))
pdfmetrics.registerFont(TTFont('Times New Roman', '/usr/share/fonts/truetype/english/Times-New-Roman.ttf'))

registerFontFamily('SimHei', normal='SimHei', bold='SimHei')
registerFontFamily('Microsoft YaHei', normal='Microsoft YaHei', bold='Microsoft YaHei')
registerFontFamily('Times New Roman', normal='Times New Roman', bold='Times New Roman')

# Create document
output_path = "/home/z/my-project/download/Rally_Workflow_V5.0_Ultimate.pdf"
doc = SimpleDocTemplate(output_path, pagesize=A4, 
                        topMargin=1.5*cm, bottomMargin=1.5*cm,
                        leftMargin=1.5*cm, rightMargin=1.5*cm,
                        title="Rally_Workflow_V5.0_Ultimate",
                        author="Z.ai",
                        creator="Z.ai",
                        subject="Rally Ultimate Workflow V5.0")

styles = getSampleStyleSheet()

# Define styles
title_style = ParagraphStyle(
    name='Title',
    fontName='Microsoft YaHei',
    fontSize=24,
    leading=32,
    alignment=TA_CENTER,
    spaceAfter=12
)

subtitle_style = ParagraphStyle(
    name='Subtitle',
    fontName='SimHei',
    fontSize=12,
    leading=18,
    alignment=TA_CENTER,
    spaceAfter=6
)

h1_style = ParagraphStyle(
    name='H1',
    fontName='Microsoft YaHei',
    fontSize=14,
    leading=20,
    alignment=TA_LEFT,
    spaceBefore=12,
    spaceAfter=8,
    textColor=colors.HexColor('#1F4E79')
)

h2_style = ParagraphStyle(
    name='H2',
    fontName='Microsoft YaHei',
    fontSize=11,
    leading=16,
    alignment=TA_LEFT,
    spaceBefore=8,
    spaceAfter=6,
    textColor=colors.HexColor('#2E75B6')
)

body_style = ParagraphStyle(
    name='Body',
    fontName='SimHei',
    fontSize=9,
    leading=14,
    alignment=TA_LEFT,
    spaceAfter=4,
    wordWrap='CJK'
)

code_style = ParagraphStyle(
    name='Code',
    fontName='Times New Roman',
    fontSize=8,
    leading=12,
    alignment=TA_LEFT,
    leftIndent=10,
    spaceAfter=4,
    backColor=colors.HexColor('#F5F5F5')
)

table_header_style = ParagraphStyle(
    name='TableHeader',
    fontName='Microsoft YaHei',
    fontSize=8,
    leading=11,
    alignment=TA_CENTER,
    textColor=colors.white,
    wordWrap='CJK'
)

table_cell_style = ParagraphStyle(
    name='TableCell',
    fontName='SimHei',
    fontSize=8,
    leading=11,
    alignment=TA_CENTER,
    wordWrap='CJK'
)

table_cell_left_style = ParagraphStyle(
    name='TableCellLeft',
    fontName='SimHei',
    fontSize=8,
    leading=11,
    alignment=TA_LEFT,
    wordWrap='CJK'
)

story = []

# Cover Page
story.append(Spacer(1, 2*cm))
story.append(Paragraph("RALLY WORKFLOW V5.0", title_style))
story.append(Paragraph("ULTIMATE COMPLETE EDITION", title_style))
story.append(Spacer(1, 0.5*cm))
story.append(Paragraph("Menggabungkan Semua Workflow V3.13-V4.0", subtitle_style))
story.append(Paragraph("Efektivitas: 95-100% | Universal untuk Semua Campaign", subtitle_style))
story.append(Spacer(1, 1*cm))
story.append(Paragraph("Key Features:", h2_style))
features = [
    "Metric Weights Detection (campaign-specific)",
    "FR (Followers of Repliers) Cheat Code Strategy",
    "Gate Multiplier Formula (1.5x max bonus)",
    "Distribution Curves Strategy Adaptation",
    "11 Metrik Resmi Rally + Formula Lengkap",
    "Multi-Version Generation (5 angles)",
    "Quality Scoring (HES 100-point + 4-point)",
    "Iterative Refinement (3 iterations max)",
    "Micro-Optimization (word/char level)",
    "Viral Mechanics Layer (8 triggers)",
    "Psychological Triggers (8 triggers)",
    "Network Effect Amplification",
    "A/B Testing Framework",
    "Complete 18-Phase Workflow"
]
for f in features:
    story.append(Paragraph(f"• {f}", body_style))
story.append(Spacer(1, 1*cm))
story.append(Paragraph("Completeness: 100% | All versions merged", subtitle_style))
story.append(Paragraph("Generated by Z.ai", subtitle_style))
story.append(PageBreak())

# Section 1: Rally Scoring System
story.append(Paragraph("SECTION 1: RALLY SCORING SYSTEM", h1_style))

story.append(Paragraph("1.1 THE 11 OFFICIAL METRICS", h2_style))

metrics_data = [
    [Paragraph('<b>Category</b>', table_header_style), Paragraph('<b>Metric</b>', table_header_style), Paragraph('<b>Scale</b>', table_header_style), Paragraph('<b>Description</b>', table_header_style)],
    [Paragraph('GATES', table_cell_style), Paragraph('G1: Content Alignment', table_cell_left_style), Paragraph('0-2', table_cell_style), Paragraph('Message accuracy, brand consistency', table_cell_left_style)],
    [Paragraph('', table_cell_style), Paragraph('G2: Information Accuracy', table_cell_left_style), Paragraph('0-2', table_cell_style), Paragraph('Factual correctness', table_cell_left_style)],
    [Paragraph('', table_cell_style), Paragraph('G3: Campaign Compliance', table_cell_left_style), Paragraph('0-2', table_cell_style), Paragraph('Hashtags, mentions, format', table_cell_left_style)],
    [Paragraph('', table_cell_style), Paragraph('G4: Originality', table_cell_left_style), Paragraph('0-2', table_cell_style), Paragraph('Fresh perspective, authentic', table_cell_left_style)],
    [Paragraph('QUALITY', table_cell_style), Paragraph('EP: Engagement Potential', table_cell_left_style), Paragraph('0-5', table_cell_style), Paragraph('Hook, CTA, structure', table_cell_left_style)],
    [Paragraph('', table_cell_style), Paragraph('TQ: Technical Quality', table_cell_left_style), Paragraph('0-5', table_cell_style), Paragraph('Grammar, formatting', table_cell_left_style)],
    [Paragraph('ENGAGEMENT', table_cell_style), Paragraph('RT: Retweets', table_cell_left_style), Paragraph('log(RT+1)', table_cell_style), Paragraph('Amplification', table_cell_left_style)],
    [Paragraph('', table_cell_style), Paragraph('LK: Likes', table_cell_left_style), Paragraph('log(LK+1)', table_cell_style), Paragraph('Appreciation', table_cell_left_style)],
    [Paragraph('', table_cell_style), Paragraph('RP: Replies', table_cell_left_style), Paragraph('log(RP+1)', table_cell_style), Paragraph('Conversation', table_cell_left_style)],
    [Paragraph('', table_cell_style), Paragraph('QR: Quality of Replies', table_cell_left_style), Paragraph('0-1 AI', table_cell_style), Paragraph('Relevance, civility', table_cell_left_style)],
    [Paragraph('', table_cell_style), Paragraph('FR: Followers of Repliers', table_cell_left_style), Paragraph('log(Total+1)', table_cell_style), Paragraph('CHEAT CODE', table_cell_left_style)],
]
t = Table(metrics_data, colWidths=[2*cm, 4.5*cm, 2*cm, 6.5*cm])
t.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('BACKGROUND', (0, 1), (-1, 4), colors.HexColor('#E8F4FD')),
    ('BACKGROUND', (0, 5), (-1, 6), colors.HexColor('#FFF3CD')),
    ('BACKGROUND', (0, 7), (-1, -1), colors.white),
    ('BACKGROUND', (0, -1), (-1, -1), colors.HexColor('#D4EDDA')),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 4),
    ('RIGHTPADDING', (0, 0), (-1, -1), 4),
    ('TOPPADDING', (0, 0), (-1, -1), 4),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
]))
story.append(t)
story.append(Spacer(1, 8))
story.append(Paragraph("IMPRESSIONS = TIDAK DIHITUNG (hanya tampil di UI)", body_style))
story.append(Spacer(1, 12))

story.append(Paragraph("1.2 GATE MULTIPLIER FORMULA", h2_style))
story.append(Paragraph("M_gate = 1 + 0.5 × (g_star - 1)", code_style))
gate_data = [
    [Paragraph('<b>Gate Scores</b>', table_header_style), Paragraph('<b>g_star</b>', table_header_style), Paragraph('<b>M_gate</b>', table_header_style), Paragraph('<b>Effect</b>', table_header_style)],
    [Paragraph('All 2/2', table_cell_left_style), Paragraph('2.0', table_cell_style), Paragraph('1.5x', table_cell_style), Paragraph('MAXIMUM BONUS', table_cell_left_style)],
    [Paragraph('All 1.5/2', table_cell_left_style), Paragraph('1.5', table_cell_style), Paragraph('1.25x', table_cell_style), Paragraph('GOOD BONUS', table_cell_left_style)],
    [Paragraph('All 1/2', table_cell_left_style), Paragraph('1.0', table_cell_style), Paragraph('1.0x', table_cell_style), Paragraph('BASELINE', table_cell_left_style)],
    [Paragraph('Any 0/2', table_cell_left_style), Paragraph('FAIL', table_cell_style), Paragraph('N/A', table_cell_style), Paragraph('DISQUALIFIED', table_cell_left_style)],
]
t2 = Table(gate_data, colWidths=[3.5*cm, 2.5*cm, 2.5*cm, 6.5*cm])
t2.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('BACKGROUND', (0, 1), (-1, 1), colors.HexColor('#D4EDDA')),
    ('BACKGROUND', (0, 2), (-1, 2), colors.white),
    ('BACKGROUND', (0, 3), (-1, 3), colors.HexColor('#F5F5F5')),
    ('BACKGROUND', (0, 4), (-1, 4), colors.HexColor('#F8D7DA')),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 4),
    ('RIGHTPADDING', (0, 0), (-1, -1), 4),
    ('TOPPADDING', (0, 0), (-1, -1), 4),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
]))
story.append(t2)
story.append(Spacer(1, 8))
story.append(Paragraph("CRITICAL: All gates 2/2 = 50% BONUS to entire score!", body_style))
story.append(PageBreak())

# Section 2: FR Cheat Code
story.append(Paragraph("SECTION 2: FR (FOLLOWERS OF REPLIERS) CHEAT CODE", h1_style))

story.append(Paragraph("2.1 WHY FR IS THE MOST POWERFUL METRIC", h2_style))
story.append(Paragraph("FR Formula: log(Sum of Followers of All Repliers + 1)", code_style))
story.append(Spacer(1, 6))

fr_data = [
    [Paragraph('<b>Scenario</b>', table_header_style), Paragraph('<b>Total Followers</b>', table_header_style), Paragraph('<b>FR Score</b>', table_header_style), Paragraph('<b>Equivalent</b>', table_header_style)],
    [Paragraph('1 reply from 100K account', table_cell_left_style), Paragraph('100,000', table_cell_style), Paragraph('~5.0', table_cell_style), Paragraph('= 100,000 likes', table_cell_left_style)],
    [Paragraph('10 replies from 10K each', table_cell_left_style), Paragraph('100,000', table_cell_style), Paragraph('~5.0', table_cell_style), Paragraph('= 100,000 RTs', table_cell_left_style)],
    [Paragraph('1 reply from 1M account', table_cell_left_style), Paragraph('1,000,000', table_cell_style), Paragraph('~6.0', table_cell_style), Paragraph('= 1,000,000 likes', table_cell_left_style)],
    [Paragraph('100 replies from 100 each', table_cell_left_style), Paragraph('10,000', table_cell_style), Paragraph('~4.0', table_cell_style), Paragraph('= 10,000 likes', table_cell_left_style)],
]
t3 = Table(fr_data, colWidths=[5*cm, 3*cm, 2.5*cm, 4.5*cm])
t3.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('BACKGROUND', (0, 1), (-1, -1), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 4),
    ('RIGHTPADDING', (0, 0), (-1, -1), 4),
    ('TOPPADDING', (0, 0), (-1, -1), 4),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
]))
story.append(t3)
story.append(Spacer(1, 6))
story.append(Paragraph("KEY INSIGHT: 1 reply from influencer > 100 replies from small accounts!", body_style))
story.append(Paragraph("FR contributes ~22% of total engagement score!", body_style))
story.append(Spacer(1, 12))

story.append(Paragraph("2.2 FR OPTIMIZATION STRATEGIES", h2_style))
fr_strat = [
    [Paragraph('<b>Strategy</b>', table_header_style), Paragraph('<b>Implementation</b>', table_header_style), Paragraph('<b>FR Boost</b>', table_header_style)],
    [Paragraph('High-Follower Reply Bait', table_cell_left_style), Paragraph('@[influencer] thoughts? Direct mention', table_cell_left_style), Paragraph('+300%', table_cell_style)],
    [Paragraph('Thread Jacking', table_cell_left_style), Paragraph('Reply to influencer threads with value', table_cell_left_style), Paragraph('+200%', table_cell_style)],
    [Paragraph('Controversy Angle', table_cell_left_style), Paragraph('"Unpopular opinion:", "Change my mind"', table_cell_left_style), Paragraph('+250%', table_cell_style)],
    [Paragraph('Community Engagement', table_cell_left_style), Paragraph('Build relationships with medium accounts', table_cell_left_style), Paragraph('+150%', table_cell_style)],
]
t4 = Table(fr_strat, colWidths=[4*cm, 8*cm, 3*cm])
t4.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('BACKGROUND', (0, 1), (-1, -1), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 4),
    ('RIGHTPADDING', (0, 0), (-1, -1), 4),
    ('TOPPADDING', (0, 0), (-1, -1), 4),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
]))
story.append(t4)
story.append(PageBreak())

# Section 3: Thread Structure
story.append(Paragraph("SECTION 3: THREAD STRUCTURE (7 TWEETS OPTIMAL)", h1_style))

thread_data = [
    [Paragraph('<b>Tweet</b>', table_header_style), Paragraph('<b>Technical</b>', table_header_style), Paragraph('<b>Focus</b>', table_header_style), Paragraph('<b>Viral Mechanic</b>', table_header_style), Paragraph('<b>FR Strategy</b>', table_header_style)],
    [Paragraph('1', table_cell_style), Paragraph('LOW', table_cell_style), Paragraph('Hook + Reply CTA', table_cell_left_style), Paragraph('CONTROVERSY', table_cell_style), Paragraph('Influencer mention', table_cell_left_style)],
    [Paragraph('2', table_cell_style), Paragraph('LOW-MED', table_cell_style), Paragraph('Problem', table_cell_left_style), Paragraph('RELATABLE PAIN', table_cell_style), Paragraph('Community', table_cell_left_style)],
    [Paragraph('3', table_cell_style), Paragraph('MEDIUM', table_cell_style), Paragraph('Solution + Reply CTA', table_cell_left_style), Paragraph('AHA MOMENT', table_cell_style), Paragraph('Question', table_cell_left_style)],
    [Paragraph('4', table_cell_style), Paragraph('MED-HIGH', table_cell_style), Paragraph('How it works', table_cell_left_style), Paragraph('CONTRAST', table_cell_style), Paragraph('Authority', table_cell_left_style)],
    [Paragraph('5', table_cell_style), Paragraph('HIGH', table_cell_style), Paragraph('Deep dive', table_cell_left_style), Paragraph('HARD TRUTH', table_cell_style), Paragraph('Expert', table_cell_left_style)],
    [Paragraph('6', table_cell_style), Paragraph('MEDIUM', table_cell_style), Paragraph('Value summary', table_cell_left_style), Paragraph('CHECKLIST', table_cell_style), Paragraph('Utility', table_cell_left_style)],
    [Paragraph('7', table_cell_style), Paragraph('LOW', table_cell_style), Paragraph('CTA + Link + Reply', table_cell_left_style), Paragraph('FOMO + CONTEST', table_cell_style), Paragraph('Final push', table_cell_left_style)],
]
t5 = Table(thread_data, colWidths=[1.5*cm, 2*cm, 3.5*cm, 3.5*cm, 4.5*cm])
t5.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('BACKGROUND', (0, 1), (-1, 1), colors.HexColor('#E8F4FD')),
    ('BACKGROUND', (0, 2), (-1, 2), colors.white),
    ('BACKGROUND', (0, 3), (-1, 3), colors.HexColor('#E8F4FD')),
    ('BACKGROUND', (0, 4), (-1, 4), colors.white),
    ('BACKGROUND', (0, 5), (-1, 5), colors.HexColor('#E8F4FD')),
    ('BACKGROUND', (0, 6), (-1, 6), colors.white),
    ('BACKGROUND', (0, 7), (-1, 7), colors.HexColor('#E8F4FD')),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 4),
    ('RIGHTPADDING', (0, 0), (-1, -1), 4),
    ('TOPPADDING', (0, 0), (-1, -1), 4),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
]))
story.append(t5)
story.append(Spacer(1, 8))
story.append(Paragraph("RULE: Spend 60% of time on Tweet 1", body_style))
story.append(Paragraph("RULE: Minimum 2 Reply CTAs per thread", body_style))
story.append(Paragraph("RULE: At least ONE contest/challenge format", body_style))
story.append(PageBreak())

# Section 4: Kill List
story.append(Paragraph("SECTION 4: KILL LIST (AI DETECTION)", h1_style))

kill_data = [
    [Paragraph('<b>Pattern</b>', table_header_style), Paragraph('<b>Status</b>', table_header_style), Paragraph('<b>Detection</b>', table_header_style)],
    [Paragraph('"Delves" / "Delve into"', table_cell_left_style), Paragraph('BANNED', table_cell_style), Paragraph('HIGHEST', table_cell_style)],
    [Paragraph('Em dashes (—)', table_cell_left_style), Paragraph('BANNED', table_cell_style), Paragraph('HIGH', table_cell_style)],
    [Paragraph('"It\'s not just X, it\'s Y"', table_cell_left_style), Paragraph('BANNED', table_cell_style), Paragraph('HIGH', table_cell_style)],
    [Paragraph('"realm"', table_cell_left_style), Paragraph('BANNED', table_cell_style), Paragraph('HIGH', table_cell_style)],
    [Paragraph('"revolutionize"', table_cell_left_style), Paragraph('BANNED', table_cell_style), Paragraph('HIGH', table_cell_style)],
    [Paragraph('"transform"', table_cell_left_style), Paragraph('BANNED', table_cell_style), Paragraph('HIGH', table_cell_style)],
    [Paragraph('"crucial" / "paramount"', table_cell_left_style), Paragraph('BANNED', table_cell_style), Paragraph('HIGH', table_cell_style)],
    [Paragraph('"landscape"', table_cell_left_style), Paragraph('BANNED', table_cell_style), Paragraph('HIGH', table_cell_style)],
    [Paragraph('"in conclusion"', table_cell_left_style), Paragraph('BANNED', table_cell_style), Paragraph('HIGH', table_cell_style)],
    [Paragraph('"Let\'s explore"', table_cell_left_style), Paragraph('BANNED', table_cell_style), Paragraph('HIGH', table_cell_style)],
    [Paragraph('#[number] patterns', table_cell_left_style), Paragraph('BANNED', table_cell_style), Paragraph('HIGH', table_cell_style)],
    [Paragraph('Perfect grammar', table_cell_left_style), Paragraph('BANNED', table_cell_style), Paragraph('MEDIUM', table_cell_style)],
]
t6 = Table(kill_data, colWidths=[5*cm, 3*cm, 3*cm])
t6.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('BACKGROUND', (0, 1), (-1, 1), colors.HexColor('#F8D7DA')),
    ('BACKGROUND', (0, 2), (-1, -1), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 4),
    ('RIGHTPADDING', (0, 0), (-1, -1), 4),
    ('TOPPADDING', (0, 0), (-1, -1), 4),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
]))
story.append(t6)
story.append(Spacer(1, 8))
story.append(Paragraph("RULE: Search for 'delve' - if found, DELETE IMMEDIATELY", body_style))
story.append(PageBreak())

# Section 5: Quality Scoring
story.append(Paragraph("SECTION 5: QUALITY SCORING SYSTEMS", h1_style))

story.append(Paragraph("5.1 HES CHECK (4-POINT)", h2_style))
hes_data = [
    [Paragraph('<b>Check</b>', table_header_style), Paragraph('<b>Question</b>', table_header_style), Paragraph('<b>Score</b>', table_header_style)],
    [Paragraph('EMOTIONAL HOOK', table_cell_left_style), Paragraph('Can you FEEL it?', table_cell_left_style), Paragraph('0/1', table_cell_style)],
    [Paragraph('REPLY CTA', table_cell_left_style), Paragraph('Can people easily reply?', table_cell_left_style), Paragraph('0/1', table_cell_style)],
    [Paragraph('CURIOSITY GAP', table_cell_left_style), Paragraph('Do you want to know more?', table_cell_left_style), Paragraph('0/1', table_cell_style)],
    [Paragraph('NO AI PATTERNS', table_cell_left_style), Paragraph('No Kill List items?', table_cell_left_style), Paragraph('0/1', table_cell_style)],
]
t7 = Table(hes_data, colWidths=[4*cm, 7*cm, 2*cm])
t7.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('BACKGROUND', (0, 1), (-1, -1), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 4),
    ('RIGHTPADDING', (0, 0), (-1, -1), 4),
    ('TOPPADDING', (0, 0), (-1, -1), 4),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
]))
story.append(t7)
story.append(Spacer(1, 6))
story.append(Paragraph("4/4 = SUBMIT | 3/4 = Consider revision | < 3/4 = REVISE", body_style))
story.append(Spacer(1, 12))

story.append(Paragraph("5.2 HES CALCULATOR (100-POINT)", h2_style))
hes100_data = [
    [Paragraph('<b>Component</b>', table_header_style), Paragraph('<b>Max</b>', table_header_style), Paragraph('<b>Guide</b>', table_header_style)],
    [Paragraph('Emotional Resonance', table_cell_left_style), Paragraph('25 pts', table_cell_style), Paragraph('25=Visceral, 20=Strong, 15=Moderate', table_cell_left_style)],
    [Paragraph('Curiosity Gap', table_cell_left_style), Paragraph('25 pts', table_cell_style), Paragraph('25=MUST click, 20=Strong, 15=Moderate', table_cell_left_style)],
    [Paragraph('Broad Appeal', table_cell_left_style), Paragraph('25 pts', table_cell_style), Paragraph('25=Universal, 20=Most, 15=Niche', table_cell_left_style)],
    [Paragraph('Clarity', table_cell_left_style), Paragraph('25 pts', table_cell_style), Paragraph('25=Instant, 20=One read, 15=Second read', table_cell_left_style)],
]
t8 = Table(hes100_data, colWidths=[4*cm, 2*cm, 8*cm])
t8.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E79')),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
    ('BACKGROUND', (0, 1), (-1, -1), colors.white),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 4),
    ('RIGHTPADDING', (0, 0), (-1, -1), 4),
    ('TOPPADDING', (0, 0), (-1, -1), 4),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
]))
story.append(t8)
story.append(Spacer(1, 6))
story.append(Paragraph("90-100 = EXCEPTIONAL | 80-89 = EXCELLENT | 70-79 = GOOD | < 70 = REVISE", body_style))
story.append(Spacer(1, 12))

story.append(Paragraph("5.3 VIRAL SCORE (0-10)", h2_style))
viral_items = [
    "1. Controversial/challenge angle",
    "2. Share-worthy format",
    "3. Reply bait (contest/challenge)",
    "4. Emotional trigger",
    "5. Cultural relevance",
    "6. Memorable hook",
    "7. FOMO/urgency",
    "8. Personal story element",
    "9. Contrast/comparison",
    "10. Call-out/identity trigger"
]
for item in viral_items:
    story.append(Paragraph(f"• {item} (0-1 pt each)", body_style))
story.append(Spacer(1, 6))
story.append(Paragraph("8-10 = VIRAL READY | 6-7 = GOOD | < 6 = REVISE", body_style))
story.append(PageBreak())

# Section 6: Quick Reference
story.append(Paragraph("SECTION 6: 60-SECOND PRE-SUBMIT CHECK", h1_style))

checklist_items = [
    ("GATE CHECK (10 sec)", ["All 4 gates will PASS?", "All requirements included?"]),
    ("HOOK CHECK (15 sec)", ["EMOTIONAL?", "CURIOSITY?", "NO DELVES?", "CONTROVERSIAL?"]),
    ("REPLY CHECK (15 sec)", ["Has Reply CTA?", "Contest/Challenge?", "FR-targeting?", "Easy to answer?"]),
    ("LINK CHECK (10 sec)", ["Link NOT in Tweet 1?", "Link in last/reply?", "No shortened URLs?"]),
    ("HASHTAG CHECK (5 sec)", ["Max 1-2 per tweet?", "No hashtag in Tweet 1?"]),
    ("SCORE CHECK (5 sec)", ["HES >= 80?", "Viral Score >= 6?", "Would YOU retweet?"]),
]

for title, items in checklist_items:
    story.append(Paragraph(f"<b>{title}</b>", body_style))
    for item in items:
        story.append(Paragraph(f"  [ ] {item}", body_style))
    story.append(Spacer(1, 4))

story.append(Spacer(1, 12))
story.append(Paragraph("<b>IF ALL CHECKS PASS → SUBMIT</b>", body_style))
story.append(Paragraph("<b>IF FR CHECK FAILS → ADD INFLUENCER STRATEGY</b>", body_style))
story.append(Paragraph("<b>IF VIRAL SCORE < 6 → ENHANCE BEFORE SUBMIT</b>", body_style))
story.append(Paragraph("<b>IF HES < 80 → REVISE HOOK</b>", body_style))
story.append(PageBreak())

# Section 7: What To Do / Not To Do
story.append(Paragraph("SECTION 7: WHAT TO DO / NOT TO DO", h1_style))

story.append(Paragraph("WHAT NOT TO DO:", h2_style))
dont_items = [
    "Put link in Tweet 1 (ZERO reach for non-Premium)",
    "Use 3+ hashtags (-21% penalty)",
    "Forget Reply CTA (missing 150x value)",
    "Use 'delves' (instant AI tell)",
    "Ignore FR strategy (missing ~22% of engagement)",
    "Optimize for impressions (not calculated)",
    "Forget to check metric weights",
    "Neglect gate scores (affects multiplier)",
    "Miss the first 30 minutes (80% viral potential)"
]
for item in dont_items:
    story.append(Paragraph(f"❌ {item}", body_style))
story.append(Spacer(1, 12))

story.append(Paragraph("WHAT TO DO:", h2_style))
do_items = [
    "Check metric weights BEFORE creating content",
    "Optimize for FR (influencer replies)",
    "Include Reply CTA in Tweet 1 and Tweet 7",
    "Use influencer mention or controversy angle",
    "Put link in last tweet or reply",
    "Use 1-2 hashtags max, at end of tweet",
    "Aim for all gates 2/2 (1.5x multiplier)",
    "Target HES >= 80 and Viral Score >= 6",
    "Post at optimal time (Wed 9 AM EST)",
    "Engage heavily in first 30 minutes",
    "Create multiple versions (5 angles)",
    "Iterate up to 3 times if needed"
]
for item in do_items:
    story.append(Paragraph(f"✅ {item}", body_style))

# Build PDF
doc.build(story)
print(f"PDF created: {output_path}")
